package main

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"embed"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Generated by tools/build-release.py. Not a committed binary dependency.
//
//go:embed payload.bin
var payloadFS embed.FS

type FileRecord struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
	Size   int64  `json:"size"`
}
type PackageManifest struct {
	Schema  int          `json:"schema"`
	Product string       `json:"product"`
	Version string       `json:"version"`
	Files   []FileRecord `json:"files"`
	Runtime struct {
		Version string   `json:"version"`
		SHA256  string   `json:"sha256"`
		URLs    []string `json:"urls"`
	} `json:"runtime"`
}
type Package struct {
	Zip      *zip.Reader
	Manifest PackageManifest
	Files    map[string]*zip.File
}

func loadPackage() (*Package, error) {
	raw, err := payloadFS.ReadFile("payload.bin")
	if err != nil {
		return nil, err
	}
	const magic = "PULSEDECK-PAYLOAD\x00"
	if len(raw) < len(magic)+8 || string(raw[:len(magic)]) != magic {
		return nil, errors.New("bad payload header")
	}
	size := binary.LittleEndian.Uint64(raw[len(magic):])
	raw = raw[len(magic)+8:]
	if size != uint64(len(raw)) {
		return nil, errors.New("bad payload size")
	}
	z, err := zip.NewReader(bytes.NewReader(raw), int64(len(raw)))
	if err != nil {
		return nil, err
	}
	p := &Package{Zip: z, Files: map[string]*zip.File{}}
	for _, f := range z.File {
		if !safeRelative(f.Name) || (f.UncompressedSize64 > 64*1024*1024 && (f.Name != "runtime/electron.zip" || f.UncompressedSize64 > 600*1024*1024)) || f.Mode()&os.ModeSymlink != 0 {
			return nil, errors.New("unsafe payload")
		}
		if _, ok := p.Files[f.Name]; ok {
			return nil, errors.New("duplicate payload file")
		}
		p.Files[f.Name] = f
	}
	f, ok := p.Files["manifest.json"]
	if !ok {
		return nil, errors.New("manifest missing")
	}
	data, err := zipBytes(f, 4*1024*1024)
	if err != nil {
		return nil, err
	}
	if err = json.Unmarshal(data, &p.Manifest); err != nil {
		return nil, err
	}
	if p.Manifest.Schema != 1 || p.Manifest.Product != "com.pulsedeck.music" || p.Manifest.Version == "" {
		return nil, errors.New("wrong payload product")
	}
	if !regexp.MustCompile(`^\d+\.\d+\.\d+(?:-[A-Za-z0-9.-]+)?$`).MatchString(p.Manifest.Runtime.Version) || !regexp.MustCompile(`^[a-f0-9]{64}$`).MatchString(p.Manifest.Runtime.SHA256) || len(p.Manifest.Runtime.URLs) == 0 {
		return nil, errors.New("invalid runtime pin")
	}
	for _, address := range p.Manifest.Runtime.URLs {
		if !runtimeURLAllowed(address) {
			return nil, errors.New("untrusted runtime source")
		}
	}
	return p, nil
}
func safeRelative(s string) bool {
	if s == "" || strings.ContainsAny(s, "\\:\x00") || strings.HasPrefix(s, "/") || filepath.IsAbs(s) {
		return false
	}
	for _, part := range strings.Split(s, "/") {
		if part == "." || part == ".." {
			return false
		}
	}
	return true
}
func zipBytes(f *zip.File, limit int64) ([]byte, error) {
	r, e := f.Open()
	if e != nil {
		return nil, e
	}
	defer r.Close()
	b, e := io.ReadAll(io.LimitReader(r, limit+1))
	if int64(len(b)) > limit {
		return nil, errors.New("payload file too large")
	}
	return b, e
}
func fileHash(name string) (string, error) {
	f, e := os.Open(name)
	if e != nil {
		return "", e
	}
	defer f.Close()
	h := sha256.New()
	_, e = io.Copy(h, f)
	return hex.EncodeToString(h.Sum(nil)), e
}
func copyFile(src, dst string, mode fs.FileMode) error {
	in, e := os.Open(src)
	if e != nil {
		return e
	}
	defer in.Close()
	if e = os.MkdirAll(filepath.Dir(dst), 0700); e != nil {
		return e
	}
	out, e := os.OpenFile(dst, os.O_CREATE|os.O_EXCL|os.O_WRONLY, mode)
	if e != nil {
		return e
	}
	_, e = io.Copy(out, in)
	if e == nil {
		e = out.Sync()
	}
	closeErr := out.Close()
	if e != nil {
		return e
	}
	return closeErr
}
func (p *Package) extract(dest string, notify func(Event)) error {
	for i, record := range p.Manifest.Files {
		if !safeRelative(record.Path) {
			return errors.New("unsafe manifest path")
		}
		zf, ok := p.Files[record.Path]
		if !ok {
			return errors.New("payload file missing")
		}
		b, e := zipBytes(zf, 64*1024*1024)
		if e != nil {
			return e
		}
		sum := sha256.Sum256(b)
		if int64(len(b)) != record.Size || hex.EncodeToString(sum[:]) != record.SHA256 {
			return errors.New("payload checksum mismatch")
		}
		target := filepath.Join(dest, filepath.FromSlash(record.Path))
		if e = os.MkdirAll(filepath.Dir(target), 0700); e != nil {
			return e
		}
		if e = os.WriteFile(target, b, 0600); e != nil {
			return e
		}
		if notify != nil {
			notify(Event{Phase: "extracting", Done: i + 1, Total: len(p.Manifest.Files), Percent: float64(i+1) / float64(len(p.Manifest.Files)) * 100})
		}
	}
	return nil
}
