'use strict';
const test=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const U=require('../app/updates/upstream-components'),T=require('../app/updates/transport'),{ComponentManager}=require('../app/updates/components'),{resolveStorage}=require('../app/storage-paths');
const exe=Buffer.from('MZ local component fixture; not executable'),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),v='2026.08.19',api='https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest',prefix=`https://github.com/yt-dlp/yt-dlp/releases/download/${v}/`;
function release(){return {tag_name:v,draft:false,prerelease:false,assets:[{name:'yt-dlp.exe',size:exe.length,browser_download_url:prefix+'yt-dlp.exe',digest:'sha256:'+sha(exe)},{name:'SHA2-256SUMS',browser_download_url:prefix+'SHA2-256SUMS'}]};}
function routes(){return {[api]:JSON.stringify(release()),[prefix+'SHA2-256SUMS']:sha(exe)+'  yt-dlp.exe\n','https://www.gyan.dev/ffmpeg/builds/release-version':'9.0.2\n','https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-9.0.2-essentials_build.zip.sha256':'a'.repeat(64)};}
function transport(map=routes(),calls=[]){return {...T,jsonBytes:async(url,opts)=>{calls.push(url);opts.validate(url);if(opts.signal?.aborted)throw Object.assign(Error('cancelled'),{code:'UPDATE_CANCELLED'});if(!Object.hasOwn(map,url))throw Object.assign(Error('fixture network error'),{code:'UPDATE_NETWORK_ERROR'});if(map[url] instanceof Error)throw map[url];const b=Buffer.from(map[url]);if(b.length>opts.maxBytes)throw Object.assign(Error('oversize'),{code:'UPDATE_MANIFEST_TOO_LARGE'});return b;},download:async(file,dest,{onProgress})=>{fs.writeFileSync(dest,exe);onProgress?.({percent:100});}};}
async function fixture(fn){const install=fs.mkdtempSync(path.join(os.tmpdir(),'pd291-'));const m=new ComponentManager({root:path.join(install,'components'),legacy:path.join(install,'tools'),config:{},current:'2.9.1',platform:'win32',transport:transport(),probe:async()=>{}});try{return await fn({install,m});}finally{m.cancel();fs.rmSync(install,{recursive:true,force:true});}}
function pin(version=v){return {id:'ytdlp',version,format:'exe',origin:'upstream',file:{url:`https://github.com/yt-dlp/yt-dlp/releases/download/${version}/yt-dlp.exe`,size:exe.length,sha256:sha(exe)}};}
for(const [label,text,name] of [['raw','A'.repeat(64),''],['GNU',sha(exe)+'  yt-dlp.exe\n','yt-dlp.exe'],['binary GNU',sha(exe)+' *yt-dlp.exe','yt-dlp.exe']])test('291 publisher checksum '+label,()=>A.match(U.checksum(Buffer.from(text),name),/^[a-f0-9]{64}$/));
for(const text of ['no hash','a'.repeat(63),'a'.repeat(64)+'  other.exe','\0'+sha(exe)])test('291 rejects unusable checksum '+JSON.stringify(text.slice(0,16)),()=>A.throws(()=>U.checksum(Buffer.from(text),'yt-dlp.exe'),{code:'COMPONENT_BAD_CHECKSUM'}));
test('291 yt-dlp resolves official Windows asset and cross-checks two digests',async()=>{const calls=[],c=await U.fetchComponent('ytdlp',transport(routes(),calls));A.equal(c.origin,'upstream');A.equal(c.file.sha256,sha(exe));A.equal(c.file.size,exe.length);A.deepEqual(calls,[api,prefix+'SHA2-256SUMS']);});
test('291 FFmpeg metadata is locked to a version-specific archive and checksum',async()=>{const c=await U.fetchComponent('ffmpeg',transport());A.equal(c.version,'9.0.2');A.equal(c.file.url,'https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-9.0.2-essentials_build.zip');A.equal(c.file.maxSize,536870912);});
test('291 GitHub asset digest is usable when checksum list is not published',async()=>{const map=routes(),r=release();r.assets.pop();map[api]=JSON.stringify(r);A.equal((await U.fetchComponent('ytdlp',transport(map))).file.sha256,sha(exe));});
for(const [label,change,code] of [
 ['wrong hash',r=>r.assets[0].digest='sha256:'+'b'.repeat(64),'COMPONENT_BAD_CHECKSUM'],
 ['foreign binary',r=>r.assets[0].browser_download_url='https://evil.test/x.exe','UPDATE_UNTRUSTED_URL'],
 ['foreign checksum',r=>r.assets[1].browser_download_url='https://evil.test/SHA2-256SUMS','UPDATE_UNTRUSTED_URL'],
 ['traversal',r=>r.tag_name='../../2026.08.19','COMPONENT_BAD_CATALOG'],
 ['draft',r=>r.draft=true,'COMPONENT_BAD_CATALOG'],
 ['prerelease',r=>r.prerelease=true,'COMPONENT_BAD_CATALOG'],
 ['oversize',r=>r.assets[0].size=2**31,'COMPONENT_BAD_CATALOG'],
 ['missing executable',r=>r.assets.shift(),'COMPONENT_BAD_CATALOG']])test('291 publisher rejects '+label,async()=>{const r=release(),map=routes();change(r);map[api]=JSON.stringify(r);await A.rejects(U.fetchComponent('ytdlp',transport(map)),{code});});
for(const url of ['http://api.github.com/repos/yt-dlp/yt-dlp/releases/latest','https://user:pw@api.github.com/repos/yt-dlp/yt-dlp/releases/latest','https://api.github.com/repos/other/repo/releases/latest','file:///x','https://evil.test/a','https://www.gyan.dev/evil.exe'])test('291 metadata allowlist rejects '+url,()=>A.throws(()=>U.metadataURL(url,'ytdlp')));
test('291 absent app repository does not block either publisher or installation',()=>fixture(async({m})=>{const s=await m.check();A.equal(s.phase,'current');A.equal(s.source,'publishers');A.equal(s.items.filter(x=>x.available).length,2);await m.install('ytdlp');A.equal(m.installed('ytdlp'),true);A.equal(m.index.ytdlp.active,v);}));
test('291 configured app repository keeps independent publisher component updates by default',()=>fixture(async({m})=>{m.config={repository:{owner:'viktorstriuk',name:'PulseDeck'},publicKey:require('node:crypto').generateKeyPairSync('ed25519').publicKey.export({type:'spki',format:'pem'}),releaseAsset:'pulsedeck-update-{channel}.json',componentsAsset:'pulsedeck-components-{channel}.json',componentsMode:'publishers'};const s=await m.check();A.equal(s.phase,'current');A.equal(s.source,'publishers');A.equal(s.items.filter(x=>x.available).length,2);}));
test('291 failure of one publisher leaves another usable',()=>fixture(async({m})=>{const map=routes();delete map['https://www.gyan.dev/ffmpeg/builds/release-version'];m.transport=transport(map);const s=await m.check();A.equal(s.phase,'error');A.equal(s.errors.ffmpeg,'UPDATE_NETWORK_ERROR');A.equal(m.catalog.ytdlp.version,v);await m.install('ytdlp');A.ok(m.resolve('yt-dlp.exe'));}));
test('291 previously checked component remains available after transient metadata error',()=>fixture(async({m})=>{await m.check();m.transport=transport({});const s=await m.check();A.equal(s.phase,'error');A.equal(m.catalog.ytdlp.version,v);}));
test('291 downgrade metadata never replaces a newer local version',()=>fixture(async({m})=>{await m.install('ytdlp',pin('2026.09.20'));await m.check();A.equal(m.state.errors.ytdlp,'COMPONENT_OLD_CATALOG');A.equal(m.catalog.ytdlp,undefined);A.equal(m.index.ytdlp.active,'2026.09.20');}));
test('291 PATH and another installation are ignored; own legacy tool remains compatible',()=>fixture(({install,m})=>{const external=path.join(install,'outside');fs.mkdirSync(external);fs.writeFileSync(path.join(external,'yt-dlp.exe'),exe);const old=process.env.PATH;process.env.PATH=external;try{A.equal(m.resolve('yt-dlp.exe'),'');m.legacy=path.join(os.tmpdir(),'not-this-install');A.equal(m.resolve('yt-dlp.exe'),'');m.legacy=path.join(install,'tools');fs.mkdirSync(m.legacy);fs.writeFileSync(path.join(m.legacy,'yt-dlp.exe'),exe);A.equal(m.resolve('yt-dlp.exe'),path.join(m.legacy,'yt-dlp.exe'));}finally{process.env.PATH=old;}}));
test('291 binary symlink is not used even with MZ bytes at target',()=>fixture(async({install,m})=>{await m.install('ytdlp',pin());const file=m.resolve('yt-dlp.exe'),other=path.join(install,'other.exe');fs.writeFileSync(other,exe);fs.unlinkSync(file);fs.symlinkSync(other,file);A.equal(m.resolve('yt-dlp.exe'),'');}));
test('291 symlink component root is refused before creating cache',()=>fixture(({install})=>{const outside=fs.mkdtempSync(path.join(os.tmpdir(),'pd291-outside-'));try{fs.symlinkSync(outside,path.join(install,'linked'));A.throws(()=>new ComponentManager({root:path.join(install,'linked'),config:{}}),{code:'COMPONENT_UNSAFE_PATH'});A.deepEqual(fs.readdirSync(outside),[]);}finally{fs.rmSync(outside,{recursive:true,force:true});}}));
test('291 missing FFprobe means the FFmpeg component is incomplete',()=>fixture(({m})=>{const dir=path.join(m.root,'ffmpeg','9.0.2');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'ffmpeg.exe'),exe);m.index.ffmpeg={active:'9.0.2'};A.equal(m.installed('ffmpeg'),false);fs.writeFileSync(path.join(dir,'ffprobe.exe'),exe);A.equal(m.installed('ffmpeg'),true);fs.writeFileSync(path.join(dir,'ffprobe.exe'),'not an executable');A.equal(m.installed('ffmpeg'),false);}));
test('291 missing same-version tool is offered and repaired without version conflict',()=>fixture(async({m})=>{await m.install('ytdlp',pin());fs.unlinkSync(m.resolve('yt-dlp.exe'));A.equal(m.installed('ytdlp'),false);await m.check();A.equal(m.catalog.ytdlp.version,v);await m.install('ytdlp');A.equal(m.installed('ytdlp'),true);A.equal(m.index.ytdlp.previous,null);}));
test('291 failed index publish does not switch the in-memory active tool',()=>fixture(async({m})=>{await m.install('ytdlp',pin());const before=m.resolve('yt-dlp.exe');fs.unlinkSync(m.file);fs.mkdirSync(m.file);await A.rejects(m.install('ytdlp',pin('2026.09.20')));A.equal(m.index.ytdlp.active,v);A.equal(m.resolve('yt-dlp.exe'),before);}));
test('291 storage migration changes components only and backs up old mapping',()=>fixture(({install})=>{const root=path.join(install,'application'),env={APPDATA:path.join(install,'roaming'),LOCALAPPDATA:path.join(install,'local')},home=path.join(install,'home');const first=resolveStorage({root,env,home,platform:'win32'}),file=path.join(first.profile,'storage.json'),saved=JSON.parse(fs.readFileSync(file));saved.tools=path.join(install,'old-components');fs.writeFileSync(file,JSON.stringify(saved));const next=resolveStorage({root,env,home,platform:'win32'});A.equal(next.tools,path.join(root,'components'));for(const key of ['music','data','languages'])A.equal(next[key],saved[key]);A.ok(fs.existsSync(path.join(first.profile,'backups','before-components-local-2.9.1.json')));}));
test('291 renderer IPC can check components while app updates remain unconfigured',async()=>{const {harness}=require('./main-harness'),h=harness({requireOverrides:{'./updates/transport':transport(),'./updates/config.json':{schema:1,repository:null,publicKey:'',checkIntervalHours:12,releaseAsset:'pulsedeck-update-{channel}.json',componentsAsset:'pulsedeck-components-{channel}.json',componentsMode:'publishers'}}});try{A.equal((await h.invoke('updates:check')).phase,'unconfigured');const result=await h.invoke('components:check');A.equal(result.phase,'current');A.ok(result.directory.startsWith(h.temp));A.equal(result.source,'publishers');}finally{h.close();}});
test('291 extractor disables default runtime discovery before the bundled Node runtime',async()=>{const {createExtractor}=require('../app/online/extractor');const e=createExtractor({runtimePath:'/app/PulseDeck.exe',resolve:()=>'/app/components/tool.exe',run:async()=>({stdout:'22.16.0'})});const o=await e.environment('https://youtube.com');A.ok(o.args.indexOf('--no-js-runtimes')<o.args.indexOf('--js-runtimes'));A.ok(o.args.includes('node:/app/PulseDeck.exe'));});

test('291 incomplete managed FFmpeg never mixes with a legacy FFprobe',()=>fixture(({m})=>{const dir=path.join(m.root,'ffmpeg','9.0.2');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'ffmpeg.exe'),exe);fs.mkdirSync(m.legacy);for(const n of ['ffmpeg.exe','ffprobe.exe'])fs.writeFileSync(path.join(m.legacy,n),exe);m.index.ffmpeg={active:'9.0.2'};A.equal(m.resolve('ffmpeg.exe'),'');A.equal(m.resolve('ffprobe.exe'),'');A.equal(m.installed('ffmpeg'),false);}));
test('291 legacy FFmpeg is accepted only as a complete local pair',()=>fixture(({m})=>{fs.mkdirSync(m.legacy);fs.writeFileSync(path.join(m.legacy,'ffmpeg.exe'),exe);A.equal(m.resolve('ffmpeg.exe'),'');fs.writeFileSync(path.join(m.legacy,'ffprobe.exe'),exe);A.equal(m.resolve('ffmpeg.exe'),path.join(m.legacy,'ffmpeg.exe'));A.equal(m.resolve('ffprobe.exe'),path.join(m.legacy,'ffprobe.exe'));}));
test('291 malformed managed version cannot silently fall back to legacy',()=>fixture(({m})=>{fs.mkdirSync(m.legacy);fs.writeFileSync(path.join(m.legacy,'yt-dlp.exe'),exe);m.index.ytdlp={active:'../other'};A.equal(m.resolve('yt-dlp.exe'),'');}));
