'use strict';
const test=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Engine,cleanKey,escape,ERROR_MARKER}=require('../app/shared/i18n');
const I18n=require('../app/i18n');
const {CatalogService,loadCatalogs}=I18n;
const {JsonSettingsStore}=require('../app/settings-store');
const {harness}=require('./main-harness');
const ru=require('../app/languages/ru.json'),en=require('../app/languages/en.json');
const engine=(language='ru',catalogs={ru,en})=>new Engine({language,catalogs});
const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'pd-i18n-269-'));
const catalog=(code,messages,extra={})=>({meta:{code,name:code,locale:code,icon:code+'.svg',...extra},messages});
const write=(dir,code,data)=>fs.writeFileSync(path.join(dir,code+'.json'),typeof data==='string'?data:JSON.stringify(data));
function fixture(fn){return async()=>{const dir=temp();try{await fn(dir);}finally{fs.rmSync(dir,{recursive:true,force:true});}};}
const t=(name,fn)=>test('269 i18n '+name,fn);

t('selected translation wins without source-language fallbacks',()=>{
 const e=engine('xx',{xx:catalog('xx',{SettingsButton:'Custom'}),en:catalog('en',{SettingsButton:'English'}),ru:catalog('ru',{SettingsButton:'Русский'})});
 A.equal(e.t('SettingsButton'),'Custom');delete e.catalogs.xx.messages.SettingsButton;A.equal(e.t('SettingsButton'),'English');delete e.catalogs.en.messages.SettingsButton;A.equal(e.t('SettingsButton'),'SettingsButton');
});
t('missing selected catalog uses English and never another installed language',()=>{const e=engine('fr',{en:catalog('en',{OnlyEnglish:'English'}),ru:catalog('ru',{OnlyRussian:'Текст'})});A.equal(e.t('OnlyEnglish'),'English');A.equal(e.t('OnlyRussian'),'OnlyRussian');});
t('missing English or both catalogs is safe',()=>{A.equal(engine('en',{}).t('Button'),'Button');A.equal(engine('ru',{ru:catalog('ru',{Button:'Кнопка'})}).t('Button'),'Кнопка');});
t('last fallback cleans whitespace and quoting, not semantic key spelling',()=>{A.equal(cleanKey(' \t"SettingsButton" '),'SettingsButton');A.equal(engine('en',{}).t("  'SettingsButton'  "),'SettingsButton');});
for(const bad of ['', '  ', null, 42, [], true, {one:''}])t('empty or invalid selected entry falls through '+JSON.stringify(bad),()=>{const e=engine('x',{x:catalog('x',{Key:bad}),en:catalog('en',{Key:'Good'})});A.equal(e.t('Key'),'Good');});
t('interpolation is literal, missing placeholders retained, inherited params ignored',()=>{const e=engine('en',{en:catalog('en',{Key:'{name}: {count}; {missing}'})});const p=Object.create({missing:'BAD'});Object.assign(p,{name:'<img src=x onerror=alert(1)>',count:0});A.equal(e.t('Key',p),'<img src=x onerror=alert(1)>: 0; {missing}');});
t('HTML and attribute arguments are inert',()=>{const e=engine('en',{en:catalog('en',{Key:'<b>{name}</b>'})});A.equal(e.h('Key',{name:'"&\''}),'&lt;b&gt;&quot;&amp;&#39;&lt;/b&gt;');A.equal(escape('<>&"\''),'&lt;&gt;&amp;&quot;&#39;');A.ok(!e.attrArgs({name:'" onclick="BAD'}).includes(' onclick="'));});
t('nested application labels relocalize and interpolation recursion is bounded',()=>{const e=engine(),p={value1:e.msg('LyricsStart'),value2:3};const first=e.t('LyricsOfLine',p);e.setLanguage('en');A.notEqual(e.t('LyricsOfLine',p),first);const cycle=e.msg('Recursive');cycle.params={value:cycle};e.catalogs={en:catalog('en',{Recursive:'{value}'})};A.equal(e.t('Recursive',{value:cycle}),'');});
t('prototype properties are not translations',()=>{const inherited={messages:{Key:'BAD'}};const e=engine('x',Object.create({x:inherited,en:inherited}));A.equal(e.t('Key'),'Key');A.equal(engine('en').t('toString'),'toString');});
t('Russian and English plural forms follow the catalog locale',()=>{const e=engine('ru',{ru:catalog('ru',{K:{one:'one {count}',few:'few {count}',many:'many {count}',other:'other {count}'}}),en:catalog('en',{K:{one:'one {count}',other:'other {count}'}})});for(const [n,f]of [[1,'one'],[2,'few'],[5,'many'],[11,'many'],[21,'one'],[1.5,'other']])A.equal(e.t('K',{count:n}),`${f} ${n}`);e.setLanguage('en');A.equal(e.t('K',{count:2}),'other 2');});
t('missing plural form falls through to English',()=>{const e=engine('ru',{ru:catalog('ru',{K:{one:'один'}}),en:catalog('en',{K:{one:'one',other:'many'}})});A.equal(e.t('K',{count:2}),'many');});
t('numbers use selected locale and invalid locale is safe',()=>{A.equal(engine('ru').number(1.25),'1,25');A.equal(engine('en').number(1.25),'1.25');A.doesNotThrow(()=>engine('bad@locale').number(1));});
t('HTTP503 wire error survives Electron prefix and switches without internal IPC prose',()=>{const e=engine('ru');const wire=e.encodeError(e.error('LyricsServiceUnavailableHttp',{value1:503}));A.ok(wire.startsWith(ERROR_MARKER));e.setLanguage('en');const message=e.errorMessage(Error("Error invoking remote method 'lyrics:command': Error: "+wire));A.equal(message,e.t('LyricsServiceUnavailableHttp',{value1:503}));A.ok(message.includes('503'));A.ok(!message.includes('lyrics:command'));});
t('worker error packet survives serialization and keeps parameters',()=>{const e=engine('ru'),packet=JSON.parse(JSON.stringify(e.errorPacket(e.error('AudioAnalysisEndedEarly',{code:17}))));e.setLanguage('en');const err=e.fromErrorPacket(packet);A.equal(err.i18nKey,'AudioAnalysisEndedEarly');A.equal(err.message,e.t('AudioAnalysisEndedEarly',{code:17}));});
t('external OS/service diagnostics are preserved as details',()=>{const e=engine('en');A.ok(e.errorMessage(Error('EACCES: disk is read-only')).includes('EACCES: disk is read-only'));A.doesNotThrow(()=>e.errorMessage(Error(ERROR_MARKER+'{broken')));});

t('RU and EN have identical key sets and placeholders',()=>{
 A.deepEqual(Object.keys(ru.messages).sort(),Object.keys(en.messages).sort());
 const parameters=value=>[...new Set(Object.values(typeof value==='string'?{text:value}:value).flatMap(v=>[...v.matchAll(/\{([A-Za-z][\w]*)\}/g)].map(m=>m[1])))].sort();
 for(const key of Object.keys(ru.messages)){A.deepEqual(parameters(ru.messages[key]),parameters(en.messages[key]),key);for(const value of [ru.messages[key],en.messages[key]])for(const text of Object.values(typeof value==='string'?{text:value}:value))A.ok(text.trim(),key+' is empty');}
});
t('drop-in JSON is listed by its own name and filename, with safe SVG URL',fixture(dir=>{fs.mkdirSync(path.join(dir,'icons'));fs.writeFileSync(path.join(dir,'icons','new.svg'),'<svg xmlns="http://www.w3.org/2000/svg"/>');write(dir,'new',catalog('new',{K:'New'},{name:'New language',locale:'en',icon:'new.svg'}));const service=new CatalogService(dir,'new');A.equal(service.t('K'),'New');A.equal(service.languages[0].name,'New language');A.ok(service.languages[0].iconUrl.startsWith('file:'));A.ok(service.languages[0].iconUrl.includes('new.svg'));}));
t('BOM, unknown metadata, and optional meta code are supported',fixture(dir=>{write(dir,'fr','\uFEFF'+JSON.stringify({meta:{name:'Français',locale:'fr-FR',extra:'safe'},messages:{K:'Oui'}}));const s=new CatalogService(dir,'fr');A.equal(s.t('K'),'Oui');A.equal(s.locale,'fr-FR');}));
t('malformed JSON, schema and oversized catalog do not prevent other packs loading',fixture(dir=>{write(dir,'en',catalog('en',{K:'Good'}));write(dir,'broken','{');write(dir,'wrong',{meta:{name:'Wrong',code:'other'},messages:{}});write(dir,'array',[]);write(dir,'huge',' '.repeat(2*1024*1024+1));const s=new CatalogService(dir,'broken');A.equal(s.t('K'),'Good');A.equal(s.diagnostics.length,4);A.equal(s.languages.length,1);}));
t('noncatalog files, directories and filename traversal are not languages',fixture(dir=>{write(dir,'en',catalog('en',{K:'Good'}));fs.mkdirSync(path.join(dir,'folder.json'));fs.writeFileSync(path.join(dir,'bad code.json'),'{}');fs.writeFileSync(path.join(dir,'readme.txt'),'text');A.equal(loadCatalogs(dir).languages.length,1);}));
t('dangerous message properties, wrong values and unsafe direction are filtered',fixture(dir=>{write(dir,'x','{"meta":{"name":"<img onerror=BAD>","direction":"<script>"},"messages":{"__proto__":"BAD","constructor":"BAD","A":12,"K":"OK"}}');const s=new CatalogService(dir,'x');A.equal(s.t('__proto__'),'__proto__');A.equal(s.t('constructor'),'constructor');A.equal(s.languages[0].direction,'ltr');A.equal(s.languages[0].name,'<img onerror=BAD>');A.equal(s.t('A'),'A');}));
for(const icon of ['../secret.svg','/tmp/a.svg','https://evil/x.svg','x.svg" onload="BAD','x.png'])t('unsafe icon filename is ignored '+icon,fixture(dir=>{write(dir,'en',catalog('en',{K:'OK'},{icon}));const s=new CatalogService(dir,'en');A.equal(s.languages[0].iconUrl,'');A.equal(s.t('K'),'OK');}));
t('catalog symlinks and SVG file/directory symlinks are ignored',fixture(dir=>{const outside=path.join(dir,'outside');fs.mkdirSync(outside);fs.writeFileSync(path.join(outside,'a.svg'),'<svg/>');fs.symlinkSync(outside,path.join(dir,'icons'));write(dir,'en',catalog('en',{K:'OK'},{icon:'a.svg'}));fs.symlinkSync(path.join(dir,'en.json'),path.join(dir,'fr.json'));A.equal(loadCatalogs(dir).languages.length,1);A.equal(loadCatalogs(dir).languages[0].iconUrl,'');fs.unlinkSync(path.join(dir,'icons'));fs.mkdirSync(path.join(dir,'icons'));fs.symlinkSync(path.join(outside,'a.svg'),path.join(dir,'icons','a.svg'));A.equal(loadCatalogs(dir).languages[0].iconUrl,'');}));
t('reload supports new packs, edits and removal without changing selected preference',fixture(dir=>{write(dir,'en',catalog('en',{K:'EN'}));const s=new CatalogService(dir,'zz');write(dir,'zz',catalog('zz',{K:'One'}));s.reload();A.equal(s.t('K'),'One');write(dir,'zz',catalog('zz',{K:'Two'}));s.reload();A.equal(s.t('K'),'Two');fs.unlinkSync(path.join(dir,'zz.json'));s.reload();A.equal(s.language,'zz');A.equal(s.t('K'),'EN');}));
t('watcher discovers a new language without restart',fixture(async dir=>{write(dir,'en',catalog('en',{K:'EN'}));fs.mkdirSync(path.join(dir,'icons'));const s=new CatalogService(dir,'en');let changes=0;s.watch(()=>changes++);try{write(dir,'fr',catalog('fr',{K:'FR'}));for(let i=0;i<30&&!changes;i++)await new Promise(r=>setTimeout(r,50));A.ok(changes);A.ok(s.languages.some(l=>l.code==='fr'));}finally{s.close();}}));
t('settings save failure preserves cached and persisted prior language',fixture(dir=>{const s=new JsonSettingsStore({file:path.join(dir,'settings.json')});s.set({language:'ru',userText:'SettingsButton'});const persist=s.persist;s.persist=()=>{throw Error('DISK_FULL');};A.throws(()=>s.set({language:'en'}),/DISK_FULL/);A.equal(s.get().language,'ru');s.persist=persist;A.equal(new JsonSettingsStore({file:s.file}).get().language,'ru');}));
t('main IPC persists language and broadcasts to both windows',async()=>{const h=harness();try{const snap=await h.invoke('i18n:set-language','en');A.equal(snap.language,'en');A.equal(h.api.getSettings().language,'en');for(const w of [h.main,h.overlay])A.ok(w.messages.some(m=>m.name==='i18n:changed'&&m.value.language==='en'));A.ok((await h.invoke('i18n:reload')).languages.some(l=>l.code==='ru'));}finally{h.close();I18n.setLanguage('ru');}});
t('main IPC rejects unknown languages and untrusted senders without changing preference',async()=>{const h=harness();try{A.throws(()=>h.rawHandlers.get('i18n:set-language')({sender:h.main.webContents},'../ru'));A.throws(()=>h.rawHandlers.get('i18n:set-language')({sender:h.overlay.webContents},'en'));A.throws(()=>h.rawHandlers.get('i18n:reload')({sender:{}}));A.equal(h.api.getSettings().language,'ru');const e={sender:{}};h.ipc.emit('i18n:bootstrap',e);A.equal(JSON.stringify(e.returnValue),'{}');}finally{h.close();I18n.setLanguage('ru');}});
t('main error wire contains stable key instead of translated remote-method prose',()=>{const h=harness();try{A.throws(()=>h.rawHandlers.get('i18n:set-language')({sender:h.main.webContents},'missing'),e=>e.message.startsWith(ERROR_MARKER)&&JSON.parse(e.message.slice(ERROR_MARKER.length)).key==='InvalidLanguage');}finally{h.close();I18n.setLanguage('ru');}});
t('legacy default overlay label migrates, user label is preserved',()=>{const h=harness();try{const old=h.api.normalizeSettings({playerOverlay:{label:ru.messages.PlayerDefaultLabel}});A.equal(old.playerOverlay.label,'');const user=h.api.normalizeSettings({i18nSchema:1,playerOverlay:{label:ru.messages.PlayerDefaultLabel}});A.equal(user.playerOverlay.label,ru.messages.PlayerDefaultLabel);}finally{h.close();}});
t('missing artist identity is locale-independent while its presentation changes',()=>{const L=require('../app/shared/library-model');const tracks=[{rel:'a.mp3',title:'SettingsButton',artist:''}];I18n.setLanguage('ru');const a=L.categories(tracks,{});I18n.setLanguage('en');const b=L.categories(tracks,{});A.deepEqual(a.map(x=>x.key),b.map(x=>x.key));A.equal(L.trackTitle(tracks[0]),'SettingsButton');A.equal(tracks[0].artist,'');I18n.setLanguage('ru');});
t('system-generated lyric notes are localized without rewriting user notes',()=>{const L=require('../app/shared/lyrics');const d={notes:['Моя заметка'],systemNotes:['AcousticDraftNote']};I18n.setLanguage('ru');const r=L.notes(d);I18n.setLanguage('en');const e=L.notes(d);A.equal(r[0],'Моя заметка');A.equal(e[0],'Моя заметка');A.notEqual(r[1],e[1]);A.deepEqual(d.notes,['Моя заметка']);I18n.setLanguage('ru');});
