'use strict';
const test=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),fsp=fs.promises,path=require('node:path'),os=require('node:os'),zlib=require('node:zlib'),crypto=require('node:crypto'),vm=require('node:vm');
const F=require('../app/shared/track-enrichment'),Ar=require('../app/library/archives'),{Importer}=require('../app/library/importer'),{TrackEditor}=require('../app/library/editor'),{bestLyrics,bestCover,Enrichment}=require('../app/library/enrichment'),{sanitizeImage}=require('../app/library/images'),{createCovers,imageURL,artworkKey}=require('../app/online/covers'),{createLyricsHTTP}=require('../app/lyrics/http');
const {harness,trackFile}=require('./main-harness');
const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'pd292-'));
const rm=p=>fs.rmSync(p,{recursive:true,force:true});
const key=k=>e=>e.i18nKey===k;
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a35sAAAAASUVORK5CYII=','base64');
function zip(entries){let offset=0;const data=[],central=[];for(const x of entries){const name=Buffer.from(x.name),raw=Buffer.from(x.data||''),packed=x.method===0?raw:zlib.deflateRawSync(raw),method=x.method===0?0:8,flags=x.flags||0x800,crc=Ar.crc32(raw);const h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(flags,6);h.writeUInt16LE(method,8);h.writeUInt32LE(crc,14);h.writeUInt32LE(packed.length,18);h.writeUInt32LE(raw.length,22);h.writeUInt16LE(name.length,26);data.push(h,name,packed);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,6);c.writeUInt16LE(flags,8);c.writeUInt16LE(method,10);c.writeUInt32LE(crc,16);c.writeUInt32LE(packed.length,20);c.writeUInt32LE(x.declaredSize??raw.length,24);c.writeUInt16LE(name.length,28);c.writeUInt32LE(x.attr||0,38);c.writeUInt32LE(offset,42);central.push(c,name);offset+=h.length+name.length+packed.length;}
 const d=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(d.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...data,d,end]);}
function tar(entries){const out=[];for(const x of entries){const b=Buffer.from(x.data||''),h=Buffer.alloc(512);h.write(x.name);h.write('0000644\0',100);h.write(b.length.toString(8).padStart(11,'0')+'\0',124);h.fill(32,148,156);h[156]=(x.type||'0').charCodeAt(0);h.write('ustar\0',257);const sum=h.reduce((a,b)=>a+b,0);h.write(sum.toString(8).padStart(6,'0')+'\0 ',148);out.push(h,b,Buffer.alloc((512-b.length%512)%512));}return Buffer.concat([...out,Buffer.alloc(1024)]);}
for(const [name,want] of [['Маяк - Тихий свет',{artist:'Маяк',title:'Тихий свет'}],['A-ha — Take On Me',{artist:'A-ha',title:'Take On Me'}],['Artist – Track — Live',{artist:'Artist',title:'Track — Live'}],['01 - Track',null],['Track without separator',null],['AC-DC - Thunderstruck',{artist:'AC-DC',title:'Thunderstruck'}],['Artist-Track',null]])test('292 conservative filename split: '+name,()=>A.deepEqual(F.splitName({artist:'Неизвестный исполнитель',title:name}),want));
for(const value of ['',null,'Unknown Artist','неизвестно','Неизвестный исполнитель','N/A'])test('292 unknown artist placeholder '+value,()=>A.equal(F.unknown(value),true));
for(const value of ['Unknown Mortal Orchestra','Various Artists','Неизвестный Артист и друзья','Unknown T'])test('292 real artist is retained: '+value,()=>A.equal(F.unknown(value),false));
test('292 never split a known artist and retain internal dashes',()=>A.equal(F.splitName({artist:'Known',title:'Another — Track'}),null));
test('292 editable field bounds, type safety and selective patch',()=>{A.deepEqual(F.validatePatch({title:'  Тихий   свет ',sourceUrl:'https://bad'}),{title:'Тихий свет'});for(const p of [{title:''},{artist:'x'.repeat(161)},{title:42},{filename:'evil'},[]])A.throws(()=>F.validatePatch(p));});
test('292 synced verses include segmented lyric lines and respect suppression',()=>{A.ok(F.hasSynced({lines:[{startMs:0,segments:[{text:'Hi'}]}]}));A.equal(F.hasSynced({lines:[{text:'Hi'}]}),false);A.deepEqual(F.needs({title:'A — B',artist:''},{suppressed:true}),{artists:true,covers:true,lyrics:false});A.deepEqual(F.actions({artists:0,covers:3,lyrics:1}),['covers','lyrics']);});
for(const name of ['../a.mp3','a/../../b.mp3','C:\\foo.mp3','/abs.mp3','a//b.mp3','a/./b.mp3','CON.mp3','aux/a.mp3','a. /b.mp3','a\0.mp3'])test('292 reject unsafe archive path '+JSON.stringify(name),()=>A.throws(()=>Ar.safeName(name),key('ImportUnsafeArchive')));
test('292 safely normalize common TAR ./ prefix and keep Cyrillic',()=>A.equal(Ar.safeName('././Музыка/Трек.mp3'),'Музыка/Трек.mp3'));
test('292 ZIP streams deflate/stored audio, sidecars, and ignores scripts',async()=>{const d=temp();try{const z=path.join(d,'a.zip'),out=path.join(d,'out');fs.mkdirSync(out);fs.writeFileSync(z,zip([{name:'Album/One.mp3',data:'audio'}, {name:'Album/Two.wav',data:'wave',method:0},{name:'Album/One.lrc',data:'[00:01.00]line'},{name:'Album/cover.jpg',data:'jpg'},{name:'run.exe',data:'MZ'}]));const files=await Ar.extract(z,out);A.equal(files.length,4);A.equal(fs.readFileSync(path.join(out,'Album/One.mp3'),'utf8'),'audio');A.ok(!fs.existsSync(path.join(out,'run.exe')));}finally{rm(d);}});
for(const [label,entries,expected]of [['traversal',[{name:'../bad.mp3'}],'ImportUnsafeArchive'],['case duplicate',[{name:'A.mp3'},{name:'a.mp3'}],'ImportUnsafeArchive'],['symlink',[{name:'link.mp3',attr:0xa0000000}],'ImportUnsafeArchive'],['encrypted',[{name:'a.mp3',flags:1}],'ImportEncryptedArchive'],['claimed bomb',[{name:'a.mp3',data:'small',declaredSize:0xfffffffe}],'ImportArchiveLimit']])test('292 archive rejects '+label,async()=>{const d=temp();try{const z=path.join(d,'x.zip');fs.writeFileSync(z,zip(entries));await A.rejects(Ar.extract(z,path.join(d,'out')),key(expected));A.ok(!fs.existsSync(path.join(d,'bad.mp3')));}finally{rm(d);}});
test('292 ZIP checks CRC and real inflated length',async()=>{const d=temp();try{const z=path.join(d,'x.zip'),data=zip([{name:'a.mp3',data:'hello',method:0}]);data[35]^=1;fs.writeFileSync(z,data);await A.rejects(Ar.extract(z,path.join(d,'out')));}finally{rm(d);}});
for(const gzip of [false,true])test('292 TAR root entry, UTF-8 directories and '+(gzip?'gzip checksum':'padding'),async()=>{const d=temp();try{const f=path.join(d,gzip?'x.tgz':'x.tar'),out=path.join(d,'out'),data=tar([{name:'./',type:'5'},{name:'./Музыка/',type:'5'},{name:'./Музыка/Трек.mp3',data:'audio'}]);fs.writeFileSync(f,gzip?zlib.gzipSync(data):data);await Ar.extract(f,out);A.equal(fs.readFileSync(path.join(out,'Музыка/Трек.mp3'),'utf8'),'audio');if(gzip){rm(out);const b=fs.readFileSync(f);b[b.length-8]^=1;fs.writeFileSync(f,b);await A.rejects(Ar.extract(f,out));}}finally{rm(d);}});
test('292 TAR rejects symlinks and truncated headers',async()=>{const d=temp();try{const f=path.join(d,'x.tar');fs.writeFileSync(f,tar([{name:'x.mp3',type:'2'}]));await A.rejects(Ar.extract(f,path.join(d,'out')),key('ImportUnsafeArchive'));fs.writeFileSync(f,tar([{name:'x.mp3',data:'123'}]).subarray(0,520));await A.rejects(Ar.extract(f,path.join(d,'out2')));}finally{rm(d);}});
test('292 already-aborted extraction never publishes audio',async()=>{const d=temp();try{const f=path.join(d,'x.zip');fs.writeFileSync(f,zip([{name:'a.mp3',data:'hello'}]));const c=new AbortController();c.abort();await A.rejects(Ar.extract(f,path.join(d,'out'),{signal:c.signal}));A.ok(!fs.existsSync(path.join(d,'out/a.mp3')));}finally{rm(d);}});
function importer(d){const music=path.join(d,'music');fs.mkdirSync(music);const progress=[],m=new Importer({music,staging:path.join(d,'staging'),notify(){},progress:p=>progress.push(p),storeCover:async f=>f,publish:async(f,meta)=>{let name=path.basename(f),dest=path.join(music,name),i=0;while(fs.existsSync(dest))dest=path.join(music,(++i)+'-'+name);await fsp.copyFile(f,dest,fs.constants.COPYFILE_EXCL);await fsp.writeFile(dest+'.pulse.json',JSON.stringify(meta));return dest;}});return {m,music,progress};}
test('292 folder preflight counts real media, preserves originals and imports lyrics',async()=>{const d=temp();let m;try{const env=importer(d);m=env.m;const src=path.join(d,'source');fs.mkdirSync(src);const f=path.join(src,'Artist — Song.wav');fs.writeFileSync(f,'audio bytes');fs.writeFileSync(f+'.pulse.json',JSON.stringify({artist:'Unknown Artist',title:'Artist — Song',duration:123}));fs.writeFileSync(path.join(src,'Artist — Song.lrc'),'[00:00.00]First\n[00:05.00]Next');fs.writeFileSync(path.join(src,'unrelated.exe'),'not media');const plan=await m.prepare([src,f]);A.equal(plan.count,1);A.deepEqual(plan.counts,{artists:1,covers:1,lyrics:0});A.equal(fs.readdirSync(env.music).length,0);const result=await m.commit(plan.token);A.equal(result.added,1);A.equal(fs.readFileSync(f,'utf8'),'audio bytes');A.ok(fs.existsSync(path.join(env.music,result.rels[0])+'.lyrics.json'));A.equal(m.plans.size,0);A.equal(fs.readdirSync(path.join(d,'staging')).length,0);}finally{await m?.dispose();rm(d);}});
test('292 archive preflight skips unsupported RAR with a visible warning',async()=>{const d=temp();let m;try{({m}=importer(d));const f=path.join(d,'music.rar');fs.writeFileSync(f,'RAR');const p=await m.prepare([f]);A.equal(p.count,0);A.equal(p.warnings[0].code,'ImportArchiveUnsupported');}finally{await m?.dispose();rm(d);}});
test('292 changed source after confirmation is not copied and other tracks continue',async()=>{const d=temp();let m;try{const env=importer(d);m=env.m;const a=path.join(d,'one.wav'),b=path.join(d,'two.wav');fs.writeFileSync(a,'a');fs.writeFileSync(b,'b');const p=await m.prepare([a,b]);fs.appendFileSync(a,'modified');const r=await m.commit(p.token);A.equal(r.added,1);A.equal(r.failed,1);A.equal(r.errors[0].code,'ImportSourceChanged');A.ok(!fs.existsSync(path.join(env.music,'one.wav')));}finally{await m?.dispose();rm(d);}});
test('292 cancelling a copy keeps already copied files and never deletes sources',async()=>{const d=temp();let m;try{const env=importer(d);m=env.m;const paths=['one.wav','two.wav','three.wav'].map(n=>path.join(d,n));for(const f of paths)fs.writeFileSync(f,'audio');const p=await m.prepare(paths),c=new AbortController();const r=await m.commit(p.token,{signal:c.signal,onProgress:()=>c.abort()});A.equal(r.added,1);A.equal(r.cancelled,true);A.ok(paths.every(f=>fs.existsSync(f)));A.equal(m.plans.size,0);}finally{await m?.dispose();rm(d);}});
test('292 imported malicious absolute artwork outside the source folder is ignored',async()=>{const d=temp();let m;try{({m}=importer(d));const src=path.join(d,'source');fs.mkdirSync(src);const f=path.join(src,'one.wav'),cover=path.join(d,'secret.png');fs.writeFileSync(f,'audio');fs.writeFileSync(cover,png);fs.writeFileSync(f+'.pulse.json',JSON.stringify({coverPath:cover}));const p=await m.prepare([f]);A.equal(p.counts.covers,1);A.equal(m.plans.get(p.token).tracks[0].cover,'');}finally{await m?.dispose();rm(d);}});
test('292 existing library files and dropped symlinks are not recopied',async()=>{const d=temp();let m;try{const env=importer(d);m=env.m;const f=path.join(env.music,'one.wav');fs.writeFileSync(f,'audio');const link=path.join(d,'alias.wav');fs.symlinkSync(f,link);const p=await m.prepare([f,link]);A.equal(p.count,0);A.equal(p.skipped,1);A.equal(p.warnings[0].code,'ImportSkippedLink');}finally{await m?.dispose();rm(d);}});
test('292 public edit writes sidecar, retains ID/hash/favorite and survives rescanning',async()=>{const h=harness();try{const f=trackFile(h,'Artist — Song.wav','Unknown Artist',{title:'Artist — Song'});h.api.saveSettings({favorites:['artist — song.wav']},{skipEffects:true});const before=(await h.api.scanLibrary(true))[0],hash=crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');const info=await h.invoke('library:command',{type:'metadata',rel:before.rel});const result=await h.invoke('library:command',{type:'edit',rel:before.rel,revision:info.revision,patch:{title:'Song',artist:'Artist'}});const after=(await h.api.scanLibrary())[0];A.equal(after.title,'Song');A.equal(after.artist,'Artist');A.equal(after.id,before.id);A.equal(after.addedAt,before.addedAt);A.equal(after.favorite,true);A.equal(after.editRevision,result.revision);A.equal(hash,crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'));A.equal(JSON.parse(fs.readFileSync(f+'.pulse.json'))._pulsePrevious.title,'Artist — Song');await A.rejects(h.invoke('library:command',{type:'edit',rel:before.rel,revision:info.revision,patch:{title:'Overwrite'}}),key('TrackChanged'));}finally{h.close();}});
test('292 private rename stays encrypted and audio capability remains valid',async()=>{const h=harness();try{trackFile(h,'secret.wav','Unknown Artist',{title:'Artist - Secret'});h.api.saveSettings({customCategories:[{id:'custom:a',name:'Private',tracks:['secret.wav']}]},{skipEffects:true});await h.api.vaultCommand({type:'protect',key:'custom:a',name:'Private',password:'strong test password'});const v=await h.api.vaultCommand({type:'unlock',key:'custom:a',password:'strong test password'}),t=v.tracks[0];const info=await h.invoke('library:command',{type:'metadata',rel:t.rel});await h.invoke('library:command',{type:'edit',rel:t.rel,patch:{artist:'Private renamed artist'},revision:info.revision});const next=await h.api.vaultCommand({type:'enter',key:'custom:a'});A.equal(next.tracks[0].artist,'Private renamed artist');A.equal(next.tracks[0].audioUrl,t.audioUrl);A.equal((await fetch(t.audioUrl)).status,200);const vault=h.api.getVault(),file=vault.file(vault.descriptor('custom:a'),'playlist.pdv');A.equal(fs.readFileSync(file,'utf8').includes('Private renamed artist'),false);await h.api.vaultCommand({type:'lock'});await A.rejects(h.invoke('library:command',{type:'metadata',rel:t.rel}));}finally{h.close();}});
test('292 artwork validation rejects active content and oversized raster headers',()=>{const fake={createFromBuffer:()=>({isEmpty:()=>false,getSize:()=>({width:1,height:1}),toPNG:()=>png})};A.deepEqual(sanitizeImage(png,fake),png);for(const b of [Buffer.from('<svg onload="x"/>'),Buffer.alloc(17*1024*1024),Buffer.from('GIF89a')])A.throws(()=>sanitizeImage(b,fake),key('CoverInvalidImage'));const large=Buffer.from(png);large.writeUInt32BE(10000,16);large.writeUInt32BE(10000,20);A.throws(()=>sanitizeImage(large,fake),key('CoverInvalidImage'));});
test('292 artwork host policy and normalized thumbnails are conservative',()=>{for(const u of ['http://i.ytimg.com/a','https://127.0.0.1/a','https://ytimg.com.evil.example/a','https://i.ytimg.com:444/a','https://user:pass@i.ytimg.com/a'])A.equal(imageURL(u),'');A.ok(imageURL('https://i.ytimg.com/vi/abc/hqdefault.jpg'));A.equal(artworkKey('https://i.ytimg.com/vi/abc/hqdefault.jpg'),artworkKey('https://i.ytimg.com/vi/abc/maxresdefault.jpg'));});
test('292 cover music results use selected providers, dedupe and opaque expiring download IDs',async()=>{let now=100;const calls=[],service=createCovers({clock:()=>now,search:{command:async c=>{calls.push(c);return {ok:true,items:[{url:'https://www.youtube.com/watch?v=abcdefghijk',title:'Song',artist:'Artist',thumbnail:'https://i.ytimg.com/vi/abcdefghijk/hqdefault.jpg',provider:c.provider}]};},cancel(){}},fetch:async()=>new Response(png)});try{const r=await service.find({query:'Artist Song',prefs:{enabled:['youtube','ytmusic']},requestId:'cover'});A.equal(r.items.length,1);A.equal(calls.length,2);A.match(r.items[0].id,/^[a-f0-9]{32}$/);A.deepEqual(await service.download(r.items[0].id),png);await A.rejects(service.download('https://127.0.0.1/'),key('CoverExpired'));now+=31*60000;await A.rejects(service.download(r.items[0].id),key('CoverExpired'));}finally{service.dispose();}});
test('292 Cover Art Archive follows its documented archive.org JSON redirect safely',async()=>{const calls=[],release='12345678-1234-1234-1234-123456789012',service=createCovers({search:{cancel(){}},fetch:async url=>{calls.push(url);if(url.includes('/ws/2/'))return Response.json({releases:[{id:release,title:'Album','artist-credit':[{name:'Artist'}]}]});if(url===`https://coverartarchive.org/release/${release}`)return new Response(null,{status:307,headers:{Location:'http://archive.org/download/mbid-'+release+'/index.json'}});return Response.json({images:[{front:true,thumbnails:{500:`http://coverartarchive.org/release/${release}/1-500.jpg`}}]});}});try{const r=await service.find({query:'Artist Album',phase:'catalog'});A.equal(r.items.length,1);A.ok(r.items[0].image.startsWith('https://'));A.ok(calls.some(x=>x.startsWith('https://archive.org/')));}finally{service.dispose();}});
test('292 cover redirects cannot fetch a private IP and bounded responses are rejected',async()=>{const s=createCovers({search:{cancel(){}},fetch:async()=>new Response(null,{status:302,headers:{Location:'http://127.0.0.1/private'}})});try{await A.rejects(s.request('https://i.ytimg.com/a'));}finally{s.dispose();}const big=createCovers({search:{cancel(){}},fetch:async()=>new Response('x',{headers:{'content-length':String(20*1024*1024)}})});try{await A.rejects(big.request('https://i.ytimg.com/a'));}finally{big.dispose();}});
test('292 lyric matching requires known identity, synced text and close duration',()=>{const t={artist:'Artist',title:'Song',duration:180},x={artist:'Artist',title:'Song',synced:'[00:00.00]Hello',duration:180,delta:0,matchScore:100};A.equal(bestLyrics([x],t),x);for(const bad of [{delta:20},{delta:null},{artist:'Other'},{title:'Other'},{synced:''},{instrumental:true},{variantMismatch:true},{matchScore:80}])A.equal(bestLyrics([{...x,...bad}],t),null);A.equal(bestLyrics([x],{...t,duration:0}),null);A.equal(bestLyrics([x],{...t,artist:'Unknown Artist'}),null);});
test('292 artwork auto-fill rejects wrong artist but accepts a matching album',()=>{const t={artist:'Artist',title:'Song',album:'Album'};A.equal(bestCover([{artist:'Other',title:'Song'}],t),null);const good={artist:'Artist',title:'Album'};A.equal(bestCover([good],t),good);});
test('292 LRCLIB Chromium transport enforces origin, response size and no cookies',async()=>{let opts;const request=createLyricsHTTP(async(u,o)=>{opts=o;return Response.json([{id:1}]);});A.deepEqual(await request('https://lrclib.net/api/search?q=test'),[{id:1}]);A.equal(opts.credentials,'omit');A.equal(opts.redirect,'error');for(const url of ['http://lrclib.net/api/search','https://evil.test/api/search','https://lrclib.net:444/api/search'])await A.rejects(request(url));const large=createLyricsHTTP(async()=>new Response('{}',{headers:{'content-length':String(3*1024*1024)}}));await A.rejects(large('https://lrclib.net/api/search'),key('LyricsServiceResponseIsTooLarge'));});
test('292 LRCLIB errors are not mistaken for no lyrics',async()=>{for(const [status,want]of [[429,'LyricsLRCLIBHasRequestedADelayTrySearchingAgain'],[503,'LyricsServiceUnavailableHttp']]){const request=createLyricsHTTP(async()=>new Response('',{status}));await A.rejects(request('https://lrclib.net/api/search'),key(want));}});
test('292 bridge only obtains disk paths through Electron webUtils for File drops',async()=>{let api,calls=[];const file={tag:'real'},context=vm.createContext({console,require:name=>{A.equal(name,'electron');return {contextBridge:{exposeInMainWorld:(n,o)=>{api=o;}},ipcRenderer:{invoke:async(...a)=>{calls.push(a);return {};},on(){},removeListener(){},sendSync(){},send(){}},webUtils:{getPathForFile:f=>f===file?'C:\\Music\\song.wav':''}};}});vm.runInContext(fs.readFileSync(path.join(__dirname,'../app/preload.js'),'utf8'),context);await api.library.prepareDrop([file,{}],'req');A.equal(calls[0][0],'library:prepare-drop');A.deepEqual(Array.from(calls[0][1]),['C:\\Music\\song.wav']);A.equal(calls[0][2],'req');});
test('292 main rejects arbitrary import paths through the generic command channel',async()=>{const h=harness();try{await A.rejects(h.invoke('library:command',{type:'import-prepare',paths:[h.temp]}),key('TrackBadEdit'));await A.rejects(async()=>h.handlers.get('library:prepare-drop')({sender:{}},[h.temp],'r'));}finally{h.close();}});

// End-to-end queue semantics with injected storage/network responses. The queue,
// matching, cancellation and write guards are the real implementation.
function queueFixture(tracks,overrides={}){
 const events=[],edits=[],saves=[],queries=[],lookup=new Map(tracks.map(t=>[t.rel,{...t}])),docs=new Map(),revisions=new Map();
 const lyrics={get:async rel=>({doc:docs.get(rel)||null,revision:revisions.get(rel)||null}),search:async c=>{queries.push(c);return [];},save:async c=>{saves.push(c);docs.set(c.rel,c.doc);revisions.set(c.rel,'saved');}};
 const editor={resolve:async rel=>{if(!lookup.has(rel))throw Error('Missing');return {track:{...lookup.get(rel)},revision:lookup.get(rel).revision||null};},update:async(rel,patch,opts)=>{const t=lookup.get(rel);if(opts.revision!==(t.revision||null))throw Object.assign(Error('changed'),{i18nKey:'TrackChanged'});edits.push({rel,patch,opts});Object.assign(t,patch);if(opts.coverBuffer)t.coverUrl='file://saved.png';t.revision=String(edits.length);return {ok:true};}};
 const coverCalls=[],covers={find:async c=>{coverCalls.push(c);return {ok:true,items:[]};},download:async()=>png,cancel(){}};
 const q=new Enrichment({editor,lyrics:()=>lyrics,vault:()=>({exclusive:fn=>fn()}),covers,importer:{commit:async()=>({rels:[...lookup.keys()],added:lookup.size,failed:0,errors:[]})},sanitize:x=>x,preferences:()=>({}),progress:p=>events.push(p),notify(){},...overrides});
 return {q,events,edits,saves,queries,lookup,docs,revisions,lyrics,editor,covers,coverCalls};
}
async function runQueue(f,command){f.q.start({rels:[...f.lookup.keys()],...command});await f.q.active.promise;return f.events.at(-1);}
const demoTrack=(rel='one.wav')=>({rel,title:'Song',artist:'Artist',duration:180,coverUrl:''});
const lyricCandidate=(overrides={})=>({artist:'Artist',title:'Song',synced:'[00:00.00]Hello\n[00:05.00]World',duration:180,delta:0,matchScore:100,...overrides});
test('292 batch rejects online actions without consent, but artist-only processing is local',async()=>{const f=queueFixture([{...demoTrack(),artist:'Unknown Artist',title:'Artist — Song'},demoTrack('two.wav')]);try{A.throws(()=>f.q.start({rels:['one.wav'],actions:['covers']}),key('EnrichConsent'));const r=await runQueue(f,{actions:['artists'],consent:false});A.equal(f.edits.length,1);A.deepEqual(f.edits[0].patch,{artist:'Artist',title:'Song'});A.equal(f.lookup.get('two.wav').artist,'Artist');A.equal(f.coverCalls.length,0);A.equal(f.queries.length,0);A.equal(r.changed,1);A.equal(r.skipped,1);}finally{f.q.dispose();}});
test('292 batch searches covers using newly inferred artist and preserves existing cover',async()=>{const f=queueFixture([{...demoTrack(),artist:'Unknown Artist',title:'Artist - Song'},{...demoTrack('two.wav'),coverUrl:'file://mine.png'}]);f.covers.find=async c=>{f.coverCalls.push(c);return {ok:true,items:[{id:'good',artist:'Artist',title:'Song'}]};};try{const r=await runQueue(f,{actions:['artists','covers'],consent:true});A.equal(f.coverCalls.length,1);A.equal(f.coverCalls[0].query,'Artist Song');A.equal(f.lookup.get('two.wav').coverUrl,'file://mine.png');A.equal(r.changed,2);A.equal(r.skipped,2);}finally{f.q.dispose();}});
test('292 lyrics queue skips no match and continues to a valid synchronized result',async()=>{const f=queueFixture([demoTrack(),demoTrack('two.wav')]);f.lyrics.search=async c=>{f.queries.push(c);return c.rel==='two.wav'?[lyricCandidate()]:[];};try{const r=await runQueue(f,{actions:['lyrics'],consent:true});A.equal(f.queries.length,2);A.equal(f.queries[0].background,true);A.ok(f.queries[0].signal instanceof AbortSignal);A.equal(f.saves.length,1);A.equal(f.saves[0].rel,'two.wav');A.equal(f.events.find(p=>p.title&&p.status==='skipped').reason,'EnrichNoMatch');A.equal(r.changed,1);A.equal(r.skipped,1);}finally{f.q.dispose();}});
test('292 manual text, synchronized lyrics and suppressed lyrics are never overwritten',async()=>{const f=queueFixture([demoTrack(),demoTrack('two.wav'),demoTrack('three.wav')]);f.docs.set('one.wav',{lines:[{text:'My own different lyrics'}]});f.docs.set('two.wav',{lines:[{startMs:0,text:'Already synced'}]});const get=f.lyrics.get;f.lyrics.get=async rel=>({...await get(rel),suppressed:rel==='three.wav'});f.lyrics.search=async()=>[lyricCandidate()];try{const r=await runQueue(f,{actions:['lyrics'],consent:true});A.equal(f.saves.length,0);A.equal(r.skipped,3);A.ok(f.events.some(p=>p.reason==='EnrichPreservedText'));}finally{f.q.dispose();}});
test('292 a concurrent lyric edit or a newly suppressed lyric cancels just that write',async()=>{for(const mode of ['revision','suppress']){const f=queueFixture([demoTrack()]);let changed=false;const get=f.lyrics.get;f.lyrics.get=async rel=>({...await get(rel),suppressed:mode==='suppress'&&changed});f.lyrics.search=async()=>{changed=true;if(mode==='revision')f.revisions.set('one.wav','user-edit');return [lyricCandidate()];};try{await runQueue(f,{actions:['lyrics'],consent:true});A.equal(f.saves.length,0);}finally{f.q.dispose();}}});
test('292 failures on one track do not stop later tracks or become false no-match',async()=>{const f=queueFixture([demoTrack(),demoTrack('two.wav')]);f.lyrics.search=async c=>{if(c.rel==='one.wav')throw Object.assign(Error('network'),{i18nKey:'LyricsServiceUnavailableHttp'});return [lyricCandidate()];};try{const r=await runQueue(f,{actions:['lyrics'],consent:true});A.equal(r.failed,1);A.equal(r.changed,1);A.ok(f.events.some(p=>p.status==='failed'&&p.reason==='LyricsServiceUnavailableHttp'));}finally{f.q.dispose();}});
test('292 explicit cancellation stops pending actions without undoing completed edits',async()=>{const f=queueFixture([{...demoTrack(),artist:'Unknown Artist',title:'Artist - Song'},{...demoTrack('two.wav'),artist:'Unknown Artist',title:'Artist - Next'}]);f.q.progress=p=>{f.events.push(p);if(p.status==='changed')f.q.cancel(p.id);};try{const r=await runQueue(f,{actions:['artists'],consent:false});A.equal(r.cancelled,true);A.equal(f.edits.length,1);A.equal(f.lookup.get('two.wav').artist,'Unknown Artist');}finally{f.q.dispose();}});
test('292 import is committed once before enrichment and a copy-only job needs no network',async()=>{const f=queueFixture([demoTrack()]);let committed=0;f.q.importer.commit=async(token,{onProgress})=>{A.equal(token,'plan');committed++;onProgress({phase:'copy',done:1,total:1,added:1});return {rels:['one.wav'],added:1,failed:0,errors:[]};};try{const r=await runQueue(f,{token:'plan',actions:[],consent:false});A.equal(committed,1);A.equal(r.added,1);A.equal(r.total,0);A.equal(f.edits.length+f.saves.length+f.queries.length+f.coverCalls.length,0);A.equal(f.q.active,null);}finally{f.q.dispose();}});
test('292 one capability scan excludes synced and intentionally suppressed lyrics',async()=>{const f=queueFixture([{...demoTrack(),title:'Artist - Song',artist:'Unknown Artist'},{...demoTrack('two.wav'),coverUrl:'file://cover'}]);f.docs.set('two.wav',{lines:[{startMs:0,text:'Sync'}]});try{const c=await f.q.capabilities(['one.wav','two.wav','one.wav']);A.deepEqual(c.counts,{artists:1,covers:1,lyrics:1});A.equal(c.total,2);f.docs.set('one.wav',{lines:[{startMs:0,text:'Now synced'}]});f.q.invalidate('one.wav');A.equal((await f.q.capabilities(['one.wav'])).counts.lyrics,0);}finally{f.q.dispose();}});
test('292 editor snapshot scans membership once but rereads each changed track',async()=>{const d=temp();try{const music=path.join(d,'music'),covers=path.join(d,'covers');fs.mkdirSync(music);fs.mkdirSync(covers);const file=path.join(music,'a.wav');fs.writeFileSync(file,'audio');fs.writeFileSync(file+'.pulse.json',JSON.stringify({title:'Artist - Song',artist:'Unknown Artist'}));let scans=0;const editor=new TrackEditor({music,covers,list:async()=>{scans++;return [{id:'a'.repeat(16),rel:'a.wav',title:'Artist - Song',artist:'Unknown Artist',addedAt:1}];},vault:()=>({hidden:()=>false,exclusive:fn=>fn()}),notify(){}});await editor.withSnapshot(async()=>{const first=await editor.resolve('a.wav');await editor.update('a.wav',{artist:'Artist',title:'Song'},{revision:first.revision});const after=await editor.resolve('a.wav');A.equal(after.track.artist,'Artist');A.equal(after.track.title,'Song');A.equal(after.revision,after.track.editRevision);});A.equal(scans,1);A.equal(editor.snapshotPromise,null);}finally{rm(d);}});
test('292 all artwork source failures are reported, not cached as an empty success',async()=>{let broken=true;const s=createCovers({search:{command:async()=>broken?{ok:false,error:{code:'SEARCH_NETWORK'}}:{ok:true,items:[]},cancel(){}},fetch:async()=>Response.json({})});try{const bad=await s.find({query:'Artist Song',prefs:{enabled:['youtube']}});A.equal(bad.ok,false);A.equal(bad.error.code,'SEARCH_NETWORK');broken=false;A.equal((await s.find({query:'Artist Song',prefs:{enabled:['youtube']}})).ok,true);}finally{s.dispose();}});
test('292 private cover replacement encrypts the image and keeps the playing audio token',async()=>{const h=harness();try{trackFile(h,'secret.wav','Artist',{title:'Secret'});h.api.saveSettings({customCategories:[{id:'custom:a',name:'Private',tracks:['secret.wav']}]},{skipEffects:true});await h.api.vaultCommand({type:'protect',key:'custom:a',name:'Private',password:'test strong password'});const view=await h.api.vaultCommand({type:'unlock',key:'custom:a',password:'test strong password'}),t=view.tracks[0],vault=h.api.getVault(),coverDir=path.join(h.temp,'edit-covers');const editor=new TrackEditor({music:h.music,covers:coverDir,list:()=>h.api.scanLibrary(),vault:()=>vault,notify(){}});const before=await editor.info(t.rel);await editor.update(t.rel,{}, {coverBuffer:png,revision:before.revision});const after=await h.api.vaultCommand({type:'enter',key:'custom:a'});A.equal(after.tracks[0].audioUrl,t.audioUrl);A.equal((await fetch(t.audioUrl)).status,200);A.deepEqual(Buffer.from(await (await fetch(after.tracks[0].coverUrl)).arrayBuffer()),png);A.equal(fs.readdirSync(coverDir).length,0);const {s,entry}=await vault.lookup(t.rel),encoded=fs.readFileSync(vault.file(s.d,entry.cover.id+'.pda'));A.equal(encoded.includes(png),false);}finally{h.close();}});
test('292 URL resolution uses local metadata extraction, pins exact identity and caches it',async()=>{const {createSearchService}=require('../app/online/service');let calls=0;const svc=createSearchService({providers:{},extractInfo:async(url,opts)=>{calls++;A.equal(opts.probe,true);return {track:'Song',artist:'Artist',duration:180,thumbnail:'https://i.ytimg.com/vi/abcdefghijk/hqdefault.jpg',formats:[{url:'https://media.example/a',acodec:'opus',vcodec:'none'}]};}});try{const r=await svc.command({type:'resolve',url:'https://youtu.be/abcdefghijk',requestId:'link'});A.equal(r.ok,true);A.equal(r.item.title,'Song');A.equal(r.item.provider,'youtube');A.equal(r.query,'Artist Song');A.equal(r.item.key,'youtube:abcdefghijk');A.ok(svc.cachedInfo(r.item.url));A.equal((await svc.command({type:'resolve',url:r.item.url})).ok,true);A.equal(calls,1);}finally{svc.dispose();}});
test('292 link resolution rejects unsupported/private URLs and playlists before extractor execution',async()=>{const {createSearchService}=require('../app/online/service');let calls=0;const svc=createSearchService({providers:{},extractInfo:async()=>{calls++;return {};}});try{for(const url of ['https://127.0.0.1/a','file:///etc/passwd','https://youtube.com.evil.test/watch?v=abcdefghijk','https://soundcloud.com/user/sets/album','https://www.youtube.com/playlist?list=abc']){const r=await svc.command({type:'resolve',url});A.equal(r.ok,false);A.equal(r.error.code,'SEARCH_BAD_URL');}A.equal(calls,0);}finally{svc.dispose();}});
test('292 failed/cancelled link resolution never enters known result cache',async()=>{const {createSearchService}=require('../app/online/service');const svc=createSearchService({providers:{},extractInfo:async(u,{signal})=>new Promise((res,rej)=>signal.addEventListener('abort',()=>rej(Object.assign(Error('cancelled'),{name:'AbortError'})),{once:true}))});try{const promise=svc.command({type:'resolve',url:'https://youtu.be/abcdefghijk',requestId:'link'});await new Promise(r=>setTimeout(r,10));svc.cancel('link');const r=await promise;A.equal(r.ok,false);A.equal(r.error.code,'SEARCH_CANCELLED');A.equal(svc.stats().known,0);}finally{svc.dispose();}});
test('292 preload lock subscriptions are independent and revoke only their own listener',()=>{let api;const listeners=new Set(),ctx=vm.createContext({console,require:()=>({contextBridge:{exposeInMainWorld:(_,v)=>{api=v;}},ipcRenderer:{on:(_,cb)=>listeners.add(cb),removeListener:(_,cb)=>listeners.delete(cb)},webUtils:{}})});vm.runInContext(fs.readFileSync(path.join(__dirname,'../app/preload.js'),'utf8'),ctx);let a=0,b=0;const remove=api.lyrics.onLock(()=>a++);api.lyrics.onLock(()=>b++);for(const cb of listeners)cb({},null);A.equal(a,1);A.equal(b,1);remove();for(const cb of listeners)cb({},null);A.equal(a,1);A.equal(b,2);});
test('292 metadata changed during lyric lookup cannot receive results for an old identity',async()=>{const f=queueFixture([demoTrack()]);f.lyrics.search=async()=>{Object.assign(f.lookup.get('one.wav'),{artist:'Corrected artist',revision:'user-change'});return [lyricCandidate()];};try{await runQueue(f,{actions:['lyrics'],consent:true});A.equal(f.saves.length,0);A.ok(f.events.some(p=>p.reason==='TrackChanged'));}finally{f.q.dispose();}});
