'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),os=require('node:os');
const L=require('../app/shared/lyrics'),Colors=require('../app/shared/lyrics-colors');
const {LyricsStore,decode}=require('../app/lyrics/store');const {writeZip,crc32}=require('../app/lyrics/zip');
const C=require('../app/vault/crypto'),{parseUslt,parseVorbisComments}=require('../app/metadata');const {harness,trackFile,tree}=require('./main-harness');
const doc=lines=>L.normalize({lines}).doc;
function unit(name,fn){test('266 '+name,fn);}
function hm(name,fn){unit(name,async()=>{const h=harness();try{await fn(h);}finally{h.close();}});}
const cmd=(h,c)=>h.invoke('lyrics:command',c),vc=(h,c)=>h.invoke('vault:command',c);
function make(h,rel='song.wav'){const f=trackFile(h,rel,'Actual Artist',{title:'Actual Artist - Test [Official Video]'});fs.copyFileSync(path.join(__dirname,'fixtures/lyrics-clock.wav'),f);return f;}
function setupVault(h){make(h,'secret.wav');h.api.saveSettings({customCategories:[{id:'custom:a',name:'Private',tracks:['secret.wav']},{id:'custom:b',name:'Open',tracks:[]}]},{skipEffects:true});}
const protect=h=>vc(h,{type:'protect',key:'custom:a',name:'Private',password:'secret lyrics password'});
const unlock=h=>vc(h,{type:'unlock',key:'custom:a',password:'secret lyrics password'});
unit('plain UTF-8 text preserves Unicode, punctuation and stanza breaks',()=>{const r=L.parse('Снова — свет\n\n第二行 🎤');assert.equal(r.doc.lines.length,3);assert.equal(L.toPlain(r.doc),'Снова — свет\n\n第二行 🎤');assert.ok(r.doc.lines.every(l=>l.startMs===null));});
unit('canonical JSON round-trip retains theme, offset and recording identity',()=>{const a=L.normalize({lines:[{text:'Line',startMs:200,endMs:2000}],offsetMs:50,recordingId:'a'.repeat(64),theme:{mode:'gradient',background:'#123456',gradientColors:['#123456','#fedcba','#456789']}}).doc;assert.deepEqual(L.parse(JSON.stringify(a)).doc,a);});
for(const [text,ms] of [['00:16.3',16300],['00:16.30',16300],['00:16.030',16030],['123:04.999',7384999],['00:16:30',16300]])unit('unambiguous time adapter '+text,()=>assert.equal(L.time(text),ms));
unit('invalid time is rejected without evaluation',()=>{for(const t of ['12:99','NaN','-1','00:01.1000','alert(1)'])assert.throws(()=>L.time(t));});
unit('compact marks belong to following phrase; prefix inherits line start',()=>{const r=L.parse('(00:13):"Снова 😀00:15😀смотрю на небо 😀00:17:50😀ночью"');assert.deepEqual(r.doc.lines[0].segments.map(s=>s.startMs),[13000,15000,17500]);assert.equal(r.doc.lines[0].segments[1].text,'смотрю на небо ');assert.ok(r.warnings.some(w=>w.includes('двоеточие')));});
unit('curly short-form marks suppress outgoing automatic gap',()=>{const r=L.parse('{00:13.000}:"Одна фраза"\n(00:23):"Другая"');assert.ok(r.doc.lines[0].suppressGapAfter);});
unit('compact color blocks are converted by a narrow inert adapter',()=>{const r=L.parse('{\nbgcolor: #dd6e37\ntextcolor: #a07674\n}\n{\n(00:13):"Пример 😀00:15😀текста"\n}');assert.equal(r.doc.theme.background,'#dd6e37');assert.equal(L.plainLine(r.doc.lines[0]),'Пример текста');});
unit('enhanced LRC word stamps and missing stamps form groups',()=>{const a=L.parse('[00:01.00]<00:01.00>Words <00:02.00>as a group <00:04.50>end',{kind:'lrc'}).doc.lines[0];assert.equal(a.segments.length,3);assert.equal(a.segments[1].text,'as a group ');});
unit('partially timed JSON fills preceding time, never fabricates later times',()=>{const a=doc([{startMs:1000,segments:[{text:'one '},{startMs:2000,text:'two '},{text:'three'}]}]).lines[0];assert.deepEqual(a.segments.map(s=>s.startMs),[1000,2000,2000]);});
unit('first segment can establish missing row time',()=>{const r=doc([{segments:[{startMs:1200,text:'Phrase'}]}]);assert.equal(r.lines[0].startMs,1200);});
unit('mixed unsynchronized rows remain visible and unassigned',()=>{const r=L.parse('[00:01.000]One\nНе размечено\n[00:03.000]Two',{kind:'lrc'});assert.equal(r.doc.lines[1].startMs,null);assert.ok(r.warnings.length);});
unit('same timestamps preserve overlapping singers',()=>{const a=L.compile(doc([{startMs:1000,text:'A'},{startMs:1000,text:'B'},{startMs:2000,text:'C'}]),3000);assert.deepEqual(L.activeAt(a,1500),[0,1]);});
unit('repeated LRC tags expand chorus in time order',()=>{const a=L.parse('[00:01][00:07]Chorus\n[00:04]Verse').doc;assert.deepEqual(a.lines.map(l=>l.startMs),[1000,4000,7000]);assert.equal(a.lines[2].text,'Chorus');});
unit('LRC offset uses correct inverse sign and survives export/import',()=>{const a=L.parse('[offset:200]\n[00:01]Phrase').doc;assert.equal(a.offsetMs,-200);assert.equal(L.parse(L.toLrc(a),{kind:'lrc'}).doc.offsetMs,-200);});
unit('known 2.5 second gap gets one note; word starts alone do not',()=>{let r=L.compile(doc([{startMs:0,endMs:1000,text:'A'},{startMs:3500,text:'B'}]),6000);assert.equal(r.filter(l=>l.auto).length,1);r=L.compile(doc([{startMs:0,segments:[{startMs:0,text:'Long sung word'}]},{startMs:9000,text:'Next'}]),12000);assert.equal(r.filter(l=>l.auto).length,0);});
unit('gaps below threshold and suppression never add auto notes',()=>{for(const row of [{startMs:0,endMs:1000,text:'A',suppressGapAfter:true},{startMs:0,endMs:3000,text:'A'}]){const r=L.compile(doc([row,{startMs:5000,text:'B'}]),6000);assert.equal(r.filter(l=>l.auto).length,0);}});
unit('explicit note variants normalized without inline-note destruction',()=>{for(const n of ['♪','♫','🎵','🎶','♬'])assert.equal(doc([{text:n}]).lines[0].kind,'interlude');assert.equal(doc([{text:'Пой ♪ со мной'}]).lines[0].text,'Пой ♪ со мной');});
unit('explicit instrumental interval suppresses duplicate automatic note',()=>{const r=L.compile(doc([{startMs:0,endMs:1000,text:'A'},{startMs:1000,text:'🎶'},{startMs:10000,text:'B'}]),15000);assert.equal(r.filter(l=>l.kind==='interlude').length,1);});
unit('overlapping vocal endings never create a false instrumental interval',()=>{const r=L.compile(doc([{startMs:0,endMs:10000,text:'A'},{startMs:5000,endMs:6000,text:'B'},{startMs:15000,text:'C'}]),17000);assert.equal(r.find(l=>l.auto).startMs,10000);});
unit('intro and known outro supported; untimed leading vocals forbid invented intro',()=>{const r=L.compile(doc([{startMs:3000,endMs:5000,text:'A'}]),9000);assert.equal(r.filter(l=>l.auto).length,2);const a=L.compile(doc([{text:'Unknown first phrase'},{startMs:5000,text:'A'}]),9000);assert.equal(a.filter(l=>l.auto).length,0);});
unit('unknown middle text forbids artificial gap',()=>{const r=L.compile(doc([{startMs:0,endMs:1000,text:'A'},{text:'Unknown'},{startMs:5000,text:'B'}]),6000);assert.equal(r.filter(l=>l.auto).length,0);});
unit('end boundaries are half-open and backward seeks recompute directly',()=>{const r=L.compile(doc([{startMs:0,text:'A'},{startMs:1000,text:'B'}]),2000);assert.deepEqual(L.activeAt(r,1000),[1]);assert.deepEqual(L.activeAt(r,999),[0]);assert.deepEqual(L.activeAt(r,2000),[]);});
unit('invalid offsets, ordering, duplicate text/segments and oversized input bounded',()=>{assert.throws(()=>doc([{startMs:3,text:'a'},{startMs:2,text:'b'}]));assert.throws(()=>doc([{startMs:2,endMs:1,text:'a'}]));assert.throws(()=>doc([{startMs:1,text:'a',segments:[{text:'b'}]}]));assert.throws(()=>doc([{text:'x'.repeat(20001)}]));assert.throws(()=>L.parse('x'.repeat(L.MAX_TEXT+1)));assert.throws(()=>doc(Array.from({length:5001},()=>({text:'a'}))));});
unit('out-of-duration marks warn; saved source object is not mutated',()=>{const raw={lines:[{startMs:9000,text:'a'}]},before=JSON.stringify(raw);assert.ok(L.normalize(raw,{durationMs:2000}).warnings.length);assert.equal(JSON.stringify(raw),before);});
unit('HTML imports only embedded inert JSON and ignore scripts, audio, links',()=>{const html=`<!doctype html><script>throw new Error('DO NOT RUN')</script><script id="lyric-data" type="application/json">[{"t":1,"end":3,"text":"Example","kind":"lyric"}]</script><script id="initial-prefs" type="application/json">{"bg":"#112233","offset":-1}</script>`;const r=L.parse(html);assert.equal(r.doc.lines[0].startMs,1000);assert.equal(r.doc.offsetMs,-1000);assert.equal(r.doc.theme.background,'#112233');assert.throws(()=>L.parse('<html><script>alert(1)</script></html>'));});
unit('malicious colors, source URLs, prototype keys and plain HTML are inert',()=>{const r=L.parse('{"__proto__":{"polluted":true},"theme":{"background":"url(javascript:bad)","text":"red;display:none"},"source":{"url":"javascript:bad"},"lines":[{"text":"<img src=x onerror=alert(1)>"}]}').doc;assert.equal({}.polluted,undefined);assert.equal(r.theme.background,'#302036');assert.equal(r.source,undefined);assert.ok(r.lines[0].text.includes('<img'));});
unit('search preserves title version and records original metadata (expanded in 268)',()=>{const info=L.searchIdentity({artist:'Artist',title:'Artist — Song [Official Video] (Live)'});assert.equal(info.artist,'Artist');assert.equal(info.title,'Song (Live)');assert.equal(info.originalArtist,'Artist');assert.equal(L.searchIdentity({artist:'Art',title:'Artistic Song (sped up)'}).title,'Artistic Song (sped up)');});
unit('color mode cycle skips missing cover and defaults to gradient',()=>{assert.equal(L.theme().mode,'gradient');assert.deepEqual(Colors.modes(false),['gradient','solid']);assert.equal(Colors.nextMode('solid',false),'gradient');assert.equal(Colors.nextMode('cover',false),'solid');assert.equal(Colors.scene(L.theme({mode:'cover'})).mode,'gradient');});
unit('cover contrast guaranteed against all RGB extremes and sampled pixels',()=>{for(const average of [[0,0,0],[255,255,255],[128,20,220]]){const s=Colors.scene(L.theme({mode:'cover'}),{hasCover:true,average});for(let r=0;r<256;r+=17)for(let g=0;g<256;g+=17)for(let b=0;b<256;b+=17){const composed=Colors.mix(Colors.mix(Colors.rgb(s.base),[r,g,b],s.coverOpacity),Colors.rgb(s.tint),s.scrim);assert.ok(Colors.ratio(s.text,composed)>=4.5);assert.ok(Colors.ratio(s.active,composed)>=4.5);}assert.ok(s.coverOpacity<1);}});
unit('dark and bright covers pick different monochrome foregrounds',()=>{assert.equal(Colors.scene(L.theme({mode:'cover'}),{hasCover:true,average:[10,10,10]}).active,'#ffffff');assert.equal(Colors.scene(L.theme({mode:'cover'}),{hasCover:true,average:[240,240,240]}).active,'#000000');});
unit('gradient automatic contrast holds for colorful and black-white transitions',()=>{for(const colors of [['#000000','#ffffff'],['#ff0000','#00ff00','#0000ff'],['#ffffff','#ffffcc'],['#442040','#112233']]){const s=Colors.scene(L.theme({gradientColors:colors}));assert.ok(s.minContrast>=4.5);for(let i=0;i<colors.length-1;i++)for(let k=0;k<=1000;k++){const rgb=Colors.mix(Colors.mix(Colors.rgb(colors[i]),Colors.rgb(colors[i+1]),k/1000),Colors.rgb(s.tint),s.scrim);assert.ok(Colors.ratio(rgb,s.text)>=4.5);}}});
unit('manual low contrast is reported; cover cannot disable readability',()=>{const t=L.theme({mode:'solid',background:'#ffffff',text:'#fefefe',activeText:'#fefefe',autoContrast:false});assert.ok(Colors.scene(t).minContrast<2);t.mode='cover';assert.ok(Colors.scene(t,{hasCover:true}).minContrast>=4.5);});
unit('metadata USLT preserves newlines for UTF8/UTF16, Vorbis lyrics not flattened',()=>{assert.equal(parseUslt(Buffer.concat([Buffer.from([3]),Buffer.from('eng\0'),Buffer.from('Line 1\nLine 2')])),'Line 1\nLine 2');const comment=Buffer.from('LYRICS=Один\nДва'),buffer=Buffer.alloc(12+comment.length);buffer.writeUInt32LE(0);buffer.writeUInt32LE(1,4);buffer.writeUInt32LE(comment.length,8);comment.copy(buffer,12);assert.equal(parseVorbisComments(buffer).embeddedLyrics,'Один\nДва');});
unit('imports handle UTF16 BOM and Windows1251 fallback',()=>{assert.equal(decode(Buffer.concat([Buffer.from([255,254]),Buffer.from('Текст','utf16le')])),'Текст');assert.equal(decode(Buffer.from([0xcf,0xf0,0xe8,0xe2,0xe5,0xf2])),'Привет');});
hm('read/save use hash identity, survive file rename and never rewrite audio',async h=>{const file=make(h);const before=fs.readFileSync(file);let r=await cmd(h,{type:'get',rel:'song.wav'});assert.equal(r.doc,null);r=await cmd(h,{type:'save',rel:'song.wav',doc:doc([{text:'LOCAL LYRICS'}]),revision:r.revision});const id=r.recordingId;assert.deepEqual(fs.readFileSync(file),before);fs.renameSync(file,path.join(h.api.paths.music,'renamed.wav'));fs.renameSync(file+'.pulse.json',path.join(h.api.paths.music,'renamed.wav.pulse.json'));await h.api.scanLibrary(true);r=await cmd(h,{type:'get',rel:'renamed.wav'});assert.equal(r.recordingId,id);assert.equal(r.doc.lines[0].text,'LOCAL LYRICS');});
hm('neighbor LRC/embedded lookup and saved manual priority',async h=>{const file=make(h);fs.writeFileSync(file+'.lrc','[00:01.00]Neighbor\n[00:03.00]Second');let r=await cmd(h,{type:'get',rel:'song.wav'});assert.equal(r.doc.lines[0].text,'Neighbor');assert.equal(r.doc.lines[0].startMs,1000);await cmd(h,{type:'save',rel:'song.wav',doc:doc([{text:'Manual'}]),revision:null});fs.writeFileSync(file+'.lrc','[00:01.00]Changed neighbor');assert.equal((await cmd(h,{type:'get',rel:'song.wav'})).doc.lines[0].text,'Manual');});
hm('optimistic revision and invalid import cannot overwrite working text',async h=>{make(h);const saved=await cmd(h,{type:'save',rel:'song.wav',doc:doc([{text:'KEEP'}])});const before=tree(h.api.paths.data);await assert.rejects(cmd(h,{type:'save',rel:'song.wav',doc:{lines:[]},revision:saved.revision}));await assert.rejects(cmd(h,{type:'save',rel:'song.wav',doc:doc([{text:'wrong'}]),revision:'stale'}));await assert.rejects(cmd(h,{type:'save',rel:'song.wav',doc:{lines:[{text:'Wrong record'}],recordingId:'f'.repeat(64)},revision:saved.revision}));assert.deepEqual(tree(h.api.paths.data),before);});
hm('display mode settings persisted but arbitrary injected fields discarded',async h=>{h.api.saveSettings({lyricsDisplay:{wordMode:'lines',secret:'NO'}},{skipEffects:true});assert.deepEqual(JSON.parse(JSON.stringify(h.api.getSettings().lyricsDisplay)),{wordMode:'lines'});});
hm('lyrics IPC rejects a foreign renderer and unknown track references',async h=>{make(h);assert.throws(()=>h.handlers.get('lyrics:command')({sender:{}},{type:'get',rel:'song.wav'}));await assert.rejects(cmd(h,{type:'get',rel:'../elsewhere.wav'}));});
hm('local import previews mismatch, never saves or executes HTML',async h=>{make(h);const file=path.join(h.temp,'import.html');fs.writeFileSync(file,'<html><script>process.exit()</script><script id="lyric-data">[{"t":1,"text":"USER INPUT","kind":"lyric"}]</script></html>');h.electron.dialog.showOpenDialog=async()=>({filePaths:[file]});const r=await cmd(h,{type:'import',rel:'song.wav'});assert.equal(r.doc.lines[0].text,'USER INPUT');assert.equal((await cmd(h,{type:'get',rel:'song.wav'})).doc,null);});
hm('search only on consent, uses fixed LRCLIB endpoint with metadata, no audio',async h=>{make(h);const store=h.api.getLyrics();let url;store.fetchJson=async u=>{url??=u;return [{id:12,trackName:'Test',artistName:'Actual Artist',duration:65,syncedLyrics:'[00:01]Example'},{id:2,duration:100,plainLyrics:'X'}];};await assert.rejects(cmd(h,{type:'search',rel:'song.wav'}));const r=await cmd(h,{type:'search',rel:'song.wav',consent:true,duration:64});assert.equal(url.hostname,'lrclib.net');assert.equal(url.searchParams.get('artist_name'),'Actual Artist');assert.equal(url.searchParams.get('track_name'),'Test');assert.ok(!url.href.includes('song.wav'));assert.equal(r[0].id,12);assert.equal(r[0].delta,1);});
hm('malformed provider reply reports failure without overwriting local lyrics',async h=>{make(h);h.api.getLyrics().fetchJson=async()=>({error:true});await assert.rejects(cmd(h,{type:'search',rel:'song.wav',consent:true}),/ответ/);assert.equal((await cmd(h,{type:'get',rel:'song.wav'})).doc,null);});
hm('protection migrates saved text and all alternate sidecars into authenticated ciphertext',async h=>{setupVault(h);const f=path.join(h.api.paths.music,'secret.wav');fs.writeFileSync(f+'.lrc','[00:01]PRIVATE WORDS');fs.writeFileSync(path.join(h.api.paths.music,'secret.txt'),'ALTERNATE PRIVATE');await cmd(h,{type:'save',rel:'secret.wav',doc:doc([{text:'PRIVATE EDITED'}])});const result=await protect(h);assert.equal(result.warnings.length,0);assert.ok(!fs.existsSync(f));assert.ok(!fs.existsSync(f+'.lrc'));assert.ok(!fs.existsSync(path.join(h.api.paths.music,'secret.txt')));const entries=fs.readdirSync(path.join(h.api.paths.music,'.pulsedeck-lyrics'));assert.equal(entries.length,1);const box=fs.readFileSync(path.join(h.api.paths.music,'.pulsedeck-lyrics',entries[0]),'utf8');for(const s of ['PRIVATE','secret.wav'])assert.ok(!box.includes(s));assert.equal(fs.readdirSync(path.join(h.api.paths.data,'lyrics')).length,0);const view=await unlock(h),rel=view.tracks[0].rel;const r=await cmd(h,{type:'get',rel});assert.equal(r.doc.lines[0].text,'PRIVATE EDITED');assert.equal(r.originalSidecars,undefined);const {entry}=await h.api.getVault().lookup(rel);const raw=C.open(JSON.parse(box),entry.blob.key,`lyrics:${entry.id}`);assert.equal(raw.originalSidecars.length,2);await cmd(h,{type:'save',rel,doc:doc([{text:'PRIVATE REVISED'}]),revision:r.revision});await vc(h,{type:'enter',key:'all'});await assert.rejects(cmd(h,{type:'get',rel}));const again=await unlock(h);assert.equal((await cmd(h,{type:'get',rel:again.tracks[0].rel})).doc.lines[0].text,'PRIVATE REVISED');});
hm('invalid neighboring text is archived, not silently erased from existence',async h=>{setupVault(h);const side=path.join(h.api.paths.music,'secret.wav.lyrics.json');fs.writeFileSync(side,'{BROKEN JSON ORIGINAL');await protect(h);const u=await unlock(h),{entry}=await h.api.getVault().lookup(u.tracks[0].rel);const record=C.open(JSON.parse(fs.readFileSync(h.api.getLyrics().privateFile(entry.id))),entry.blob.key,`lyrics:${entry.id}`);assert.equal(Buffer.from(record.originalSidecars[0].data,'base64').toString(),'{BROKEN JSON ORIGINAL');});
hm('sidecar changed after capture is never deleted by cleanup',async h=>{const f=make(h),store=h.api.getLyrics();fs.writeFileSync(f+'.lrc','[00:01]FIRST');const id=crypto.randomBytes(16).toString('hex');const entry={id,blob:{sha256:await store.fingerprint(f),key:crypto.randomBytes(32).toString('base64')}};await store.sealForVault((await h.api.scanLibrary())[0],entry);fs.writeFileSync(f+'.lrc','[00:01]CHANGED');await assert.rejects(store.retirePublic(['song.wav'],entry),/изменился/);assert.equal(fs.readFileSync(f+'.lrc','utf8'),'[00:01]CHANGED');assert.ok(fs.existsSync(f));});
hm('oversized raw sidecar stops protection cleanup and preserves originals',async h=>{setupVault(h);const side=path.join(h.api.paths.music,'secret.txt');fs.writeFileSync(side,Buffer.alloc(4*1024*1024+1,65));await assert.rejects(protect(h),/4 МБ/);assert.ok(fs.existsSync(path.join(h.api.paths.music,'secret.wav')));assert.ok(fs.existsSync(side));});
hm('public text export preserves audio and blocks destinations inside library',async h=>{const f=make(h);await cmd(h,{type:'save',rel:'song.wav',doc:doc([{startMs:1000,text:'DATA'}])});h.electron.dialog.showSaveDialog=async()=>({filePath:f});await assert.rejects(cmd(h,{type:'export-text',rel:'song.wav'}),/вне music/);const dest=path.join(h.temp,'lyrics.lrc');h.electron.dialog.showSaveDialog=async()=>({filePath:dest});await cmd(h,{type:'export-text',rel:'song.wav',format:'lrc'});assert.equal(L.parse(fs.readFileSync(dest,'utf8'),{kind:'lrc'}).doc.lines[0].text,'DATA');});
function readZip(file){const b=fs.readFileSync(file),eocd=b.length-22;assert.equal(b.readUInt32LE(eocd),0x06054b50);let pos=b.readUInt32LE(eocd+16);const files={};for(let i=0;i<b.readUInt16LE(eocd+10);i++){assert.equal(b.readUInt32LE(pos),0x02014b50);const len=b.readUInt16LE(pos+28),size=b.readUInt32LE(pos+24),local=b.readUInt32LE(pos+42),name=b.subarray(pos+46,pos+46+len).toString(),start=local+30+b.readUInt16LE(local+26);const data=b.subarray(start,start+size);assert.equal((crc32(data)^0xffffffff)>>>0,b.readUInt32LE(pos+16));files[name]=data;pos+=46+len;}return files;}
hm('real streaming ZIP contains byte-identical audio, instruction and no local paths',async h=>{const f=make(h),before=fs.readFileSync(f),dest=path.join(h.temp,'package.zip');h.electron.dialog.showSaveDialog=async()=>({filePath:dest});await cmd(h,{type:'save',rel:'song.wav',doc:doc([{text:'Example local'}])});await cmd(h,{type:'export-package',rel:'song.wav'});const z=readZip(dest);assert.deepEqual(z['audio.wav'],before);assert.equal(JSON.parse(z['track.json']).recordingId,crypto.createHash('sha256').update(before).digest('hex'));assert.ok(z['INSTRUCTIONS.md']);assert.ok(z['example.lyrics.json']);assert.ok(z['lyrics.json']);assert.ok(!z['track.json'].toString().includes(h.temp));assert.deepEqual(fs.readFileSync(f),before);});
hm('fresh private password required for audio ZIP; ciphertext remains protected',async h=>{setupVault(h);await cmd(h,{type:'save',rel:'secret.wav',doc:doc([{text:'SECRET LYRIC'}])});const bytes=fs.readFileSync(path.join(h.api.paths.music,'secret.wav'));await protect(h);const u=await unlock(h),rel=u.tracks[0].rel,dest=path.join(h.temp,'private.zip');h.electron.dialog.showSaveDialog=async()=>({filePath:dest});await assert.rejects(cmd(h,{type:'export-package',rel,password:'wrong password'}));assert.ok(!fs.existsSync(dest));const before=tree(h.api.paths.music);await cmd(h,{type:'export-package',rel,password:'secret lyrics password'});const z=readZip(dest);assert.deepEqual(z['audio.wav'],bytes);assert.equal(z['text.txt'].toString(),'SECRET LYRIC');assert.deepEqual(tree(h.api.paths.music),before);});
hm('parallel exports rejected while a save dialog is pending; cancel invalidates pending task',async h=>{make(h);let resolve;h.electron.dialog.showSaveDialog=()=>new Promise(r=>resolve=r);const first=cmd(h,{type:'export-package',rel:'song.wav'});while(!resolve)await new Promise(r=>setTimeout(r,5));await assert.rejects(cmd(h,{type:'export-package',rel:'song.wav'}),/Дождись/);await cmd(h,{type:'cancel-export'});resolve({filePath:path.join(h.temp,'cancelled.zip')});await assert.rejects(first,/отменён/);assert.ok(!fs.existsSync(path.join(h.temp,'cancelled.zip')));});
unit('ZIP stream failures keep old destination and remove partial data',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'lyrics-zip-'));try{const dest=path.join(root,'out.zip');fs.writeFileSync(dest,'OLD');await assert.rejects(writeZip(dest,[{name:'audio.wav',size:10,stream:async function*(){yield Buffer.from('some');throw Error('interrupted');}}]));assert.equal(fs.readFileSync(dest,'utf8'),'OLD');assert.deepEqual(fs.readdirSync(root),['out.zip']);}finally{fs.rmSync(root,{recursive:true,force:true});}});

hm('export rejects symbolic-link aliases into music and data',async h=>{
 make(h);const store=h.api.getLyrics();for(const [n,root]of [['music',h.api.paths.music],['data',h.api.paths.data]]){const alias=path.join(h.temp,'alias-'+n);fs.symlinkSync(root,alias,'junction');assert.throws(()=>store.checkDestination(path.join(alias,'export.zip')),/вне music/);}store.checkDestination(path.join(h.temp,'external.zip'));
});
hm('public transfer restores lyric metadata; private references use the shared edited public text',async h=>{
 setupVault(h);await cmd(h,{type:'save',rel:'secret.wav',doc:doc([{text:'First private words'}]),revision:null});await protect(h);const opened=await unlock(h),rel=opened.tracks[0].rel;
 await vc(h,{type:'transfer',source:'custom:a',rels:[rel],target:'custom:b',password:'secret lyrics password'});
 const songs=await h.api.scanLibrary(true),publicTrack=songs.find(t=>t.rel==='secret.wav');assert.ok(publicTrack);
 const current=await cmd(h,{type:'get',rel:publicTrack.rel});assert.equal(current.doc.lines[0].text,'First private words');await cmd(h,{type:'save',rel:publicTrack.rel,doc:doc([{text:'Changed shared public words'}]),revision:current.revision});
 const privateView=await cmd(h,{type:'get',rel});assert.equal(privateView.doc.lines[0].text,'Changed shared public words');
});

unit('staged ZIP is not committed by a worker without main authorization',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'lyrics-stage-'));try{const dest=path.join(root,'out.zip'),part=path.join(root,'staged.partial');fs.writeFileSync(dest,'OLD');await writeZip(dest,[{name:'text.txt',text:'New data'}],{part,commit:false});assert.equal(fs.readFileSync(dest,'utf8'),'OLD');assert.equal(readZip(part)['text.txt'].toString(),'New data');}finally{fs.rmSync(root,{recursive:true,force:true});}});
hm('locking during the final ZIP stage cancels it without replacing the old destination',async h=>{setupVault(h);await protect(h);const opened=await unlock(h),rel=opened.tracks[0].rel,dest=path.join(h.temp,'private-cancel.zip');fs.writeFileSync(dest,'OLD');h.electron.dialog.showSaveDialog=async()=>({filePath:dest});let locked=false;h.api.getLyrics().progress=({percent})=>{if(percent===99&&!locked){locked=true;h.api.getVault().lock();}};await assert.rejects(cmd(h,{type:'export-package',rel,password:'secret lyrics password'}),/отменён/);assert.ok(locked);assert.equal(fs.readFileSync(dest,'utf8'),'OLD');assert.ok(!fs.readdirSync(h.temp).some(f=>f.endsWith('.partial')));});
