'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const L=require('../app/shared/lyrics'),E=require('../app/shared/lyrics-editor'),M=require('../app/shared/library-model');
const {harness,trackFile,tree}=require('./main-harness');
const t=(name,fn)=>test('267 '+name,fn),clone=x=>JSON.parse(JSON.stringify(x));
const track=(rel,artist='Alpha')=>({id:rel,rel,artist,title:rel,duration:64,addedAt:1});
const tracks=[track('one.wav'),track('two.wav','Beta'),track('three.wav','Gamma')];
const state=()=>M.normalizeOrganization({favorites:['one.wav'],recent:{'two.wav':100},playlistMembership:{downloads:{included:['three.wav'],excluded:[]}},customCategories:[{id:'custom:a',name:'A',tracks:[]},{id:'custom:b',name:'B',tracks:['one.wav']}]});
function htest(name,fn){t(name,async()=>{const h=harness();try{await fn(h);}finally{h.close();}});}
const cmd=(h,c)=>h.invoke('lyrics:command',c),v=(h,c)=>h.invoke('vault:command',c);
function make(h,rel='one.wav'){const f=trackFile(h,rel,'Alpha',{title:'Exact song'});fs.copyFileSync(path.join(__dirname,'fixtures/lyrics-clock.wav'),f);return f;}

t('word splitting preserves Unicode, emoji, repeated spaces and punctuation',()=>{for(const text of ["  Don't  stop, the  🎵 music!  ",'One\t two\nthree','Ночь. Над городом — огни','静かな夜の光','   ']){assert.equal(E.pieces(text).join(''),text);assert.equal(E.tokens({text,startMs:1200}).map(t=>t.text).join(''),text);}});
t('editing a middle word splits its inherited phrase without guessing other times',()=>{const row={startMs:1000,endMs:null,segments:[{startMs:1000,text:'One two three '},{startMs:4000,text:'four'}]},before=clone(row),words=E.tokens(row);assert.deepEqual(words.map(w=>w.explicit),[true,false,false,true]);const r=E.wordRow(row,words,1,2200);assert.deepEqual(r.row.segments,[{startMs:1000,text:'One '},{startMs:2200,text:'two three '},{startMs:4000,text:'four'}]);assert.deepEqual(row,before);});
t('clearing a word-specific time restores inherited group timing',()=>{const row={startMs:1000,segments:[{startMs:1000,text:'One '},{startMs:2000,text:'two three'}]},r=E.wordRow(row,E.tokens(row),1,null);assert.deepEqual(r.row.segments,[{startMs:1000,text:'One two three'}]);});
t('untimed words remain usable and get line start only from a known mark',()=>{const row={startMs:null,endMs:null,text:'One two three'},r=E.wordRow(row,E.tokens(row),1,3000);assert.equal(r.row.startMs,3000);assert.equal(r.row.segments[0].startMs,null);assert.equal(L.plainLine(r.row),'One two three');assert.doesNotThrow(()=>L.normalize({lines:[r.row]}));});
t('duplicate word times are valid simultaneous phrases',()=>{const row={startMs:1000,text:'One two'};assert.doesNotThrow(()=>L.normalize({lines:[E.wordRow(row,E.tokens(row),1,1000).row]}));});
t('invalid backward word timing is rejected by normalization before save',()=>{const row={startMs:2000,text:'One two'};assert.throws(()=>L.normalize({lines:[E.wordRow(row,E.tokens(row),1,1000).row]}));});
t('word editing validates negative, infinite, fractional and out-of-range values',()=>{for(const n of [-1,Infinity,NaN,1.5,86400001])assert.throws(()=>E.wordRow({text:'one'},E.tokens({text:'one'}),0,n));});
t('line shift preserves milliseconds and measured phrase-end interval',()=>{const row={startMs:1250,endMs:5750,segments:[{startMs:1250,text:'one '},{startMs:2355,text:'two'}]};const r=E.shiftStart(row,2000);assert.deepEqual(r.segments.map(x=>x.startMs),[2000,3105]);assert.equal(r.endMs,6500);assert.equal(row.startMs,1250);});
t('clearing line end does not fabricate a measured vocal end or automatic note',()=>{const d=L.normalize({durationMs:64000,lines:[{startMs:1000,text:'Held syllable'},{startMs:12000,text:'Next'}]}).doc;assert.equal(d.lines[0].endMs,null);assert.equal(E.inferredEnd(d.lines,0,64000),12000);const rows=L.compile(d,64000);assert.equal(rows.filter(x=>x.kind==='interlude'&&x.startMs>1000&&x.startMs<12000).length,0);});
t('end hint skips untimed and simultaneous lines, final line uses recording end',()=>{const lines=[{startMs:1000},{startMs:null},{startMs:1000},{startMs:7000}];assert.equal(E.inferredEnd(lines,0,9000),7000);assert.equal(E.inferredEnd(lines,1,9000),null);assert.equal(E.inferredEnd(lines,3,9000),9000);});
t('timing preferences allow a blank lyric record and clamp malformed input',()=>{assert.deepEqual(E.preferences(),{offsetMs:0,gapThresholdMs:2500});assert.deepEqual(E.preferences({offsetMs:-100,gapThresholdMs:5000}),{offsetMs:-100,gapThresholdMs:5000});assert.deepEqual(E.preferences({offsetMs:Infinity,gapThresholdMs:0}),{offsetMs:0,gapThresholdMs:1000});});
t('uncertainty notes survive import/export as inert strings with bounded size',()=>{const doc=L.normalize({notes:['Timing not independently checked.','<script>alert(1)</script>'],lines:[{text:'Own words'}]}).doc;assert.equal(doc.notes[0],'Timing not independently checked.');assert.ok(doc.notes[1].includes('<script>'));assert.ok(!('notes' in L.normalize({lines:[{text:'Own words'}]}).doc));});
for(const target of ['all','favorite','recent','downloads','custom:a'])t(`all system categories can merge into ${target} without losing their engines`,()=>{const s=state(),before=clone(s),keys=['all','favorite','recent','downloads','custom:a'];const result=M.bulkCategories(s,tracks,keys,'merge',target);assert.equal(result.count,keys.length);assert.equal(M.view(tracks,result.settings,target,'recent').length,tracks.length);for(const k of keys.filter(k=>k!==target&&k!=='custom:a'))assert.equal(result.settings.categoryStyles[k].hidden,true);assert.ok(M.categories(tracks,result.settings,true).find(c=>c.key===target));assert.deepEqual(clone(s),before);assert.ok(result.settings.favorites.includes('one.wav'));assert.equal(M.view(tracks,result.settings,'all','recent').length,tracks.length);});
t('partial deletion reports eligible and skipped keys and never alters audio membership of All',()=>{const s=state(),r=M.bulkCategories(s,tracks,['favorite','recent','custom:a','custom:b'],'delete');assert.equal(r.count,2);assert.deepEqual(r.skipped,['favorite','recent']);assert.deepEqual(r.applied,['custom:a','custom:b']);assert.equal(r.settings.customCategories.length,0);assert.deepEqual(r.settings.favorites,s.favorites);assert.equal(M.view(tracks,r.settings,'all','recent').length,3);});
t('system-only deletion is an explicit harmless empty subset',()=>{const s=state(),r=M.bulkCategories(s,tracks,['all','recent'],'delete');assert.equal(r.count,0);assert.deepEqual(r.skipped,['all','recent']);assert.deepEqual(r.settings,s);});
t('stale category IDs still reject before modifying any category',()=>{const s=state(),before=clone(s);assert.throws(()=>M.bulkCategories(s,tracks,['custom:a','missing'],'delete'));assert.deepEqual(clone(s),before);});
t('partial eligibility for deletion, artists and protected access is independent',()=>{const cats=[{key:'all',canDelete:false,kind:'system',protected:true},{key:'custom:a',canDelete:true,kind:'custom'},{key:'artist:alpha',canDelete:true,kind:'artist',protected:true}];assert.deepEqual(M.playlistBatchEligibility(cats,'delete').map(c=>c.key),['custom:a','artist:alpha']);assert.deepEqual(M.playlistBatchEligibility(cats,'alias').map(c=>c.key),['artist:alpha']);assert.deepEqual(M.playlistBatchEligibility(cats,'link').map(c=>c.key),['all','artist:alpha']);});
t('system appearance may be renamed without changing smart identity',()=>{const s=state();s.categoryStyles.favorite={name:'My favorites'};const c=M.categories(tracks,s,true).find(c=>c.key==='favorite');assert.ok(c.canRename);assert.equal(c.canDelete,false);assert.equal(c.key,'favorite');});
htest('real save and reload keeps offset/gap/theme with no lyric text and identical audio',async h=>{const f=make(h),before=fs.readFileSync(f),initial=await cmd(h,{type:'get',rel:'one.wav'});const r=await cmd(h,{type:'save',rel:'one.wav',doc:null,theme:{background:'#654321',mode:'solid'},timing:{offsetMs:200,gapThresholdMs:5000},revision:initial.revision});assert.equal(r.doc,null);const loaded=await cmd(h,{type:'get',rel:'one.wav'});assert.deepEqual(loaded.timing,{offsetMs:200,gapThresholdMs:5000});assert.equal(loaded.theme.background,'#654321');assert.deepEqual(fs.readFileSync(f),before);});
htest('presentation-only settings do not prevent discovery of newly added local lyrics',async h=>{const f=make(h);await cmd(h,{type:'save',rel:'one.wav',doc:null,timing:{offsetMs:300,gapThresholdMs:6000},theme:{mode:'solid',background:'#654321'}});fs.writeFileSync(f+'.lrc','[00:02]Newly found lyric');const r=await cmd(h,{type:'get',rel:'one.wav'});assert.equal(r.doc.lines[0].text,'Newly found lyric');assert.equal(r.doc.offsetMs,300);assert.equal(r.doc.gapThresholdMs,6000);assert.equal(r.theme.background,'#654321');});
htest('recording preferences remain isolated between different files',async h=>{make(h);trackFile(h,'two.wav','Beta');await cmd(h,{type:'save',rel:'one.wav',doc:null,timing:{offsetMs:500,gapThresholdMs:6000}});const r=await cmd(h,{type:'get',rel:'two.wav'});assert.equal(r.timing.offsetMs,0);assert.equal(r.timing.gapThresholdMs,2500);});
htest('encrypted blank text retains preconfigured settings after lock and unlock',async h=>{make(h);h.api.saveSettings({customCategories:[{id:'custom:a',name:'Private',tracks:['one.wav']}]},{skipEffects:true});await cmd(h,{type:'save',rel:'one.wav',doc:null,timing:{offsetMs:-400,gapThresholdMs:4000}});await v(h,{type:'protect',key:'custom:a',name:'Private',password:'safe test password'});const u=await v(h,{type:'unlock',key:'custom:a',password:'safe test password'});const r=await cmd(h,{type:'get',rel:u.tracks[0].rel});assert.equal(r.doc,null);assert.deepEqual(r.timing,{offsetMs:-400,gapThresholdMs:4000});assert.equal(fs.readdirSync(path.join(h.api.paths.data,'lyrics')).length,0);});
htest('main-process bulk merge accepts multiple system sources with custom destination',async h=>{make(h);trackFile(h,'two.wav','Beta');h.api.saveSettings({customCategories:[{id:'custom:a',name:'Destination',tracks:[]}],favorites:['one.wav'],playlistMembership:{downloads:{included:['two.wav'],excluded:[]}}},{skipEffects:true});const before=tree(h.api.paths.music);const r=await v(h,{type:'bulk-categories',action:'merge',keys:['favorite','downloads','custom:a'],target:'custom:a'});assert.ok(r.settings.categoryStyles.favorite.hidden);assert.ok(r.settings.categoryStyles.downloads.hidden);assert.equal(r.settings.customCategories[0].tracks.length,2);assert.deepEqual(tree(h.api.paths.music),before);});
htest('main-process partial deletion skips protected system without requiring its password',async h=>{make(h);h.api.saveSettings({customCategories:[{id:'custom:a',name:'Empty',tracks:[]}]},{skipEffects:true});await v(h,{type:'protect',key:'all',name:'All',password:'protected all password'});const before=tree(h.api.paths.music);const r=await v(h,{type:'bulk-categories',action:'delete',keys:['all','custom:a']});assert.equal(r.count,1);assert.ok(r.settings.protectedPlaylists.all);assert.equal(r.settings.customCategories.length,0);assert.deepEqual(tree(h.api.paths.music),before);});
t('archive README and instructions are English and require chat JSON after actual research',()=>{const dir=path.join(__dirname,'../app/lyrics'),readme=fs.readFileSync(path.join(dir,'README.md'),'utf8'),instructions=fs.readFileSync(path.join(dir,'INSTRUCTIONS.md'),'utf8'),example=fs.readFileSync(path.join(dir,'example.lyrics.json'),'utf8');for(const s of [readme,instructions,example])assert.ok(!/[\u0400-\u04ff]/.test(s));assert.match(readme,/without explaining/);assert.match(readme,/not an attachment/);assert.match(instructions,/Find suitable original lyric sources yourself/);assert.match(instructions,/Never invent/);assert.doesNotThrow(()=>L.normalize(JSON.parse(example)));assert.ok(fs.readFileSync(path.join(dir,'export-worker.js'),'utf8').includes('README.md'));});
htest('multiple protected system sources merge to ordinary destination with passwords, preserving archives',async h=>{make(h);trackFile(h,'two.wav','Beta');h.api.saveSettings({favorites:['one.wav'],customCategories:[{id:'custom:a',name:'Receiver',tracks:[]}]},{skipEffects:true});await v(h,{type:'protect',key:'favorite',name:'Favorite',password:'first safe password'});await v(h,{type:'protect',key:'recent',name:'Recent',password:'second safe password'});const before=tree(h.api.paths.music);await assert.rejects(v(h,{type:'bulk-categories',action:'merge',keys:['favorite','recent','custom:a'],target:'custom:a',passwords:{favorite:'first safe password',recent:'bad'}}));assert.deepEqual(tree(h.api.paths.music),before);const r=await v(h,{type:'bulk-categories',action:'merge',keys:['favorite','recent','custom:a'],target:'custom:a',passwords:{favorite:'first safe password',recent:'second safe password'}});assert.equal(r.count,3);assert.equal(r.settings.customCategories[0].tracks.length,2);assert.ok(r.settings.categoryStyles.favorite.hidden&&r.settings.categoryStyles.recent.hidden);assert.ok(!r.settings.protectedPlaylists.favorite&&!r.settings.protectedPlaylists.recent);assert.equal((await h.api.scanLibrary()).length,2);assert.ok(h.api.getVault().index.vaults.favorite.deleted&&h.api.getVault().index.vaults.recent.deleted);});
htest('unrelated protected target field cannot extend a deletion selection',async h=>{make(h);h.api.saveSettings({customCategories:[{id:'custom:a',name:'Remove',tracks:[]},{id:'custom:b',name:'Keep',tracks:['one.wav']}]},{skipEffects:true});await v(h,{type:'protect',key:'custom:b',name:'Keep',password:'unrelated safe password'});const before=tree(h.api.paths.music);const r=await v(h,{type:'bulk-categories',action:'delete',keys:['custom:a'],target:'custom:b',passwords:{'custom:b':'unrelated safe password'}});assert.ok(r.settings.protectedPlaylists['custom:b']);assert.equal(r.count,1);assert.deepEqual(tree(h.api.paths.music),before);});
