'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const P=require('../tools/sign-release'),S=require('../app/updates/security');
const keys=crypto.generateKeyPairSync('ed25519'),config={repository:{owner:'test-owner',name:'test-project'},publicKey:keys.publicKey.export({type:'spki',format:'pem'})};
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'pd-publish-'));test.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));
function exe(v){const p=path.join(tmp,`PulseDeck-Setup-${v}.exe`);fs.writeFileSync(p,'MZtest fixture');return p;}
test('Publishing signs stable for BOTH feeds; envelopes verify and bind exact binary size/hash',()=>{const files=P.application({config,key:keys.privateKey,exe:exe('2.8.1'),version:'2.8.1',notes:{ru:'Изменения',en:'Changes'}});assert.deepEqual(Object.keys(files),['pulsedeck-update-stable.json','pulsedeck-update-beta.json']);for(const channel of ['stable','beta']){const m=S.verifyEnvelope(files[`pulsedeck-update-${channel}.json`],config);assert.equal(m.channel,channel);assert.equal(m.version,'2.8.1');assert.equal(m.file.size,14);assert.equal(m.file.sha256,P.asset(exe('2.8.1'),'x').sha256);}});
test('Publishing prereleases never writes a stable channel asset',()=>{const files=P.application({config,key:keys.privateKey,exe:exe('2.8.1-beta.1'),version:'2.8.1-beta.1',notes:{ru:'Бета',en:'Beta'}});assert.deepEqual(Object.keys(files),['pulsedeck-update-beta.json']);});
test('Publishing rejects missing translated notes, wrong filenames and non-PE artifacts',()=>{for(const change of [{notes:{en:'Only English'}},{exe:exe('2.8.2')}])assert.throws(()=>P.application({config,key:keys.privateKey,exe:exe('2.8.1'),version:'2.8.1',notes:{ru:'RU',en:'EN'},...change}));const f=exe('2.8.3');fs.writeFileSync(f,'not an executable');assert.throws(()=>P.application({config,key:keys.privateKey,exe:f,version:'2.8.3',notes:{ru:'RU',en:'EN'}}));});
test('Private signing key must match public key; no keys or placeholder repository are silently accepted',()=>{const f=path.join(tmp,'private.pem');fs.writeFileSync(f,keys.privateKey.export({type:'pkcs8',format:'pem'}));assert.equal(P.signingKey(f,config).asymmetricKeyType,'ed25519');assert.throws(()=>P.signingKey(f,{...config,publicKey:crypto.generateKeyPairSync('ed25519').publicKey.export({format:'pem',type:'spki'})}));assert.throws(()=>P.signingKey(f,{repository:null,publicKey:''}));});
test('Key generation refuses repository storage/overwrites; private key permissions are restricted',()=>{assert.throws(()=>P.keygen(path.resolve(__dirname,'../private-key')));const prefix=path.join(tmp,'new-key');P.keygen(prefix);assert.throws(()=>P.keygen(prefix));if(process.platform!=='win32')assert.equal(fs.statSync(prefix+'.private.pem').mode&0o777,0o600);});
test('Source configuration is explicit and validates repository syntax + Ed25519 key',()=>{const f=path.join(tmp,'config.json'),pub=path.join(tmp,'pub.pem');fs.writeFileSync(f,JSON.stringify({repository:null,publicKey:'',schema:1}));fs.writeFileSync(pub,config.publicKey);const c=P.configure('https://github.com/test-owner/test-project',pub,f);assert.deepEqual(c.repository,config.repository);assert.equal(c.schema,1);assert.throws(()=>P.configure('https://evil.example/owner/repo',pub,f));});
const component={id:'ytdlp',version:'2026.08.19',minimumVersion:'2.8.0',format:'exe',license:'GPL-3.0-or-later (PyInstaller executable)',sourceURL:'https://github.com/yt-dlp/yt-dlp/releases/tag/2026.08.19',file:{url:'https://github.com/yt-dlp/yt-dlp/releases/download/2026.08.19/yt-dlp.exe',sha256:'a'.repeat(64),size:123}};
test('Component publishing requires source, license, compatibility and sequence before approval',()=>{for(const c of [{...component,license:''},{...component,sourceURL:''},{...component,minimumVersion:''},{...component,format:'zip'}])assert.throws(()=>P.components({config,key:keys.privateKey,catalog:{channel:'stable',sequence:1,components:[c]}}));assert.throws(()=>P.components({config,key:keys.privateKey,catalog:{channel:'stable',sequence:0,components:[component]}}));const m=S.verifyEnvelope(P.components({config,key:keys.privateKey,catalog:{channel:'stable',sequence:1,components:[component]}}),config);assert.equal(m.sequence,1);assert.equal(m.components[0].license,component.license);});
test('Publishing option parser rejects missing/ambiguous options',()=>{assert.deepEqual(P.options(['--out','dist','--version','2.8.1']),{out:'dist',version:'2.8.1'});assert.throws(()=>P.options(['--out']));assert.throws(()=>P.options(['--out','--version','1']));});
