'use strict';
const test=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const M=require('../app/shared/online-search'),P=require('../app/online/providers');
const {createHTTP,allowedURL,fail}=require('../app/online/http');
const {createSearchService,Gate}=require('../app/online/service');
const {createExtractor,proxyArgument}=require('../app/online/extractor');
const {DiscoveryStore,recommend}=require('../app/discovery/store');
const T=require('../app/updates/transport');
const {harness,trackFile}=require('./main-harness');
const url=(id=1)=>`https://www.youtube.com/watch?v=test_${String(id).padStart(6,'0')}`;
const item=(id=1,extra={})=>M.normalizeItem({url:url(id),title:'Красный флаг',artist:'Morgenstern',duration:146,...extra},extra.provider||'youtube',id);
const delay=ms=>new Promise(r=>setTimeout(r,ms));

test('290 source defaults contain six enabled sources with music first',()=>{const p=M.preferences();A.deepEqual(p.enabled,M.IDS);A.equal(p.order[0],'ytmusic');A.equal(p.autoSearch,true);A.equal(p.hideUnavailable,true);});
test('290 malformed preference data is normalized, empty enabled remains empty',()=>{A.equal(M.preferences(null).order.length,6);const p=M.preferences({order:['evil','soundcloud','soundcloud'],enabled:[]});A.equal(p.order[0],'soundcloud');A.equal(p.order.length,6);A.deepEqual(p.enabled,[]);});
test('290 query fields and quoted phrases do not leak operators to providers',()=>{const q=M.parseQuery('artist:"Morgenstern" track:"Красный флаг" album:Test');A.deepEqual(q.fields,{artist:'Morgenstern',track:'Красный флаг',album:'Test'});A.ok(!q.effective.includes('artist:'));A.equal(q.valid,true);});
test('290 explicit filter wins over query operator; free phrase retained',()=>{const q=M.parseQuery('artist:A "red flag"',{artist:'B'});A.equal(q.fields.artist,'B');A.deepEqual(q.phrases,['red flag']);});
test('290 normalization covers accents, Cyrillic case and yo',()=>{A.equal(M.fold('ЁЖИК, Café!'),'ежик cafe');A.equal(M.fold(' КРАСНЫЙ   флаг '),'красныи флаг');A.equal(M.text('\u0000hello\nworld'),'hello world');});
test('290 one character is not dispatched and long input is bounded',()=>{A.equal(M.parseQuery('a').valid,false);A.ok(M.parseQuery('x'.repeat(1000)).effective.length<=300);});
for(const u of ['https://youtu.be/test_000001?t=3','https://music.youtube.com/watch?v=test_000001&list=123','https://www.youtube.com/shorts/test_000001'])test('290 dedup equivalent YouTube URL '+u,()=>A.equal(M.canonicalURL(u),M.canonicalURL(url(1))));
test('290 canonical URL discards tracking but not file identifiers',()=>{A.equal(M.canonicalURL('https://artist.bandcamp.com/track/test?utm_source=x&from=search'),'https://artist.bandcamp.com/track/test');A.notEqual(M.canonicalURL('https://archive.org/details/id/a.mp3'),M.canonicalURL('https://archive.org/details/id/b.mp3'));});
for(const u of ['file:///etc/passwd','javascript:alert(1)','https://user:secret@youtube.com/watch?v=test_000001','http://127.0.0.1/a','https://evil.com/watch?v=test_000001'])test('290 untrusted provider result URL rejected '+u,()=>A.equal(M.normalizeItem({title:'x',url:u},'youtube'),null));
test('290 exact lower priority result beats irrelevant highest priority source',()=>{const exact=item(1,{provider:'youtube'}),noise=item(2,{provider:'ytmusic',title:'Completely unrelated',artist:'Other'});A.equal(M.rank([noise,exact],'Красный флаг')[0].key,exact.key);});
test('290 source priority chooses one canonical duplicate and changes instantly',()=>{const y=item(1),m=item(1,{provider:'ytmusic',url:'https://music.youtube.com/watch?v=test_000001'});A.equal(M.rank([y,m],'Красный флаг')[0].provider,'ytmusic');A.equal(M.rank([y,m],'Красный флаг',{order:['youtube']})[0].provider,'youtube');});
test('290 unavailable preference only hides blocked, never unverified/preview',()=>{const list=['unknown','available','preview','blocked'].map((state,i)=>item(i,{availability:{state}}));A.equal(M.rank(list,'Красный флаг').length,3);A.equal(M.rank(list,'Красный флаг',{hideUnavailable:false}).length,4);});
for(const [f,yes,no] of [['short',239,240],['medium',240,239],['long',601,600]])test('290 duration filter '+f,()=>{const q=M.parseQuery('red',{duration:f});A.equal(M.matches(item(1,{duration:yes}),q),true);A.equal(M.matches(item(1,{duration:no}),q),false);A.equal(M.matches(item(1,{duration:0}),q),true);});
for(const [title,variant] of [['Песня (ремикс)','remix'],['Трек кавер','cover'],['Song Live','live'],['Song instrumental','instrumental'],['Song','original']])test('290 version identification '+title,()=>A.equal(M.variant({title}),variant));
test('290 missing album is not falsely excluded; known mismatched album is',()=>{const q=M.parseQuery('test',{album:'Wanted'});A.equal(M.matches(item(),q),true);A.equal(M.matches(item(1,{album:'Wrong'}),q),false);});
test('290 artist field handles title-embedded artist and transliteration',()=>{A.equal(M.matches(item(1,{artist:'Channel',title:'Morgenstern - Red Flag'}),M.parseQuery('',{artist:'Morgenstern'})),true);A.equal(M.matches(item(1,{title:'Krasnyy flag'}),M.parseQuery('',{track:'Красный флаг'})),true);});
for(const [message,code] of [['HTTP Error 403: Forbidden','SEARCH_ACCESS'],['HTTP 429 Too Many Requests','SEARCH_RATE_LIMIT'],['FAILED HTTP REQUEST','SEARCH_NETWORK'],['Sign in to confirm you are not a bot','SEARCH_SIGN_IN'],['certificate verify failed','SEARCH_TLS'],['Connection timed out','SEARCH_TIMEOUT'],['Video removed by the uploader','SEARCH_REMOVED'],['This video is DRM protected','SEARCH_DRM'],['No DRM protection found','SEARCH_NETWORK'],['This video is not DRM protected','SEARCH_NETWORK']])test('290 conservative error classification '+message,()=>A.equal(M.classifyError(new Error(message)).code,code));
test('290 format checks prefer clear audio even if other formats are DRM',()=>A.equal(M.availabilityFromMetadata({has_drm:true,formats:[{acodec:'aac',has_drm:true,url:'https://x.test/a'},{acodec:'opus',has_drm:false,url:'https://x.test/b'}]}).state,'available'));
test('290 only explicit DRM formats blocks; absent formats stay unknown',()=>{A.equal(M.availabilityFromMetadata({formats:[{acodec:'aac',has_drm:true,url:'https://x/a'}]}).state,'blocked');A.equal(M.availabilityFromMetadata({formats:[]}).state,'unknown');A.equal(M.availabilityFromMetadata({availability:'private'}).state,'unknown');});
test('290 preview-only format stays visible and honestly labeled',()=>A.equal(M.availabilityFromMetadata({formats:[{acodec:'mp3',format_id:'http-preview',url:'https://x/a'}]}).state,'preview'));

test('290 HTML JSON reader ignores quoted braces and never executes scripts',()=>{A.deepEqual(P.assigned('evil(); ytInitialData = {"a":"}\\\"","b":[1]};throw 0','ytInitialData\\s*=\\s*'),{a:'}"',b:[1]});A.equal(P.readJSONAt('{bad}',0),null);});
test('290 YouTube config uses page client version, not a stale hardcoded one',()=>{const c=P.youtubeConfig('ytcfg.set({"INNERTUBE_CLIENT_VERSION":"future","INNERTUBE_API_KEY":"public","INNERTUBE_CONTEXT":{"client":{"clientName":"WEB_REMIX","clientVersion":"future","visitorData":"visitor"}}});',true);A.equal(c.context.client.clientVersion,'future');A.equal(c.context.client.clientName,'WEB_REMIX');A.equal(c.key,'public');});
const videoData={contents:{itemSectionRenderer:{contents:[{videoRenderer:{videoId:'test_000001',title:{runs:[{text:'Song'}]},ownerText:{runs:[{text:'Artist'}]},lengthText:{simpleText:'3:12'},thumbnail:{thumbnails:[{url:'https://i.ytimg.com/test.jpg',width:120}]}}}]}},onResponseReceivedCommands:[{appendContinuationItemsAction:{continuationItems:[{continuationItemRenderer:{continuationEndpoint:{continuationCommand:{token:'next-token'}}}}]}}]};
test('290 YouTube parses metadata and continuation independently of downloader',()=>{const p=P.parseYouTube(videoData);A.equal(p.items[0].duration,192);A.equal(p.items[0].artist,'Artist');A.equal(p.next,'next-token');});
test('290 music-only results carry artist, album and duration',()=>{const p=P.parseYouTube({contents:{musicShelfRenderer:{contents:[{musicResponsiveListItemRenderer:{playlistItemData:{videoId:'test_000001'},flexColumns:[{musicResponsiveListItemFlexColumnRenderer:{text:{runs:[{text:'Song'}]}}},{musicResponsiveListItemFlexColumnRenderer:{text:{runs:[{text:'Artist',navigationEndpoint:{browseEndpoint:{browseId:'UC123'}}},{text:' • '},{text:'Album',navigationEndpoint:{browseEndpoint:{browseId:'MPRE123'}}},{text:'3:15'}]}}}]}}]}}},true);A.deepEqual([p.items[0].title,p.items[0].artist,p.items[0].album,p.items[0].duration],['Song','Artist','Album',195]);});
test('290 structural provider change reports adapter error, not empty success',()=>{A.throws(()=>P.parseYouTube({wrong:true}),{code:'SEARCH_ADAPTER'});A.throws(()=>P.parseBandcamp('<html>blocked</html>'),{code:'SEARCH_ADAPTER'});A.throws(()=>P.parseNewgrounds('<html>blocked</html>'),{code:'SEARCH_ADAPTER'});});
test('290 Bandcamp search HTML is sanitized, title/artist retained',()=>{const data=P.parseBandcamp('<ul class="search-results"><li class="searchresult"><div class="heading"><a href="https://artist.bandcamp.com/track/a?from=search">A &amp; B</a></div><div class="subhead">by Artist</div><img src="https://f4.bcbits.com/img/a.jpg"></li></ul>');A.equal(data[0].title,'A & B');A.equal(data[0].artist,'Artist');A.equal(data[0].url,'https://artist.bandcamp.com/track/a');});
test('290 Newgrounds audio links, metadata, and next HTML page',()=>{const html='<a class="item-audiosubmission" href="/audio/listen/12345"><h4>Moon &amp; Sun</h4><span class="author">Artist</span><span>3:11</span></a><a href="?page=2">Next</a>';const data=P.parseNewgrounds(html);A.equal(data[0].url,'https://www.newgrounds.com/audio/listen/12345');A.equal(data[0].title,'Moon & Sun');A.equal(data[0].duration,191);A.equal(P.nextHTMLPage(html,1),2);A.equal(P.nextHTMLPage(html,2),null);});
for(const [protocol,state] of [['hls','unknown'],['progressive','unknown'],['ctr-hls','blocked'],['cbc-hls','blocked']])test('290 SoundCloud protocol '+protocol,()=>{A.equal(P.soundcloudItem({media:{transcodings:[{format:{protocol}}]}}).availability.state,state);});
test('290 SoundCloud downloadable original and mixed clear formats prevent DRM hiding',()=>{A.equal(P.soundcloudItem({downloadable:true,media:{transcodings:[{format:{protocol:'ctr-hls'}}]}}).availability.state,'unknown');A.equal(P.soundcloudItem({media:{transcodings:[{format:{protocol:'ctr-hls'}},{format:{protocol:'hls'}}]}}).availability.state,'unknown');});
test('290 Archive selects individual audio, avoids derivatives and private files',()=>{const x=P.archiveFiles({metadata:{creator:['A','B'],title:'Album'},files:[{name:'one.flac',length:'3:00'},{name:'one.mp3',original:'one.flac',length:'3:00'},{name:'two.wav'},{name:'secret.mp3',private:'true'},{name:'cover.jpg'}]},'album');A.equal(x.length,2);A.ok(x[0].url.endsWith('/one.flac'));A.equal(x[0].artist,'A, B');});
test('290 Archive pagination retains a large album file offset',async()=>{const calls=[],a=P.createProviders({json:async u=>{calls.push(u);return u.includes('advancedsearch')?{response:{numFound:1,docs:[{identifier:'id'}]}}:{metadata:{creator:'Artist'},files:Array.from({length:60},(_,i)=>({name:`song-${i}.mp3`}))};}});const first=await a.archive({query:'song'}),second=await a.archive({query:'song',cursor:first.cursor}),third=await a.archive({query:'song',cursor:second.cursor});A.equal(first.items.length,24);A.equal(second.items.length,24);A.equal(third.items.length,12);A.equal(third.cursor,null);A.equal(new Set([...first.items,...second.items,...third.items].map(x=>x.url)).size,60);A.equal(calls.length,2);});

test('290 transport permits only configured public source hosts',()=>{A.equal(allowedURL('https://music.youtube.com/').hostname,'music.youtube.com');for(const u of ['http://youtube.com','https://127.0.0.1','https://user:password@youtube.com','https://youtube.com:444/','file:///tmp/a'])A.throws(()=>allowedURL(u));});
test('290 transport rejects redirects to internal or unlisted hosts before fetching',async()=>{const calls=[];const h=createHTTP(async u=>{calls.push(u);return new Response(null,{status:302,headers:{location:'https://127.0.0.1/secret'}});});await A.rejects(h.text('https://www.youtube.com/'),{code:'SEARCH_BAD_URL'});A.equal(calls.length,1);});
test('290 consent redirects are sign-in errors, not unsupported pages',async()=>{const h=createHTTP(async()=>new Response(null,{status:302,headers:{location:'https://consent.youtube.com/m'}}));await A.rejects(h.text('https://www.youtube.com/'),{code:'SEARCH_SIGN_IN'});});
test('290 response bounds apply to streamed bodies without content-length',async()=>{const h=createHTTP(async()=>new Response('123456789'));await A.rejects(h.text('https://www.youtube.com/',{maxBytes:4}),{code:'SEARCH_RESPONSE_LIMIT'});});
test('290 429 respects Retry-After and is not retried in a storm',async()=>{let n=0;const h=createHTTP(async()=>{n++;return new Response('slow',{status:429,headers:{'retry-after':'120'}});});await A.rejects(h.text('https://www.youtube.com/'),e=>e.code==='SEARCH_RATE_LIMIT'&&e.retryAfter===120);A.equal(n,1);});
test('290 transient 503 retries once, then succeeds',async()=>{let n=0;const h=createHTTP(async()=>++n===1?new Response('retry',{status:503}):new Response('{"ok":true}'));A.deepEqual(await h.json('https://www.youtube.com/'),{ok:true});A.equal(n,2);});
test('290 metadata fetch never sends cookies and uses manual redirect validation',async()=>{const h=createHTTP(async(u,o)=>{A.equal(o.credentials,'omit');A.equal(o.redirect,'manual');A.ok(!o.headers.Cookie);return new Response('ok');});A.equal(await h.text('https://www.youtube.com/'),'ok');});
test('290 aborted metadata work really aborts fetch',async()=>{let aborted=false;const controller=new AbortController(),h=createHTTP((u,o)=>new Promise((resolve,reject)=>o.signal.addEventListener('abort',()=>{aborted=true;reject(new DOMException('aborted','AbortError'));})));const p=h.text('https://www.youtube.com/',{signal:controller.signal});controller.abort();await A.rejects(p,{code:'SEARCH_CANCELLED'});A.equal(aborted,true);});

test('290 service caches first pages and issues opaque, bound continuation tokens',async()=>{let calls=0;const service=createSearchService({providers:{youtube:async c=>{calls++;return {items:[{url:url(c.cursor?.n||1),title:'Song'}],cursor:c.cursor?null:{n:2}};}}});const first=await service.command({type:'page',provider:'youtube',query:'Song'});A.equal(first.items.length,1);A.match(first.cursor,/^[a-f0-9]{36}$/);A.equal((await service.command({type:'page',provider:'youtube',query:'Song'})).cached,true);A.equal(calls,1);const next=await service.command({type:'page',provider:'youtube',query:'Song',cursor:first.cursor});A.equal(next.items[0].key,M.canonicalURL(url(2)));A.equal(next.cursor,null);A.equal((await service.command({type:'page',provider:'youtube',query:'Other',cursor:first.cursor})).error.code,'SEARCH_BAD_CURSOR');service.dispose();});
test('290 service de-duplicates successive pages and stops repeating source cursors',async()=>{const s=createSearchService({providers:{youtube:async c=>({items:[{url:url(1),title:'a'},{url:url(c.cursor?2:1),title:'b'}],cursor:{page:1}})}});const a=await s.command({type:'page',provider:'youtube',query:'aa'}),b=await s.command({type:'page',provider:'youtube',query:'aa',cursor:a.cursor});A.equal(a.items.length,1);A.equal(b.items.length,1);A.equal(b.cursor,null);s.dispose();});
test('290 one broken source does not reject another; search does not invoke extraction',async()=>{let extracted=0;const s=createSearchService({providers:{youtube:async()=>{throw fail('SEARCH_NETWORK');},soundcloud:async()=>({items:[{url:'https://soundcloud.com/artist/song',title:'Song'}]})},extractInfo:()=>extracted++});const [bad,good]=await Promise.all(['youtube','soundcloud'].map(provider=>s.command({type:'page',provider,query:'Song'})));A.equal(bad.ok,false);A.equal(good.items.length,1);A.equal(extracted,0);s.dispose();});
test('290 search concurrency never exceeds three and cancellation clears queued work',async()=>{let active=0,max=0,aborted=0;const adapter=({signal})=>new Promise((resolve,reject)=>{active++;max=Math.max(max,active);signal.addEventListener('abort',()=>{active--;aborted++;reject(fail('SEARCH_CANCELLED'));},{once:true});});const s=createSearchService({providers:Object.fromEntries(M.IDS.map(id=>[id,adapter]))});const pending=M.IDS.map(provider=>s.command({type:'page',provider,query:'song',requestId:'q'}));await delay(10);A.equal(max,3);await s.command({type:'cancel',requestId:'q'});const r=await Promise.all(pending);A.equal(r.filter(x=>x.error?.code==='SEARCH_CANCELLED').length,6);A.equal(aborted,3);A.equal(s.stats().active,0);A.equal(s.stats().requests,0);s.dispose();});
test('290 rate limit cooldown blocks repeated user retries without network hits',async()=>{let calls=0,now=100000;const s=createSearchService({clock:()=>now,providers:{youtube:async()=>{calls++;throw fail('SEARCH_RATE_LIMIT',{retryAfter:120});}}});await s.command({type:'page',provider:'youtube',query:'song'});await s.command({type:'page',provider:'youtube',query:'song',retry:true});A.equal(calls,1);now+=121000;await s.command({type:'page',provider:'youtube',query:'song',retry:true});A.equal(calls,2);s.dispose();});
test('290 availability can inspect only a known result and never installs a tool',async()=>{let inspected=0;const s=createSearchService({providers:{youtube:async()=>({items:[{url:url(),title:'Song'}]})},extractInfo:async(u,o)=>{inspected++;A.equal(o.probe,true);return null;}});A.equal((await s.command({type:'probe',url:'https://127.0.0.1/'})).error.code,'SEARCH_BAD_URL');await s.command({type:'page',provider:'youtube',query:'song'});const r=await s.command({type:'probe',url:url()});A.equal(r.availability.state,'unknown');A.equal(r.availability.reason,'SEARCH_TOOL');A.equal(inspected,1);s.dispose();});
for(const [message,state] of [['HTTP 403','unknown'],['FAILED HTTP REQUEST','unknown'],['This video is DRM protected','blocked'],['This video was removed','blocked']])test('290 result probe '+message,async()=>{const s=createSearchService({providers:{youtube:async()=>({items:[{url:url(),title:'Song'}]})},extractInfo:async()=>{throw Error(message);}});await s.command({type:'page',provider:'youtube',query:'song'});A.equal((await s.command({type:'probe',url:url()})).availability.state,state);s.dispose();});
test('290 availability and full metadata caches expire and stay bounded',async()=>{let now=100000,calls=0;const s=createSearchService({clock:()=>now,providers:{youtube:async()=>({items:[{url:url(),title:'Song'}]})},extractInfo:async()=>{calls++;return {formats:[{acodec:'aac',url:'https://stream.example/a'}]};}});await s.command({type:'page',provider:'youtube',query:'song'});await s.command({type:'probe',url:url()});await s.command({type:'probe',url:url()});A.equal(calls,1);A.ok(s.cachedInfo(url()));now+=61000;A.equal(s.cachedInfo(url()),null);now+=121000;await s.command({type:'probe',url:url()});A.equal(calls,2);s.dispose();});
test('290 fallback only handles parser changes, never bypasses 403 or 429',async()=>{let calls=0;const fallback=async()=>{calls++;return {items:[{url:url(),title:'Song'}]};};for(const code of ['SEARCH_ACCESS','SEARCH_RATE_LIMIT','SEARCH_ADAPTER']){const s=createSearchService({providers:{youtube:async()=>{throw fail(code);}},fallback});const r=await s.command({type:'page',provider:'youtube',query:'song'});A.equal(r.ok,code==='SEARCH_ADAPTER');s.dispose();}A.equal(calls,1);});

test('290 extractor uses bundled runtime, explicit configuration isolation and system proxy',async()=>{const calls=[];const e=createExtractor({resolve:()=>'/tool/yt-dlp.exe',provision:async()=>{throw Error('must not install');},runtimePath:'/app/PulseDeck.exe',resolveProxy:async()=> 'PROXY proxy.example:8080; DIRECT',run:async(exe,args,opts)=>{calls.push({exe,args,opts});return {stdout:exe.includes('PulseDeck')?'24.0.0':JSON.stringify({title:'Song'})};}});await e.inspect(url(),{probe:true});const call=calls.at(-1);A.ok(call.args.includes('--ignore-config'));A.ok(call.args.includes('node:/app/PulseDeck.exe'));A.ok(call.args.includes('http://proxy.example:8080'));A.equal(call.opts.env.ELECTRON_RUN_AS_NODE,'1');A.ok(!call.args.includes('--no-check-certificates'));A.equal(call.args[call.args.indexOf('--retries')+1],'0');});
test('290 no-tool fast check does not provision downloader or start runtime',async()=>{const e=createExtractor({resolve:()=>'',provision:()=>{throw Error('no');},run:()=>{throw Error('no');}});A.equal(await e.inspect(url(),{probe:true}),null);});
test('290 extractor first explicit preview may provision, flat fallback does not',async()=>{let installs=0;const e=createExtractor({resolve:()=>'',provision:async()=>{installs++;return '/tool';},runtimePath:'node',run:async(exe)=>({stdout:exe==='node'?'22.16.0':'{}'})});A.equal(await e.fallback({provider:'youtube',query:'song'}),null);await e.inspect(url());A.equal(installs,1);});
test('290 extractor pagination uses requested range and music songs endpoint',async()=>{const calls=[];const e=createExtractor({resolve:()=>'/tool',runtimePath:'node',run:async(exe,args)=>{calls.push(args);return {stdout:exe==='node'?'22.16.0':JSON.stringify({entries:[]})};}});await e.fallback({provider:'ytmusic',query:'a & b',cursor:{extractorPage:3}});const args=calls.at(-1);A.equal(args[args.indexOf('--playlist-start')+1],'51');A.equal(args[args.indexOf('--playlist-end')+1],'75');A.ok(args.at(-1).endsWith('a%20%26%20b#songs'));});
for(const [input,want] of [['DIRECT',''],['PROXY local:8080; DIRECT','http://local:8080'],['SOCKS5 proxy:1080','socks5://proxy:1080'],['PROXY user:password@evil:80',''],['DIRECT; PROXY x:1','']])test('290 proxy parsing '+input,()=>A.equal(proxyArgument(input),want));

test('290 component Chromium download retains SHA verification and credentials omission',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pd290-net-')),body=Buffer.from('test binary data'),file={url:'https://github.com/yt-dlp/yt-dlp/releases/download/2026.08.19/yt-dlp.exe',size:body.length,sha256:crypto.createHash('sha256').update(body).digest('hex')};try{const transport=T.forFetch(async(u,o)=>{A.equal(o.credentials,'omit');A.equal(o.redirect,'manual');return new Response(body);});const dest=path.join(dir,'tool');await transport.download(file,dest,{config:{},component:true});A.deepEqual(fs.readFileSync(dest),body);await A.rejects(transport.download({...file,sha256:'a'.repeat(64)},path.join(dir,'bad'),{config:{},component:true}),{code:'UPDATE_HASH_MISMATCH'});A.equal(fs.existsSync(path.join(dir,'bad.part')),false);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('290 component Chromium redirect does not relax trusted host rules',async()=>{const t=T.forFetch(async()=>new Response(null,{status:302,headers:{location:'https://127.0.0.1/tool'}}));await A.rejects(t.jsonBytes('https://github.com/a',{validate:u=>{if(new URL(u).hostname!=='github.com')throw fail('UPDATE_UNTRUSTED_URL');}}),{code:'UPDATE_UNTRUSTED_URL'});});

function withStore(fn){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pd290-history-'));let now=Date.now();const file=path.join(dir,'history.json'),store=new DiscoveryStore(file,{clock:()=>now});try{return fn({store,file,advance:ms=>now+=ms,now:()=>now});}finally{fs.rmSync(dir,{recursive:true,force:true});}}
const track=(rel,artist='Artist',extra={})=>({id:rel,rel,title:rel,artist,album:'Album',duration:180,...extra});
test('290 local history is opt-in and paused playback never records',()=>withStore(({store,file})=>{A.equal(store.status().enabled,false);A.equal(store.record(track('a'),{seconds:30}).recorded,false);A.equal(fs.existsSync(file),false);store.configure(true);store.record(track('a'),{seconds:20});store.configure(false);store.record(track('b'),{seconds:20});A.equal(store.status().count,1);}));
test('290 private, vault and protected tracks are never recorded',()=>withStore(({store})=>{store.configure(true);for(const flag of ['vaultKey','vaultId','private','protected'])A.equal(store.record(track('x','A',{[flag]:true}),{seconds:20}).recorded,false);A.equal(store.status().count,0);}));
test('290 wall-time budget blocks repeated heartbeats and seek-sized jumps',()=>withStore(({store,advance})=>{store.configure(true);store.record(track('x'),{seconds:10000});store.record(track('x'),{seconds:10000});A.equal(store.data.records.x.seconds,30);advance(5000);store.record(track('x'),{seconds:10000});A.equal(store.data.records.x.seconds,35);}));
test('290 history persists locally, contains no metadata or remote credentials, and clears',()=>withStore(({store,file})=>{store.configure(true);store.record(track('x'),{seconds:20});const data=JSON.parse(fs.readFileSync(file));A.equal(data.records.x.seconds,20);A.ok(!JSON.stringify(data).includes('Artist'));A.equal(new DiscoveryStore(file).status().count,1);store.clear();A.equal(Object.keys(JSON.parse(fs.readFileSync(file)).records).length,0);A.equal(store.status().enabled,true);}));
test('290 retention and record count are bounded',()=>withStore(({store,now})=>{store.data.records=Object.fromEntries(Array.from({length:2100},(_,i)=>['x'+i,{last:now()-i,seconds:30}]));store.data.records.old={last:now()-181*86400000,seconds:99};store.save();A.equal(store.status().count,2000);A.ok(!store.data.records.old);}));
test('290 recommendations favor recently heard artists, diversify, and exclude protected/dismissed tracks',()=>{const now=Date.now(),tracks=[track('heard','A'),track('a1','A'),track('a2','A'),track('a3','A'),track('b1','B'),track('secret','A',{vaultKey:'x'})],records={heard:{seconds:3600,last:now},b1:{seconds:100,last:now-40*86400000}};const rec=recommend(tracks,records,now,['a1']);A.ok(rec.some(x=>x.track.artist==='A'));A.equal(rec.some(x=>x.track.rel==='secret'||x.track.rel==='a1'),false);A.ok(rec.filter(x=>x.track.artist==='A').length<=2);A.equal(rec[0].reason,'DiscoveryBecauseArtist');});
test('290 empty listening history has no invented taste; favorites provide a cold start',()=>{A.deepEqual(recommend([track('a')],{}),[]);A.equal(recommend([track('a','A',{favorite:true})],{})[0].track.rel,'a');});
test('290 main-process search/discovery commands reject foreign windows',async()=>{const h=harness();try{await A.rejects(async()=>h.handlers.get('online:command')({sender:{}},{type:'cancel'}));await A.rejects(async()=>h.handlers.get('discovery:command')({sender:{}},{type:'status'}));A.equal((await h.invoke('discovery:command',{type:'status'})).enabled,false);A.equal((await h.invoke('online:command',{type:'page',provider:'evil',query:'hi'})).ok,false);}finally{h.close();}});
test('290 main resolves history records only from actual public library entries',async()=>{const h=harness();try{trackFile(h,'real.wav','Artist');await h.invoke('discovery:command',{type:'configure',enabled:true});A.equal((await h.invoke('discovery:command',{type:'record',rel:'../secret',seconds:30})).recorded,false);A.equal((await h.invoke('discovery:command',{type:'record',rel:'real.wav',seconds:15})).recorded,true);A.equal((await h.invoke('discovery:command',{type:'status'})).count,1);}finally{h.close();}});
