'use strict';
// Original synthetic lyrics/audio only. These tests exercise production modules.
const test=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const S=require('../app/shared/lyrics-search'),L=require('../app/shared/lyrics'),E=require('../app/shared/lyrics-editor'),O=require('../app/shared/lyrics-operations'),R=require('../app/shared/lyrics-rhythm');
const {LyricsStore}=require('../app/lyrics/store'),{analyzeAudio}=require('../app/lyrics/analyze');const {harness,trackFile,tree}=require('./main-harness');
const t=(name,fn)=>test('268 '+name,fn),doc=lines=>L.normalize({lines}).doc,clone=x=>JSON.parse(JSON.stringify(x));
const demo=()=>doc([{startMs:1000,endMs:4000,segments:[{startMs:1000,text:'Quiet '},{startMs:2000,text:'night '},{startMs:3000,text:'again'}]},{startMs:6000,endMs:8000,text:'We return home'},{startMs:10000,text:'Open windows'}]);
for(const [input,expected] of [
 ['Последняя Любовь (Official Video, 2024)','Последняя Любовь'],['Duality [OFFICIAL VIDEO] [HD]','Duality'],['Ночная волна (Официальный клип, 2024)','Ночная волна'],['Night [1080p] (HQ) [4K]','Night'],['Night (Live)','Night (Live)'],['Night (Acoustic Version)','Night (Acoustic Version)'],['Night (Remix) [HD]','Night (Remix)'],['Night (Part II)','Night (Part II)'],['1984','1984'],['Night (2024 Remaster)','Night (2024 Remaster)'],['Night (slowed + reverb)','Night (slowed + reverb)']])t('title normalization: '+input,()=>A.equal(S.cleanTitle(input),expected));
t('uploader metadata does not win over performer explicitly in the title',()=>{const source={artist:'BUYSELL',title:'Моргенштерн - Повод [HD]'},copy=clone(source),r=S.identity(source);A.equal(r.artist,'Моргенштерн');A.equal(r.title,'Повод');A.equal(r.originalArtist,'BUYSELL');A.equal(r.fromTitle,true);A.deepEqual(source,copy);});
t('Cyrillic / Latin artist variants compare without changing track tags',()=>{A.equal(S.fold('Моргенштерн'),S.fold('MORGENSTERN'));A.equal(S.fold('MORGENSHTERN'),S.fold('MORGENSTERN'));const r=S.identity({artist:'MORGENSTERN',title:'Моргенштерн — Последняя Любовь (Official Video, 2024)'});A.equal(r.title,'Последняя Любовь');A.equal(r.fromTitle,false);});
t('query expansion is bounded, deduplicated and uses several metadata widths',()=>{const p=S.plan('MORGENSTERN','Последння Любовь [HD]');A.ok(p.queries.length<=8);A.equal(p.queries.length,new Set(p.queries.map(x=>JSON.stringify(x))).size);A.equal(p.queries[0].track_name,'Последння Любовь');A.ok(p.queries.some(x=>x.track_name==='Любовь'));A.ok(p.queries.some(x=>x.track_name==='poslednnya lyubov'));A.ok(p.queries.every(q=>q.q||q.track_name));});
t('edit-distance tolerates omitted letters, transpositions, case, script and word order',()=>{for(const [a,b]of [['Последння Любовь','Последняя любовь'],['Dulaity','Duality'],['Night Quiet','Quiet Night'],['Моргенштерн','MORGENSTERN']])A.ok(S.similarity(a,b)>.8,`${a} / ${b}`);});
t('ranking does not prefer unrelated duration-matching title',()=>{const r=S.rank([{id:1,title:'Other universe',artist:'A',duration:210},{id:2,title:'Quiet night',artist:'A',duration:240},{id:3,title:'Quiet night',artist:'A',duration:211}],'A','Quiet nght',210);A.deepEqual(r.map(x=>x.id),[3,2]);A.ok(r[0].approximate);});
t('live/remix mismatch is explicit and lower ranked, duplicate records collapse',()=>{const r=S.rank([{id:1,title:'Night (Live)',artist:'Artist',duration:100},{id:2,title:'Night',artist:'Artist',duration:100},{id:2,title:'Night',artist:'Artist',duration:100}],'Artist','Night',100);A.equal(r.length,2);A.equal(r[0].id,2);A.ok(r[1].variantMismatch);});
t('search input bounds prevent unbounded edit-distance work',()=>{A.ok(S.identity({title:'x'.repeat(10000)}).title.length<=300);A.ok(Number.isFinite(S.similarity('a'.repeat(10000),'b'.repeat(10000))));});
t('all-line shift includes ends and every segment but leaves audio offset untouched',()=>{const d=demo(),before=clone(d),r=O.shift(d,500,{all:true,durationMs:64000});A.deepEqual(r.lines.map(x=>x.startMs),[1500,6500,10500]);A.equal(r.lines[0].endMs,4500);A.equal(r.lines[0].segments[1].startMs,2500);A.equal(r.offsetMs,d.offsetMs);A.deepEqual(d,before);});
t('selected-line shift never touches the current but unselected line',()=>{const d=demo(),r=O.shift(d,-500,{rows:[1],durationMs:64000});A.deepEqual(r.lines[0],d.lines[0]);A.equal(r.lines[1].startMs,5500);A.deepEqual(r.lines[2],d.lines[2]);});
t('selected-word shifts preserve unselected effective timing',()=>{const d=demo(),r=O.shift(d,500,{words:[[0,1]],durationMs:64000});A.deepEqual(r.lines[0].segments.map(x=>x.startMs),[1000,2500,3000]);A.deepEqual(r.lines[1],d.lines[1]);});
t('word group with inherited time retains unselected group even when moved earlier',()=>{const d=doc([{startMs:1000,segments:[{startMs:1000,text:'A B '},{startMs:4000,text:'C'}]}]),r=O.shift(d,-200,{words:[[0,1]],durationMs:9000});A.deepEqual(r.lines[0].segments.map(x=>x.startMs),[1000,800,4000]);A.deepEqual(d.lines[0].segments.map(x=>x.startMs),[1000,4000]);});
t('shift rejects crossing zero or end atomically rather than clamping separate rows',()=>{const d=demo(),original=clone(d);A.throws(()=>O.shift(d,-1001,{all:true,durationMs:64000}),/границы/);A.throws(()=>O.shift(d,54001,{all:true,durationMs:64000}),/границы/);A.deepEqual(d,original);});
t('untimed rows remain untimed during a shift',()=>{const d=doc([{text:'A'},{startMs:3000,text:'B'}]),r=O.shift(d,300,{all:true});A.equal(r.lines[0].startMs,null);A.equal(r.lines[1].startMs,3300);});
t('reorder a row moves its text into timing slots; internal word timing moves with it',()=>{const d=demo(),r=O.moveRows(d,[0],1);A.equal(L.plainLine(r.doc.lines[1]),'Quiet night again');A.equal(r.doc.lines[1].startMs,6000);A.equal(r.doc.lines[1].segments[1].startMs,7000);A.deepEqual(r.rows,[1]);A.doesNotThrow(()=>L.normalize(r.doc));});
t('selected contiguous rows keep their relative order',()=>{const d=demo(),r=O.moveRows(d,[0,1],1);A.deepEqual(r.rows,[1,2]);A.deepEqual(r.doc.lines.map(L.plainLine),['Open windows','Quiet night again','We return home']);A.deepEqual(r.doc.lines.map(x=>x.startMs),[1000,6000,10000]);});
t('word reordering preserves spacing slots, duration and other lines',()=>{const d=demo(),r=O.moveWords(d,[[0,1]],1);A.equal(L.plainLine(r.doc.lines[0]),'Quiet again night');A.deepEqual(r.doc.lines[0].segments.map(x=>x.startMs),[1000,2000,3000]);A.deepEqual(r.words,[[0,2]]);A.deepEqual(r.doc.lines[1],d.lines[1]);});
t('clear all timing does not erase words or theme',()=>{const d=demo(),r=O.clearTimes(d,{all:true});A.deepEqual(r.lines.map(L.plainLine),d.lines.map(L.plainLine));A.ok(r.lines.every(x=>x.startMs==null&&x.endMs==null&&!x.segments));A.deepEqual(r.theme,d.theme);});
t('clear selected word restores inheritance without deleting text',()=>{const d=demo(),r=O.clearTimes(d,{words:[[0,1]]});A.equal(L.plainLine(r.lines[0]),'Quiet night again');A.equal(E.tokens(r.lines[0])[1].startMs,1000);});
t('split line keeps all words and marks no automatic false gap',()=>{const d=demo(),r=O.splitLine(d,0,1);A.equal(r.lines.length,4);A.equal(r.lines[0].suppressGapAfter,true);A.equal(r.lines[1].startMs,2000);A.equal(L.plainLine(r.lines[0])+L.plainLine(r.lines[1]),L.plainLine(d.lines[0]));A.doesNotThrow(()=>L.normalize(r));});
t('explicit chronological repair is stable and keeps untimed positions',()=>{const d={lines:[{startMs:15000,text:'Late'},{startMs:11000,text:'Early'},{text:'Unassigned',startMs:null},{text:'Also late',startMs:15000}]},r=O.sortByTime(d);A.deepEqual(r.lines.map(x=>x.text),['Early','Late','Unassigned','Also late']);A.equal(d.lines[0].text,'Late');});
t('history undo redo invalidates old redo after a new edit',()=>{const h=new O.History(),a=demo(),b=O.shift(a,100,{all:true}),c=O.shift(a,200,{all:true});h.push(a,b);A.deepEqual(h.undo(b),a);A.deepEqual(h.redo(a),b);h.undo(b);h.push(a,c);A.equal(h.redo(c),null);});
t('history bounds count and snapshots are isolated',()=>{const h=new O.History(3),a=demo();for(let i=0;i<10;i++)h.push({...a,offsetMs:i},{...a,offsetMs:i+1});A.equal(h.undoStack.length,3);a.lines[0].segments[0].text='changed';A.notEqual(h.undo({}).lines[0].segments[0].text,'changed');h.clear();A.equal(h.undoStack.length,0);});
t('history sheds old large entries to its memory budget',()=>{const h=new O.History(80,1000);for(let i=0;i<20;i++)h.push({v:'a'.repeat(200),i},{v:'a'.repeat(200),i:i+1});A.ok(h.undoStack.length<=2);});
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pd268-')),music=path.join(dir,'music'),data=path.join(dir,'data');fs.mkdirSync(music);fs.mkdirSync(data);const file=path.join(music,'night.wav');fs.copyFileSync(path.join(__dirname,'fixtures/rhythm-synthetic.wav'),file);const tracks=[{rel:'night.wav',title:'Quiet Night [HD]',artist:'Studio',duration:24}];const store=new LyricsStore({music,data,listPublic:async()=>tracks,getVault:()=>({sessions:new Map()}),ffmpeg:process.env.FFMPEG||'ffmpeg'});return{dir,music,data,file,tracks,store,close(){store.dispose();fs.rmSync(dir,{recursive:true,force:true});}};}
function ftest(name,fn){t(name,async()=>{const f=fixture();try{await fn(f);}finally{f.close();}});}
ftest('appearance-only save persists without creating lyrics and keeps audio identical',async f=>{const before=fs.readFileSync(f.file);const r=await f.store.presentation({rel:'night.wav',theme:{background:'#112233',fontScale:115,paletteSource:'manual'},timing:{offsetMs:300,gapThresholdMs:5000}});A.equal(r.doc,null);const loaded=await f.store.get('night.wav');A.equal(loaded.theme.fontScale,115);A.equal(loaded.theme.paletteSource,'manual');A.equal(loaded.timing.offsetMs,300);A.deepEqual(fs.readFileSync(f.file),before);});
ftest('text saves preserve stored palette despite imported JSON theme',async f=>{const style=L.theme({background:'#734c11',gradientColors:['#734c11','#203342'],paletteSource:'manual'});let r=await f.store.presentation({rel:'night.wav',theme:style});const incoming=demo();incoming.theme=L.theme({background:'#ff0000'});r=await f.store.save({rel:'night.wav',doc:incoming,revision:r.revision});A.deepEqual(r.theme,style);A.deepEqual(r.doc.theme,style);});
ftest('appearance updates never wipe saved words or word timestamps',async f=>{let r=await f.store.save({rel:'night.wav',doc:demo()});const lines=clone(r.doc.lines);r=await f.store.presentation({rel:'night.wav',revision:r.revision,theme:{fontScale:125},timing:{offsetMs:400}});A.deepEqual(r.doc.lines,lines);A.equal(r.doc.offsetMs,400);});
ftest('stale presentation and stale text revisions fail without overwriting',async f=>{const first=await f.store.presentation({rel:'night.wav',theme:{fontScale:125}});await A.rejects(f.store.presentation({rel:'night.wav',theme:{fontScale:90},revision:null}),/изменено/);await A.rejects(f.store.save({rel:'night.wav',doc:demo(),revision:null}),/изменён/);A.equal((await f.store.get('night.wav')).revision,first.revision);});
ftest('delete is a lyrics-only tombstone; sidecar and embedded lyrics cannot resurrect',async f=>{fs.writeFileSync(f.file+'.lrc','[00:01]Nearby text');f.store.embedded=async()=>'Embedded words';let r=await f.store.get('night.wav');A.ok(r.doc);r=await f.store.presentation({rel:'night.wav',theme:{background:'#554433'}});r=await f.store.remove({rel:'night.wav',revision:r.revision});const loaded=await f.store.get('night.wav');A.equal(loaded.doc,null);A.equal(loaded.theme.background,'#554433');A.equal(loaded.suppressed,true);A.ok(fs.existsSync(f.file+'.lrc'));r=await f.store.save({rel:'night.wav',doc:demo(),revision:r.revision});A.ok((await f.store.get('night.wav')).doc);A.ok(!r.suppressed);});
ftest('no remote search or PCM analysis while simply getting lyrics',async f=>{let calls=0;f.store.fetchJson=()=>{calls++;};await f.store.get('night.wav');A.equal(calls,0);A.equal(f.store.analyses.size,0);});
ftest('network search only after consent; query expansion recovers a one-word typo',async f=>{const requests=[];f.store.fetchJson=async url=>{requests.push(String(url));if(url.searchParams.get('track_name')==='Quiet')return [{id:1,trackName:'Quiet Night',artistName:'Studio',duration:24,plainLyrics:'Example text'}];return [];};await A.rejects(f.store.search({rel:'night.wav',title:'Quiet Ngith'}),/согласие/);A.equal(requests.length,0);const result=await f.store.search({rel:'night.wav',artist:'Studio',title:'Quiet Ngith [HD]',consent:true});A.equal(result[0].id,1);A.ok(result[0].approximate);A.ok(requests.length<=8);for(const url of requests){A.equal(new URL(url).origin,'https://lrclib.net');A.ok(!url.includes(f.dir));}});
ftest('remote failure is not multiplied into eight retry requests',async f=>{let count=0;f.store.fetchJson=async()=>{count++;throw Error('429: wait');};await A.rejects(f.store.search({rel:'night.wav',consent:true}),/429/);A.equal(count,1);});
ftest('partial usable results survive later query failure and are labelled',async f=>{let count=0;f.store.fetchJson=async()=>{if(count++)throw Error('offline');return [{id:4,trackName:'Quiet Night',artistName:'Someone',duration:12,plainLyrics:'Other version'}];};const result=await f.store.search({rel:'night.wav',consent:true});A.ok(result[0].partial);A.equal(count,2);});
ftest('new search aborts previous request without leaking old results',async f=>{let entered;f.store.fetchJson=(url,{signal})=>new Promise((resolve,reject)=>{entered=resolve;signal.addEventListener('abort',()=>reject(Error('aborted')),{once:true});});const one=f.store.search({rel:'night.wav',consent:true});while(!entered)await new Promise(r=>setTimeout(r,1));const pending=A.rejects(one,/отменён/);f.store.cancelSearches();await pending;A.equal(f.store.searches.size,0);});
ftest('real ffmpeg-worker analysis creates bounded features, silence regions and no files',async f=>{const before=tree(f.music),progress=[];f.store.analysisProgress=p=>progress.push(p.percent);const result=await f.store.analyze({rel:'night.wav'});A.ok(result.durationMs>=23900&&result.durationMs<=24100);A.ok(result.regions.length>=2);A.ok(result.onsets.length>=10);A.ok(result.wave.length<=1200);A.ok(result.activity.length<=90000);A.deepEqual(tree(f.music),before);A.ok(progress.length>0);A.ok(progress.every(x=>x>=0&&x<=99));A.deepEqual(await f.store.analyze({rel:'night.wav'}),result);});
ftest('audio analysis cancel leaves the file untouched and queue drained',async f=>{const before=tree(f.music);const pending=f.store.analyze({rel:'night.wav'});while(!f.store.analyses.size)await new Promise(r=>setTimeout(r,1));const check=A.rejects(pending,/отменён/);f.store.cancelAnalysis();await check;A.deepEqual(tree(f.music),before);A.equal(f.store.analyses.size,0);});
t('analysis rejects missing executable and undecodable input gracefully',async()=>{await A.rejects(analyzeAudio(__filename,{ffmpeg:'missing-pulsedeck-ffmpeg'}),/FFmpeg/);await A.rejects(analyzeAudio(__filename,{ffmpeg:process.env.FFMPEG||'ffmpeg'}),/декодировать/);});
t('analysis rejects duration limit and already-aborted work before launching',async()=>{await A.rejects(analyzeAudio(__filename,{durationMs:1800001}),/30 минут/);const ac=new AbortController();ac.abort();await A.rejects(analyzeAudio(__filename,{signal:ac.signal}),/отменён/);});
t('PCM extractor detects silence rather than inventing lyric marks',()=>{const e=new R.Extractor();e.feed(Buffer.alloc(16000*4));A.throws(()=>e.finish(),/тишина/);});
const analysis=()=>({durationMs:24000,hopMs:20,activity:Array.from({length:1200},(_,i)=>(i>=100&&i<500)||(i>=700&&i<1100)?1:0),onsets:Array.from({length:44},(_,i)=>2000+i*500)});
t('rhythm draft only uses audible regions and leaves ends unknown',()=>{const d=doc(['Quiet water','Open windows','Night returns','Morning again'].map(text=>({text}))),before=clone(d),r=R.draft(d,analysis());A.equal(r.count,4);A.ok(r.doc.lines.every(x=>(x.startMs>=2000&&x.startMs<10000)||(x.startMs>=14000&&x.startMs<22000)));A.ok(r.doc.lines.every(x=>x.endMs===null));A.deepEqual(d,before);A.deepEqual(r.doc.systemNotes,['AcousticDraftNote']);A.equal(L.notes(r.doc)[0],require('../app/i18n').t('AcousticDraftNote'));A.doesNotThrow(()=>L.normalize(r.doc));});
t('rhythm draft preserves known anchor and ignores explicitly marked instrumental interval',()=>{const d=doc([{text:'Before'},{text:'Anchor',startMs:6000},{text:'♪',startMs:10000,endMs:16000},{text:'After'},{text:'Last'}]);const r=R.draft(d,analysis());A.equal(r.doc.lines[1].startMs,6000);A.ok(r.doc.lines.slice(3).every(x=>x.startMs>=16000));A.equal(r.doc.lines[2].endMs,16000);});
t('rhythm draft honours positive or negative display offsets on the media clock',()=>{for(const offset of [-700,900]){const d=doc([{text:'One'},{text:'Two'}]);d.offsetMs=offset;const r=R.draft(d,analysis());A.equal(r.doc.offsetMs,offset);A.equal(r.doc.lines[0].startMs+offset,2000);A.ok(r.doc.lines.every(x=>x.startMs>=0));}});
t('no approximate overwrite of existing complete synchronization without opt-in',()=>{A.throws(()=>R.draft(demo(),analysis()),/уже размечены/);const r=R.draft(demo(),analysis(),{keepExisting:false});A.equal(r.count,3);});
t('too small/empty analysis range fails without changing the draft',()=>{const d=doc([{text:'One'},{text:'Two'}]),before=clone(d);A.throws(()=>R.draft(d,analysis(),{startMs:2000,endMs:2200}),/длинный/);A.throws(()=>R.draft(d,analysis(),{startMs:11000,endMs:12000}),/мало звука/);A.deepEqual(d,before);});
t('private appearance, deletion and acoustic features respect the existing vault boundary',async()=>{const h=harness();try{const f=trackFile(h,'private.wav','Singer',{duration:24});fs.copyFileSync(path.join(__dirname,'fixtures/rhythm-synthetic.wav'),f);h.api.saveSettings({customCategories:[{id:'custom:a',name:'Vault',tracks:['private.wav']}]},{skipEffects:true});const cmd=c=>h.invoke('lyrics:command',c),v=c=>h.invoke('vault:command',c);let r=await cmd({type:'save',rel:'private.wav',doc:demo()});await v({type:'protect',key:'custom:a',password:'strong test phrase',name:'Vault'});const u=await v({type:'unlock',key:'custom:a',password:'strong test phrase'}),rel=u.tracks[0].rel;const store=h.api.getLyrics();store.ffmpeg=process.env.FFMPEG||'ffmpeg';r=await cmd({type:'get',rel});r=await cmd({type:'presentation',rel,revision:r.revision,theme:{fontScale:120,paletteSource:'manual'},timing:{offsetMs:200}});A.equal(r.doc.lines.length,3);const before=tree(h.api.paths.music);const features=await store.analyze({rel});A.ok(features.regions.length>=2);A.equal(store.analysisCache.size,0);A.deepEqual(tree(h.api.paths.music),before);r=await cmd({type:'remove',rel,revision:r.revision});A.equal((await cmd({type:'get',rel})).doc,null);const cipher=fs.readdirSync(path.join(h.api.paths.music,'.pulsedeck-lyrics')).map(n=>fs.readFileSync(path.join(h.api.paths.music,'.pulsedeck-lyrics',n),'utf8')).join('');A.ok(!cipher.includes('Quiet')&&!cipher.includes('fontScale'));await v({type:'lock'});await A.rejects(cmd({type:'get',rel}));await A.rejects(store.analyze({rel}));}finally{h.close();}});

ftest('cancel during initial file lookup prevents a later FFmpeg launch',async f=>{const original=f.store.resolve.bind(f.store);let release;f.store.resolve=async rel=>{await new Promise(r=>release=r);return original(rel);};const operation=f.store.analyze({rel:'night.wav'});while(!release)await new Promise(r=>setTimeout(r,1));const rejection=A.rejects(operation,/отменён/);f.store.cancelAnalysis();release();await rejection;A.equal(f.store.analyses.size,0);A.equal(f.store.analysisCache.size,0);});
ftest('cancel during search lookup prevents later metadata transmission',async f=>{const original=f.store.resolve.bind(f.store);let release,calls=0;f.store.resolve=async rel=>{await new Promise(r=>release=r);return original(rel);};f.store.fetchJson=async()=>{calls++;return [];};const operation=f.store.search({rel:'night.wav',consent:true});while(!release)await new Promise(r=>setTimeout(r,1));const rejection=A.rejects(operation,/отменён/);f.store.cancelSearches();release();await rejection;A.equal(calls,0);});
ftest('current cover presentation may replace an older auto palette when saving text',async f=>{let r=await f.store.presentation({rel:'night.wav',theme:{paletteSource:'cover',gradientColors:['#123456','#112233']}});const current=L.theme({paletteSource:'cover',gradientColors:['#b0c0d0','#ffddaa']});r=await f.store.save({rel:'night.wav',revision:r.revision,doc:demo(),theme:current});A.deepEqual(r.theme,current);});

ftest('artist-only canonical query can retrieve typoed title from a Latin catalog',async f=>{const requests=[];f.store.fetchJson=async url=>{requests.push(String(url));return url.searchParams.get('q')==='morgenstern'?[{id:55,trackName:'Повод',artistName:'MORGENSTERN',duration:24,plainLyrics:'Original synthetic example'}]:[];};const result=await f.store.search({rel:'night.wav',artist:'BUYSELL',title:'Моргенштерн - Пвод [HD]',consent:true});A.equal(result[0].id,55);A.ok(result[0].approximate);A.ok(requests.length<=8);});
