'use strict';
const test=require('node:test'),A=require('node:assert/strict'),https=require('node:https'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{EventEmitter}=require('node:events'),{Readable}=require('node:stream'),crypto=require('node:crypto');
const T=require('../app/updates/transport'),{extractTools}=require('../app/updates/zip');
const config={repository:{owner:'owner',name:'repo'},releaseAsset:'pulsedeck-update-{channel}.json',componentsAsset:'pulsedeck-components-{channel}.json'};
const url='https://github.com/owner/repo/releases/download/v2.8.1/file.exe',hash=b=>crypto.createHash('sha256').update(b).digest('hex');
async function mock(routes,work){const original=https.get,calls=[];https.get=(u,options,cb)=>{calls.push(String(u));const req=new EventEmitter();req.setTimeout=()=>req;req.destroy=e=>req.emit('error',e);process.nextTick(()=>{const route=routes[String(u)];if(!route){req.emit('error',Error('unexpected request'));return;}const res=Readable.from(route.chunks||[route.body||Buffer.alloc(0)]);res.statusCode=route.status||200;res.headers=route.headers||{};res.setTimeout=()=>res;cb(res);});return req;};try{return await work(calls);}finally{https.get=original;}}
async function temp(work){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pd280-transport-'));try{return await work(dir);}finally{fs.rmSync(dir,{recursive:true,force:true});}}
test('280 streamed download checks exact size/hash, commits only .exe after fsync',()=>temp(async dir=>{const data=Buffer.from('MZ real streaming unit data'),file=path.join(dir,'app.exe');await mock({[url]:{body:data,headers:{'content-length':String(data.length)}}},async()=>{await T.download({url,size:data.length,sha256:hash(data)},file,{config});A.deepEqual(fs.readFileSync(file),data);A.equal(fs.existsSync(file+'.part'),false);});}));
test('280 corrupted download removes partial and never publishes executable',()=>temp(async dir=>{const data=Buffer.from('bad'),file=path.join(dir,'app.exe');await mock({[url]:{body:data}},async()=>{await A.rejects(T.download({url,size:data.length,sha256:'0'.repeat(64)},file,{config}),{code:'UPDATE_HASH_MISMATCH'});A.equal(fs.existsSync(file),false);A.equal(fs.existsSync(file+'.part'),false);});}));
test('280 size mismatch from header or stream is rejected',()=>temp(async dir=>{for(const headers of [{},{'content-length':'100'}])await mock({[url]:{body:Buffer.alloc(100),headers}},async()=>{await A.rejects(T.download({url,size:5,sha256:'0'.repeat(64)},path.join(dir,'app.exe'),{config}),{code:'UPDATE_SIZE_MISMATCH'});});}));
test('280 truncated stream cannot publish and an existing good destination survives',()=>temp(async dir=>{const dest=path.join(dir,'app.exe');fs.writeFileSync(dest,'good old');await mock({[url]:{body:Buffer.from('x')}},async()=>{await A.rejects(T.download({url,size:10,sha256:'0'.repeat(64)},dest,{config}),{code:'UPDATE_HASH_MISMATCH'});A.equal(fs.readFileSync(dest,'utf8'),'good old');});}));
test('280 GitHub asset redirect allowed; foreign redirect blocks before foreign request',()=>temp(async dir=>{const data=Buffer.from('MZdata'),final='https://release-assets.githubusercontent.com/allowed';await mock({[url]:{status:302,headers:{location:final}},[final]:{body:data}},async calls=>{await T.download({url,size:data.length,sha256:hash(data)},path.join(dir,'a.exe'),{config});A.equal(calls.length,2);});await mock({[url]:{status:302,headers:{location:'https://evil.test/file.exe'}}},async calls=>{await A.rejects(T.download({url,size:data.length,sha256:hash(data)},path.join(dir,'b.exe'),{config}),{code:'UPDATE_UNTRUSTED_URL'});A.equal(calls.length,1);});}));
test('280 malformed redirect is a safe error rather than an uncaught exception',()=>mock({[url]:{status:302,headers:{location:'https://['}}},async()=>A.rejects(T.jsonBytes(url),{code:'UPDATE_UNTRUSTED_URL'})));
test('280 manifest size cap is enforced before parsing',()=>mock({[url]:{body:Buffer.alloc(1000)}},async()=>A.rejects(T.jsonBytes(url,{maxBytes:128}),{code:'UPDATE_MANIFEST_TOO_LARGE'})));
test('280 rate-limit status is distinguishable from no new version',()=>mock({[url]:{status:429}},async()=>A.rejects(T.jsonBytes(url),{code:'UPDATE_RATE_LIMITED'})));
test('280 release discovery filters draft and prerelease on stable and uses the named asset',async()=>{const api='https://api.github.com/repos/owner/repo/releases?per_page=30',feed='https://github.com/owner/repo/releases/download/v2.8.1/pulsedeck-update-stable.json';const records=[{draft:true,prerelease:false,assets:[{name:'pulsedeck-update-stable.json',browser_download_url:'https://evil.test/draft'}]},{draft:false,prerelease:true,assets:[{name:'pulsedeck-update-stable.json',browser_download_url:'https://evil.test/beta'}]},{draft:false,prerelease:false,assets:[{name:'pulsedeck-update-stable.json',browser_download_url:feed}]}];await mock({[api]:{body:Buffer.from(JSON.stringify(records))},[feed]:{body:Buffer.from('SIGNED ENVELOPE')}},async calls=>{A.equal((await T.fetchFeed(config,'stable')).toString(),'SIGNED ENVELOPE');A.deepEqual(calls,[api,feed]);});});
// Tiny stored ZIP creator: tests central directory interpretation without third-party tooling.
function zip(files){let offset=0,locals=[],centrals=[];for(const item of files){const name=Buffer.from(item.name),data=Buffer.from(item.data||'MZbinary');const local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(20,4);local.writeUInt32LE(data.length,18);local.writeUInt32LE(item.claimed??data.length,22);local.writeUInt16LE(name.length,26);locals.push(local,name,data);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt32LE(data.length,20);c.writeUInt32LE(item.claimed??data.length,24);c.writeUInt16LE(name.length,28);c.writeUInt32LE(item.attrs||0,38);c.writeUInt32LE(offset,42);centrals.push(c,name);offset+=local.length+name.length+data.length;}const cd=Buffer.concat(centrals),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(cd.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,cd,end]);}
const pair=[{name:'ffmpeg/bin/ffmpeg.exe'},{name:'ffmpeg/bin/ffprobe.exe'}];
test('280 ZIP extracts exact FFmpeg pair and retains license, ignores other executables',()=>temp(async dir=>{const file=path.join(dir,'tools.zip'),dest=path.join(dir,'out');fs.writeFileSync(file,zip([...pair,{name:'ffmpeg/LICENSE.txt',data:'GPL license'},{name:'ffmpeg/evil.exe'}]));await extractTools(file,dest);A.equal(fs.readFileSync(path.join(dest,'ffmpeg.exe'),'utf8'),'MZbinary');A.equal(fs.readFileSync(path.join(dest,'notices','LICENSE.txt'),'utf8'),'GPL license');A.equal(fs.existsSync(path.join(dest,'evil.exe')),false);}));
for(const name of ['../outside.exe','/absolute.exe','C:/evil','bin/../../x','x\0x'])test('280 unsafe component ZIP path rejected '+JSON.stringify(name),()=>temp(async dir=>{const file=path.join(dir,'bad.zip');fs.writeFileSync(file,zip([...pair,{name}]));await A.rejects(extractTools(file,path.join(dir,'out')),{code:'COMPONENT_BAD_ARCHIVE'});}));
test('280 archive rejects symlinks, duplicate binaries, bomb claims and missing FFprobe',()=>temp(async dir=>{for(const files of [[...pair,{name:'sym',attrs:(0xa1ff<<16)>>>0}],[...pair,{name:'another/ffmpeg.exe'}],[{...pair[0],claimed:800*1024*1024},pair[1]],[pair[0]]]){const file=path.join(dir,'bad.zip');fs.writeFileSync(file,zip(files));await A.rejects(extractTools(file,path.join(dir,'out')));}}));
