'use strict';
const test=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const S=require('../app/updates/security'),T=require('../app/updates/transport'),{UpdateManager}=require('../app/updates/manager'),{ComponentManager}=require('../app/updates/components'),{resolveStorage}=require('../app/storage-paths'),{CatalogService}=require('../app/i18n');
const bytes=Buffer.from('MZsigned-test-payload-not-an-executable'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const makeKeys=()=>{const keys=crypto.generateKeyPairSync('ed25519');return {privateKey:keys.privateKey,publicKey:keys.publicKey.export({type:'spki',format:'pem'})};};
function context(overrides={}){
 const keys=makeKeys(),root=fs.mkdtempSync(path.join(os.tmpdir(),'pd280-')),config={repository:{owner:'test-owner',name:'test-repo'},publicKey:keys.publicKey,releaseAsset:'pulsedeck-update-{channel}.json',componentsAsset:'pulsedeck-components-{channel}.json',checkIntervalHours:12};
 const manifest={schema:1,product:'com.pulsedeck.music',kind:'application',version:'2.8.1',platform:'win32',arch:'x64',channel:'stable',notes:{ru:'Проверка',en:'Test <b>literal</b>'},file:{url:'https://github.com/test-owner/test-repo/releases/download/v2.8.1/PulseDeck.exe',size:bytes.length,sha256:sha(bytes)}};
 const sign=(m=manifest)=>{const payload=Buffer.from(JSON.stringify(m));return Buffer.from(JSON.stringify({schema:1,payload:payload.toString('base64'),signature:crypto.sign(null,payload,keys.privateKey).toString('base64')}));};
 const calls=[],transport={...T,fetchFeed:async()=>{calls.push('feed');return sign();},download:async(file,target,{onProgress})=>{calls.push('download');fs.writeFileSync(target,bytes);onProgress({percent:100});return target;}};
 const options={config,current:'2.8.0',profile:root,cache:path.join(root,'cache'),platform:'win32',arch:'x64',clock:()=>100000000,transport,guard:async()=>[],install:async()=>calls.push('install'),...overrides};
 const manager=new UpdateManager(options);return {keys,root,config,manifest,sign,calls,transport,manager,options,close(){manager.close();fs.rmSync(root,{recursive:true,force:true});}};
}
function fixture(name,fn){test('280 '+name,async()=>{const c=context();try{await fn(c);}finally{c.close();}});}
for(const [a,b,result]of [['2.8.10','2.8.9',1],['2.8.1','2.8.1-beta.2',1],['2.8.1-beta.10','2.8.1-beta.2',1],['2.8.1-alpha','2.8.1-beta',-1],['2.8.1+42','2.8.1+43',0],['3.0.0','2.99.99',1],['2.8.1-1','2.8.1-a',-1],['2.8.1-alpha','2.8.1-alpha.1',-1]])test(`280 semver ${a} vs ${b}`,()=>A.equal(S.compare(a,b),result));
for(const v of ['2.08.0','v2.8.0','2.8','2.8.0-beta.01','../../file','1.2.3;cmd','1.2.3-','1.2.3.4'])test('280 rejects invalid version '+v,()=>A.throws(()=>S.version(v)));
fixture('signature verifies exact bytes and wrong-key/tampering fails',c=>{A.equal(S.verifyEnvelope(c.sign(),c.config).version,'2.8.1');const e=JSON.parse(c.sign());e.payload=Buffer.from(JSON.stringify({...c.manifest,version:'9.0.0'})).toString('base64');A.throws(()=>S.verifyEnvelope(JSON.stringify(e),c.config),{code:'UPDATE_BAD_SIGNATURE'});A.throws(()=>S.verifyEnvelope(c.sign(),{...c.config,publicKey:makeKeys().publicKey}),{code:'UPDATE_BAD_SIGNATURE'});});
fixture('wrong product, oversize and unsigned envelopes fail closed',c=>{A.throws(()=>S.verifyEnvelope(c.sign({...c.manifest,product:'other'}),c.config),{code:'UPDATE_WRONG_PRODUCT'});A.throws(()=>S.verifyEnvelope(Buffer.alloc(S.MAX_ENVELOPE+1),c.config),{code:'UPDATE_MANIFEST_TOO_LARGE'});A.throws(()=>S.verifyEnvelope(JSON.stringify({payload:'e30='}),c.config));});
fixture('repository configuration requires a bundled Ed25519 public key',c=>{A.equal(S.ready({repository:c.config.repository,publicKey:''}),false);A.equal(S.ready({repository:null,publicKey:c.config.publicKey}),false);A.equal(S.ready(c.config),true);A.equal(S.repoURL({repository:null}),'');A.equal(S.repository({repository:{owner:'../test',name:'x'}}),null);});
fixture('signed file target/channel/version/size validation rejects invalid manifests',c=>{for(const patch of [{channel:'beta'},{version:'2.8.1-beta.1'},{platform:'linux'},{arch:'arm64'},{kind:'components'},{minimumVersion:'3.0.0'},{file:{...c.manifest.file,size:0}},{file:{...c.manifest.file,sha256:'00'}}])A.throws(()=>S.applicationManifest({...c.manifest,...patch},c.config,{current:'2.8.0'}));A.equal(S.applicationManifest({...c.manifest,version:'2.7.1'},c.config,{current:'2.8.0'}).newer,false);});
for(const url of ['http://github.com/test-owner/test-repo/releases/download/v1/a.exe','https://github.com.evil.test/test-owner/test-repo/releases/download/v1/a.exe','https://user:pass@github.com/test-owner/test-repo/releases/download/v1/a.exe','https://github.com/other/repo/releases/download/v1/a.exe','file:///C:/x.exe','https://github.com/test-owner/test-repo/releases/download/v1/a.exe#x'])fixture('rejects untrusted download '+url,c=>A.throws(()=>S.allowedURL(url,c.config)));
fixture('redirect object hosts allowed only for redirects; component allowlist is narrow',c=>{const u='https://release-assets.githubusercontent.com/file';A.throws(()=>S.allowedURL(u,c.config));A.equal(S.allowedURL(u,c.config,{redirect:true}),u);A.ok(S.allowedURL('https://www.gyan.dev/ffmpeg/builds/packages/a.zip',c.config,{component:true}));A.throws(()=>S.allowedURL('https://www.gyan.dev/evil.exe',c.config,{component:true}));});
fixture('unconfigured check/start/download never touches a network or executes',async c=>{c.manager.config={repository:null,publicKey:''};await c.manager.onStartup();A.equal((await c.manager.check()).phase,'unconfigured');await A.rejects(c.manager.download());A.deepEqual(c.calls,[]);A.equal(c.manager.timer,null);});
fixture('unsupported platform never fetches update feed',async c=>{c.manager.platform='linux';A.equal((await c.manager.check()).phase,'unsupported');A.deepEqual(c.calls,[]);});
fixture('single-flight and manual rate limit avoid duplicate network checks',async c=>{await Promise.all([c.manager.check(),c.manager.check(),c.manager.check()]);await c.manager.check();A.equal(c.calls.filter(x=>x==='feed').length,1);A.equal(c.manager.state.phase,'available');});
fixture('network errors are not falsely reported as up to date',async c=>{c.transport.fetchFeed=async()=>{throw S.fail('UPDATE_TIMEOUT');};await c.manager.check();A.equal(c.manager.state.phase,'error');A.equal(c.manager.state.lastCheck,0);A.equal(c.manager.state.error,'UPDATE_TIMEOUT');});
fixture('newer available then download+restart validates and calls installer exactly once',async c=>{await c.manager.check();await c.manager.download('restart');A.equal(c.manager.state.phase,'installing');A.equal(c.calls.filter(x=>x==='install').length,1);A.ok(fs.existsSync(path.join(c.root,'cache','PulseDeck-2.8.1.exe')));});
fixture('download now/install at next launch persists and does not install now',async c=>{await c.manager.check();await c.manager.download('next-launch');A.equal(c.manager.state.phase,'ready');A.ok(!c.calls.includes('install'));const next=new UpdateManager(c.options);try{await next.onStartup();A.ok(c.calls.includes('install'));}finally{next.close();}});
fixture('ready pending is preserved when checking and cancel-deferred leaves file intact',async c=>{await c.manager.check();await c.manager.download('next-launch');await c.manager.check();A.equal(c.manager.state.phase,'ready');await c.manager.defer('ready');A.equal(c.manager.pending.mode,'ready');await c.manager.onStartup();A.ok(!c.calls.includes('install'));});
fixture('dirty editor or active media blocks quit without discarding downloaded payload',async c=>{await c.manager.check();await c.manager.download();c.manager.guard=async()=>['editor'];await c.manager.apply();A.equal(c.manager.state.phase,'ready');A.equal(c.manager.state.error,'UPDATE_WORK_IN_PROGRESS');A.ok(c.manager.pending);A.ok(!c.calls.includes('install'));});
fixture('corrupted cached file, missing file and replaced repo block installation',async c=>{await c.manager.check();await c.manager.download();const file=path.join(c.root,'cache',c.manager.pending.file);fs.writeFileSync(file,Buffer.alloc(bytes.length));await c.manager.apply();A.ok(!c.calls.includes('install'));A.equal(c.manager.state.error,'UPDATE_HASH_MISMATCH');await c.manager.restore();A.equal(c.manager.pending,null);});
fixture('symlink cache cannot run even when its target has the expected digest',async c=>{await c.manager.check();await c.manager.download();const file=path.join(c.root,'cache',c.manager.pending.file),other=path.join(c.root,'other');fs.renameSync(file,other);fs.symlinkSync(other,file);await c.manager.apply();A.ok(!c.calls.includes('install'));});
fixture('re-checks cached bytes after renderer acknowledgement to prevent an intervening replacement',async c=>{await c.manager.check();await c.manager.download();c.manager.guard=async()=>{fs.writeFileSync(path.join(c.root,'cache',c.manager.pending.file),'tampered');return [];};await c.manager.apply();A.ok(!c.calls.includes('install'));});
fixture('failed startup update is not retried automatically in a loop',async c=>{await c.manager.check();await c.manager.download('next-launch');await c.manager.onStartup({failed:true});A.equal(c.manager.pending.mode,'ready');A.equal(c.manager.state.error,'UPDATE_INSTALL_FAILED');A.ok(!c.calls.includes('install'));});
fixture('channel changes discard pending packages and disabling automatic cancels scheduling',async c=>{await c.manager.check();await c.manager.download();c.manager.configure({prerelease:true,automatic:false});A.equal(c.manager.channel,'beta');A.equal(c.manager.pending,null);A.equal(c.manager.timer,null);A.equal(c.manager.prefs.automatic,false);});
fixture('installer launch failure leaves current process and pending data usable',async c=>{await c.manager.check();await c.manager.download();c.manager.install=async()=>{throw Error('spawn EACCES');};await c.manager.apply();A.equal(c.manager.state.phase,'ready');A.equal(c.manager.state.error,'UPDATE_INSTALL_FAILED');});
fixture('cancel download leaves available state and no installation',async c=>{await c.manager.check();c.transport.download=(_file,_dest,{signal})=>new Promise((_r,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(Error('aborted'),{name:'AbortError'})),{once:true}));const p=c.manager.download('restart');c.manager.cancel();await p;A.equal(c.manager.state.phase,'available');A.equal(c.manager.pending,null);A.ok(!c.calls.includes('install'));});
fixture('new successful installed version discards obsolete pending package',async c=>{await c.manager.check();await c.manager.download();const next=new UpdateManager({...c.options,current:'2.8.1'});try{await next.restore();A.equal(next.pending,null);}finally{next.close();}});

function component(c,{busy=()=>false,probe=async()=>true}={}){return new ComponentManager({root:path.join(c.root,'components'),legacy:path.join(c.root,'legacy-tools'),config:c.config,current:'2.8.0',platform:'win32',isBusy:busy,probe,transport:c.transport});}
function catalog(c,m,sequence=1){const entry={id:'ytdlp',version:'2026.09.01',format:'exe',license:'GPL-3.0-or-later',sourceURL:'https://github.com/yt-dlp/yt-dlp',file:{...c.manifest.file,url:'https://github.com/yt-dlp/yt-dlp/releases/download/2026.09.01/yt-dlp.exe'}};const payload={schema:1,product:'com.pulsedeck.music',kind:'components',platform:'win32',arch:'x64',channel:'stable',sequence,components:[entry]};c.transport.fetchFeed=async()=>c.sign(payload);return {entry,payload};}
fixture('unconfigured app does not block independent publisher checks',async c=>{const m=component(c);m.config={};c.transport.jsonBytes=async url=>{c.calls.push(url);throw Object.assign(Error('offline fixture'),{code:'UPDATE_NETWORK_ERROR'});};await m.check();A.equal(m.state.phase,'error');A.equal(c.calls.length,2);A.ok(c.calls.some(x=>x.includes('api.github.com/repos/yt-dlp')));A.equal(m.snapshot().source,'publishers');});
fixture('component install verifies binary, atomically switches and keeps previous for rollback',async c=>{const m=component(c),{entry}=catalog(c,m);await m.check();await m.install('ytdlp');A.ok(m.resolve('yt-dlp.exe').includes('2026.09.01'));const newer={...entry,version:'2026.09.02'};await m.install('ytdlp',newer);A.equal(m.index.ytdlp.previous,'2026.09.01');await m.rollback('ytdlp');A.equal(m.index.ytdlp.active,'2026.09.01');});
fixture('busy tool is not replaced; original index and executable remain',async c=>{let busy=false;const m=component(c,{busy:()=>busy}),{entry}=catalog(c,m);await m.install('ytdlp',entry);busy=true;await A.rejects(m.install('ytdlp',{...entry,version:'2026.09.02'}),{code:'COMPONENT_BUSY'});A.equal(m.index.ytdlp.active,'2026.09.01');});
fixture('failed binary/probe never publishes a new component index',async c=>{const m=component(c,{probe:async()=>{throw Error('probe failed');}}),{entry}=catalog(c,m);await A.rejects(m.install('ytdlp',entry));A.equal(m.index.ytdlp,undefined);A.equal(m.resolve('yt-dlp.exe'),'');});
fixture('older signed component feed cannot replace a newer approved catalog',async c=>{const m=component(c);catalog(c,m,9);await m.check();catalog(c,m,8);await m.check();A.equal(m.state.error,'COMPONENT_OLD_CATALOG');});
fixture('component manager checks minimum app version and excludes incompatible items',async c=>{const m=component(c),{payload}=catalog(c,m);payload.components[0].minimumVersion='9.0.0';c.transport.fetchFeed=async()=>c.sign(payload);await m.check();A.deepEqual(Object.keys(m.catalog),[]);});
fixture('rollback refuses corrupted stored tool and leaves active intact',async c=>{const m=component(c),{entry}=catalog(c,m);await m.install('ytdlp',entry);await m.install('ytdlp',{...entry,version:'2026.09.02'});fs.writeFileSync(path.join(m.root,'ytdlp','2026.09.01','yt-dlp.exe'),'BAD');await A.rejects(m.rollback('ytdlp'));A.equal(m.index.ytdlp.active,'2026.09.02');});
fixture('stored component path traversal is not resolved',c=>{const m=component(c);m.index.ytdlp={active:'../../outside'};A.equal(m.resolve('yt-dlp.exe'),'');});
fixture('legacy storage paths remain unchanged and user music is never moved',c=>{const root=path.join(c.root,'installed');fs.mkdirSync(path.join(root,'music'),{recursive:true});fs.writeFileSync(path.join(root,'music','song.wav'),'music');const env={APPDATA:path.join(c.root,'profile'),LOCALAPPDATA:path.join(c.root,'local')};const s=resolveStorage({root,platform:'win32',env,home:path.join(c.root,'home')});A.equal(s.music,path.join(root,'music'));A.equal(s.data,path.join(root,'data'));A.equal(fs.readFileSync(path.join(s.music,'song.wav'),'utf8'),'music');A.equal(s.tools,path.join(root,'components')); const again=resolveStorage({root:path.join(c.root,'new-installed'),platform:'win32',env,home:path.join(c.root,'home')});A.equal(again.music,s.music);});
fixture('new installations place user data outside replaceable program directory',c=>{const root=path.join(c.root,'installed'),env={APPDATA:path.join(c.root,'profile'),LOCALAPPDATA:path.join(c.root,'local')};const s=resolveStorage({root,platform:'win32',env,home:path.join(c.root,'home')});for(const k of ['music','data','profile','languages'])A.ok(!s[k].startsWith(root),k);});
fixture('corrupted persisted storage is not silently replaced',c=>{const env={APPDATA:path.join(c.root,'profile'),LOCALAPPDATA:path.join(c.root,'local')},p=path.join(env.APPDATA,'PulseDeck');fs.mkdirSync(p,{recursive:true});fs.writeFileSync(path.join(p,'storage.json'),'{broken');A.throws(()=>resolveStorage({root:c.root,platform:'win32',env,home:c.root}),/STORAGE_CONFIG_INVALID/);A.equal(fs.readFileSync(path.join(p,'storage.json'),'utf8'),'{broken');});
fixture('user catalog overrides retain new bundled keys and English fallback',c=>{const base=path.join(c.root,'base'),custom=path.join(c.root,'languages');fs.mkdirSync(base);fs.mkdirSync(custom);for(const [lang,messages]of [['en',{New:'New',Fallback:'English'}],['ru',{New:'Новое',Old:'Старое'}]])fs.writeFileSync(path.join(base,lang+'.json'),JSON.stringify({meta:{name:lang},messages}));fs.writeFileSync(path.join(custom,'ru.json'),JSON.stringify({meta:{name:'Русский'},messages:{Old:'Мой перевод'}}));const i=new CatalogService(base,'ru');i.setOverrideDirectory(custom);A.equal(i.t('Old'),'Мой перевод');A.equal(i.t('New'),'Новое');A.equal(i.t('Fallback'),'English');A.equal(i.t('NotFound'),'NotFound');});
fixture('new IPC maintenance actions reject another window and subframes',async c=>{const {harness}=require('./main-harness');const h=harness({requireOverrides:{'./updates/config.json':{schema:1,repository:null,publicKey:'',checkIntervalHours:12,releaseAsset:'pulsedeck-update-{channel}.json',componentsAsset:'pulsedeck-components-{channel}.json',componentsMode:'publishers'}}});try{for(const channel of ['updates:status','updates:check','updates:configure','updates:download','updates:install','components:status','components:check','components:install']){await A.rejects(Promise.resolve().then(()=>h.rawHandlers.get(channel)({sender:h.overlay.webContents}))); h.main.webContents.mainFrame={};await A.rejects(Promise.resolve().then(()=>h.rawHandlers.get(channel)({sender:h.main.webContents,senderFrame:{}}))); }A.equal((await h.invoke('updates:check')).phase,'unconfigured');}finally{h.close();}});
