'use strict';
(() => {
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],api=window.setup;
 let picker=null;
 let cfg={catalogs:{},language:'en',version:''},phase='welcome',currentFolder='',busy=false,lastProgress=null,folderEpoch=0;
 function t(key,args={}){const translated=cfg.catalogs[cfg.language]?.[key],english=cfg.catalogs.en?.[key];const raw=typeof translated==='string'&&translated.trim()?translated:typeof english==='string'&&english.trim()?english:key;return String(raw).replace(/\{(\w+)\}/g,(_m,k)=>args[k]??`{${k}}`);}
 function text(node,key,args){node.textContent=key?t(key,args):'';}
 function translate(){const language=cfg.languages?.find(l=>l.code===cfg.language);document.documentElement.lang=language?.locale||cfg.language;document.documentElement.dir=language?.direction||'ltr';for(const n of $$('[data-i18n]'))text(n,n.dataset.i18n);for(const n of $$('[data-i18n-title]'))n.title=t(n.dataset.i18nTitle);for(const n of $$('[data-i18n-aria-label]'))n.setAttribute('aria-label',t(n.dataset.i18nAriaLabel));picker?.setValue(cfg.language,t('SetupLanguage'));$('#version').textContent=cfg.version;text($('#existingHint'),cfg.existing?'SetupExisting':'SetupNoExisting');text($('#welcomeView h2'),cfg.existing?'SetupUpdateWelcome':'SetupWelcome');text($('#install span'),cfg.mode==='uninstall'?'SetupUninstall':cfg.existing?'SetupUpdate':'SetupInstall');if(cfg.mode==='uninstall'){text($('#welcomeView h2'),'SetupUninstallTitle');text($('#existingHint'),'SetupUninstallHint');}renderPlaces();if(lastProgress)progress(lastProgress);}
 function icons(root=document){for(const n of root.querySelectorAll('[data-icon]'))n.innerHTML=window.Icon(n.dataset.icon,16);}
 function show(view){phase=view;for(const name of ['welcome','progress','result'])$('#'+name+'View').hidden=name!==view;}
 function renderPlaces(){const host=$('#places');host.replaceChildren(...(cfg.places||[]).map(place=>{const b=document.createElement('button');b.type='button';b.textContent=t(place.key);b.addEventListener('click',()=>loadFolders(place.path));return b;}));}
 async function inspect(){try{const s=await api.inspect($('#targetPath').value);cfg.existing=!!s.existing;translate();}catch{/* Backend will provide the same localized validation before any writes. */}}
 async function loadFolders(folder,fallback=''){const epoch=++folderEpoch;$('#folderError').hidden=true;try{const result=await api.folders(folder);if(epoch!==folderEpoch)return;currentFolder=result.folder;$('#folderPath').value=result.folder;$('#parentFolder').disabled=result.parent===result.folder;$('#parentFolder').dataset.path=result.parent;$('#folderList').replaceChildren(...result.items.map(item=>{const b=document.createElement('button');b.type='button';b.setAttribute('role','listitem');b.innerHTML=window.Icon('folder',14);const name=document.createElement('span');name.textContent=item.name;b.append(name);b.addEventListener('click',()=>loadFolders(item.path));return b;}));if(!result.items.length){const p=document.createElement('p');text(p,'SetupEmptyFolder');$('#folderList').append(p);}}catch{if(epoch!==folderEpoch)return;if(fallback&&fallback!==folder){await loadFolders(fallback);return;}text($('#folderError'),'SetupErrorPath');$('#folderError').hidden=false;}}
 function progress(event){if(event.phase==='blocked')return;lastProgress=event;
  if(event.phase==='error'){show('result');$('#resultOrb').classList.add('bad');$('#resultOrb').innerHTML=window.Icon('alert',26);text($('#resultStep'),'SetupFailed');text($('#resultTitle'),'SetupFailed');text($('#resultHint'),event.error||'SetupErrorGeneric');$('#resultPath').textContent='';$('#launch').hidden=true;$('#retry').hidden=false;return;}
  if(['done','removed'].includes(event.phase)){show('result');$('#resultOrb').classList.remove('bad');$('#resultOrb').innerHTML=window.Icon('check',26);text($('#resultStep'),'SetupTitle');text($('#resultTitle'),event.phase==='removed'?'SetupRemoved':'SetupFinished');text($('#resultHint'),event.phase==='removed'?'SetupUninstallHint':'SetupFinishedHint');$('#resultPath').textContent=event.target||$('#targetPath').value;$('#launch').hidden=event.phase==='removed';$('#retry').hidden=true;return;}
  show('progress');const phases={waiting:'SetupWaiting',runtime:'SetupRuntime',components:'SetupComponents',verifying:'SetupVerifying',extracting:'SetupExtracting',installing:'SetupInstalling',finalizing:'SetupFinalizing',rollback:'SetupRollback'};
  text($('#progressStep'),cfg.mode==='uninstall'?'SetupUninstallTitle':'SetupTitle');text($('#progressTitle'),phases[event.phase]||'SetupPreparing');text($('#progressHint'),event.phase==='components'?'SetupComponentsHint':'SetupNoClose');const pct=Math.max(0,Math.min(100,Number(event.percent)||0));$('#setupProgress').classList.toggle('indeterminate',!event.percent);$('#setupProgress').style.setProperty('--progress',`${pct}%`);$('#setupProgress').setAttribute('aria-valuenow',String(Math.round(pct)));$('#setupProgress').setAttribute('aria-label',t(phases[event.phase]||'SetupPreparing'));$('#percent').textContent=event.percent?`${Math.round(pct)}%`:'-';text($('#fileCount'),event.total?'SetupFileCount':null,{done:event.done||0,total:event.total||0});const index=event.phase==='finalizing'?2:event.phase==='installing'?1:0;$$('.install-steps>span').forEach((n,i)=>{n.classList.toggle('active',i===index);n.classList.toggle('done',i<index);});
 }
 async function execute(){if(busy)return;busy=true;lastProgress=null;$('#close').disabled=true;$('#languageSwitch').setAttribute('aria-disabled','true');picker?.setDisabled(true);progress({phase:'verifying'});
  try{const result=await api.execute({target:$('#targetPath').value,desktop:$('#desktop').checked,language:cfg.language});if(!result?.ok)progress({phase:'error',error:result?.error||'SetupErrorGeneric'});}
  catch{progress({phase:'error',error:'SetupErrorGeneric'});}finally{busy=false;$('#close').disabled=false;picker?.setDisabled(false);$('#languageSwitch').removeAttribute('aria-disabled');}
 }
 function close(){if(busy)return;api.close().catch(()=>{});}
 $('#close').addEventListener('click',close);$('#finishClose').addEventListener('click',close);$('#minimize').addEventListener('click',()=>api.minimize());$('#install').addEventListener('click',execute);$('#retry').addEventListener('click',()=>{lastProgress=null;show('welcome');translate();});$('#launch').addEventListener('click',async()=>{const ok=await api.launch().catch(()=>false);if(!ok)progress({phase:'error',error:'SetupErrorGeneric'});});
 $('#targetPath').addEventListener('change',inspect);
 $('#browse').addEventListener('click',()=>{const d=$('#folderDialog');d.showModal();loadFolders((cfg.places||[]).find(p=>p.key==='SetupApplications')?.path||cfg.places?.[0]?.path,(cfg.places||[]).find(p=>p.key==='SetupHome')?.path);});
 for(const id of ['folderClose','folderCancel'])$('#'+id).addEventListener('click',()=>$('#folderDialog').close());$('#folderDialog').addEventListener('click',e=>{if(e.target===$('#folderDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
 $('#folderForm').addEventListener('submit',e=>{e.preventDefault();loadFolders($('#folderPath').value);});$('#parentFolder').addEventListener('click',()=>loadFolders($('#parentFolder').dataset.path));$('#useFolder').addEventListener('click',()=>{if(!currentFolder)return;const sep=currentFolder.includes('\\')?'\\':'/';const base=currentFolder.replace(/[\\/]+$/,'');$('#targetPath').value=/(?:^|[\\/])PulseDeck$/i.test(base)?base:base+sep+'PulseDeck';$('#folderDialog').close();inspect();});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&busy)e.preventDefault();});
 api.onProgress(progress);icons();
 api.bootstrap().then(value=>{cfg=value;
  // Compatibility with older IPC fixtures; production supplies names/flags from JSON meta
  cfg.languages ||= Object.keys(cfg.catalogs).map(code=>({code,name:code.toUpperCase(),locale:code}));
  cfg.language=window.PulseLanguageChoice.choose(cfg.languages,cfg.systemLanguages||navigator.languages,cfg.language);
  picker=new window.SetupLanguagePicker({languages:cfg.languages,value:cfg.language,label:t('SetupLanguage'),onChange:code=>{cfg.language=code;translate();}});
  $('#targetPath').value=cfg.target;if(cfg.mode==='uninstall'){$('.checkbox-card').hidden=true;$('#browse').hidden=true;$('#targetPath').readOnly=true;$('.safe-note').hidden=true;}translate();show('welcome');document.body.classList.add('ready');}).catch(()=>{text($('#existingHint'),'SetupErrorGeneric');$('#install').disabled=true;});
})();
