#!/usr/bin/env node
'use strict';
// Maintainer-only tool. Never imported by the application. Private keys are read
// only from a supplied file; generated keys must stay outside the working tree.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const S=require('../app/updates/security');
const ROOT=path.resolve(__dirname,'..'),CONFIG=path.join(ROOT,'app/updates/config.json');
function assert(value,message){if(!value)throw new Error(message);}
function outsideTree(file){const rel=path.relative(ROOT,path.resolve(file));assert(rel.startsWith('..'+path.sep)||path.isAbsolute(rel),'Store private keys outside the repository');}
function writeNew(file,value,mode=0o644){fs.mkdirSync(path.dirname(path.resolve(file)),{recursive:true});fs.writeFileSync(file,value,{flag:'wx',mode});}
function keygen(prefix){assert(prefix,'A private directory and key prefix are required');outsideTree(prefix);assert(!fs.existsSync(prefix+'.private.pem')&&!fs.existsSync(prefix+'.public.pem'),'Refusing to replace existing keys');const keys=crypto.generateKeyPairSync('ed25519');writeNew(prefix+'.private.pem',keys.privateKey.export({format:'pem',type:'pkcs8'}),0o600);writeNew(prefix+'.public.pem',keys.publicKey.export({format:'pem',type:'spki'}));return prefix+'.public.pem';}
function configure(repo,keyFile,configFile=CONFIG){let r=String(repo||'').replace(/^https:\/\/github\.com\//,'').replace(/\/$/,'').replace(/\.git$/,'');const parts=r.split('/');assert(parts.length===2,'Expected owner/repository or its HTTPS GitHub URL');const publicKey=fs.readFileSync(keyFile,'utf8');const old=JSON.parse(fs.readFileSync(configFile,'utf8')),next={...old,repository:{owner:parts[0],name:parts[1]},publicKey};assert(S.ready(next),'Invalid repository or Ed25519 public key');fs.writeFileSync(configFile,JSON.stringify(next,null,2)+'\n');return next;}
function signingKey(file,config){assert(S.ready(config),'Configure the official repository and Ed25519 PUBLIC key before signing');assert(file,'Specify a private key file');outsideTree(file);const key=crypto.createPrivateKey(fs.readFileSync(file));assert(key.asymmetricKeyType==='ed25519','An Ed25519 private key is required');const got=crypto.createPublicKey(key).export({format:'der',type:'spki'}),want=crypto.createPublicKey(config.publicKey).export({format:'der',type:'spki'});assert(got.equals(want),'Private key does not match the configured public key');return key;}
function signEnvelope(manifest,key){const bytes=Buffer.from(JSON.stringify(manifest));assert(bytes.length<256*1024,'Manifest too large');return JSON.stringify({schema:1,payload:bytes.toString('base64'),signature:crypto.sign(null,bytes,key).toString('base64')},null,2)+'\n';}
function asset(file,url){const st=fs.lstatSync(file);assert(st.isFile()&&!st.isSymbolicLink(),'A regular artifact file is required');assert(st.size>0&&st.size<=1024*1024*1024,'Artifact size is outside the supported range');return{url,size:st.size,sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')};}
function application({config,key,exe,version,minimumVersion='2.8.0',notes={}}){const v=S.version(version);assert(path.basename(exe)===`PulseDeck-Setup-${version}.exe`,'Installer filename must match the version');S.version(minimumVersion);assert(S.compare(version,minimumVersion)>=0,'Release is older than minimumVersion');const header=fs.openSync(exe,'r'),magic=Buffer.alloc(2);try{fs.readSync(header,magic,0,2,0);}finally{fs.closeSync(header);}assert(magic.toString()==='MZ','Expected a Windows executable');const file=asset(exe,`${S.repoURL(config)}/releases/download/v${version}/${encodeURIComponent(path.basename(exe))}`);S.fileSpec(file,config);const messages={};for(const code of ['ru','en']){assert(typeof notes[code]==='string'&&notes[code].trim(),'Supply release notes in both ru and en');assert(notes[code].length<=12000,'Release notes exceed 12,000 characters');messages[code]=notes[code];}
 return Object.fromEntries((v.pre.length?['beta']:['stable','beta']).map(channel=>{const manifest={schema:1,product:'com.pulsedeck.music',kind:'application',platform:'win32',arch:'x64',channel,version,minimumVersion,notes:messages,file};S.applicationManifest(manifest,config,{current:minimumVersion,channel});return[`pulsedeck-update-${channel}.json`,signEnvelope(manifest,key)];}));}
function components({config,key,catalog}){assert(catalog&&['stable','beta'].includes(catalog.channel),'Choose stable or beta');assert(Number.isSafeInteger(catalog.sequence)&&catalog.sequence>0,'Positive monotonic sequence required');assert(Array.isArray(catalog.components)&&catalog.components.length>0&&catalog.components.length<=2,'Supply one or two approved components');const used=new Set();const items=catalog.components.map(c=>{assert(['ffmpeg','ytdlp'].includes(c.id)&&!used.has(c.id),'Invalid or duplicate component');used.add(c.id);assert(/^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$/.test(c.version||''),'Invalid component version');assert(c.format===(c.id==='ffmpeg'?'zip':'exe'),'Incorrect component format');assert(typeof c.license==='string'&&c.license.trim(),'Record the binary distribution license');assert(typeof c.sourceURL==='string'&&c.sourceURL.startsWith('https://'),'Record the corresponding source URL');const source=new URL(c.sourceURL);assert(!source.username&&!source.password,'Invalid source URL');assert(c.minimumVersion,'Specify the minimum compatible PulseDeck version');S.version(c.minimumVersion);const file=S.fileSpec(c.file,config,{component:true});return{id:c.id,version:c.version,format:c.format,minimumVersion:c.minimumVersion,license:c.license,sourceURL:c.sourceURL,file};});return signEnvelope({schema:1,product:'com.pulsedeck.music',kind:'components',platform:'win32',arch:'x64',channel:catalog.channel,sequence:catalog.sequence,components:items},key);}
function options(args){const out={};for(let i=0;i<args.length;i++){assert(/^--[a-z-]+$/.test(args[i]),'Expected --option value');const key=args[i].slice(2);assert(i+1<args.length&&!args[i+1].startsWith('--'),'Missing option value');out[key]=args[++i];}return out;}
function main(args=process.argv.slice(2)){const command=args.shift(),o=options(args);if(command==='keygen'){console.log('Public key written to '+keygen(o.prefix));return;}if(command==='configure'){const c=configure(o.repo,o['public-key']);console.log('Configured official source: '+S.repoURL(c));return;}const config=JSON.parse(fs.readFileSync(CONFIG,'utf8')),key=signingKey(o['private-key']||process.env.PULSEDECK_PRIVATE_KEY_FILE,config),out=path.resolve(o.out||'dist');fs.mkdirSync(out,{recursive:true});
 if(command==='application'){const version=o.version||JSON.parse(fs.readFileSync(path.join(ROOT,'app/package.json'))).version;const files=application({config,key,exe:o.exe||path.join(out,`PulseDeck-Setup-${version}.exe`),version,minimumVersion:o.minimum||'2.8.0',notes:{ru:fs.readFileSync(o['notes-ru'],'utf8'),en:fs.readFileSync(o['notes-en'],'utf8')}});for(const [name,data]of Object.entries(files)){writeNew(path.join(out,name),data);console.log('Signed '+name);}}
 else if(command==='components'){const catalog=JSON.parse(fs.readFileSync(o.catalog,'utf8'));const name=`pulsedeck-components-${catalog.channel}.json`;writeNew(path.join(out,name),components({config,key,catalog}));console.log('Signed '+name);}
 else throw new Error('Commands: keygen --prefix; configure --repo --public-key; application --private-key --exe --notes-ru --notes-en [--out]; components --private-key --catalog [--out]');
}
if(require.main===module){try{main();}catch(e){console.error(e.message);process.exitCode=1;}}
module.exports={keygen,configure,signingKey,signEnvelope,application,components,asset,options};
